/**
 * Bilgi Havuzu — Uzun ansiklopedi makaleleri.
 * Güneş Sistemi ve ötesi hakkında derinlemesine, Türkçe, gerçek verilerle
 * yazılmış 15 makale. /api üzerinden değil, doğrudan lib olarak kullanılır.
 */

export interface KnowledgeArticle {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  paragraphs: string[];
  facts: string[];
}

export const ARTICLES: KnowledgeArticle[] = [
  {
    id: "samanyolu",
    title: "Samanyolu: Evimiz",
    subtitle: "100-400 milyar yıldızlı çubuklu sarmal bir adada, merkezden 26.660 ış yıllık bir mahalle",
    category: "Galaksi",
    paragraphs: [
      "Işık kirliliğinden uzak bir gecede gökyüzünde gördüğün sol ışık şeridi, aslında bir galaksinin içinden bakışın sonucudur: Samanyolu. Çubuklu sarmal (SBbc) tipinde, çapı yaklaşık 100.000 ışık yılı olan bir yıldız adasıdır; içinde 100-400 milyar yıldız, milyarlarca gezegen, gaz ve toz bulutu ile gökten çok daha ağır bir görünmez madde barındırır. Üstten bakılsaydı merkezden açılan sarmal kollarıyla bir gül gibi, kenardan bakılsaydı ince bir disk gibi görünürdü — ama biz tam ortasında yaşıyoruz ve çoğunlukla yalnızca kesitini görebiliyoruz.",
      "Galaksinin merkezinde bir çubuk uzanır: yaşlı yıldızlardan oluşan uzun bir silindir. Çubuğun uçlarından büyük sarmal kollar açılır: Perseus, Sagittarius, Scutum-Centaurus ve Norma kolları. Güneş, bu büyük kollardan birine ait değildir; Orion Spuru denen, Sagittarius ile Perseus kolları arasında sıkışmış küçük bir kol parçasında oturur. Kollar sabit yapılar da değildir: yoğunluk dalgalarıdır — otoyolda geçici olarak sıkışan arabalar gibi, yıldızlar bu yoğun bölgelerden akıp geçer.",
      "Merkezde Sagittarius A* var: 4,15 milyon güneş kütlesinde bir süperkütleli karadelik. Yıldız S2'nin onun çevresindeki 16 yıllık eliptik koşusu, karadeliğin varlığını tartışmasız kanıtladı ve bir Nobel Ödülü getirdi; 2022'de Event Horizon Telescope onun ilk fotoğrafını yayımladı — 26.000 ışık yılı ötede, turuncu parlayan bir gaz halkası. Ama bu karadelik, galaksinin kütlesinin binde birinden azını temsil eder: Samanyolu'nun asıl mimarı, görünmez kütledir.",
      "Güneş, merkezden 26.660 ışık yılı uzakta bulunur ve saniyede 220-230 km (saatte ~828.000 km) hızla çevresinde döner. Bir turu tamamlaması yaklaşık 230 milyon yıl sürer: buna bir 'galaktik yıl' denir. Güneş son galaktik turunu dinozorlar izledi; doğduğu günden beri ancak yirmiye yakın tur attı. Üstelik Güneş, galaktik düzlemin üstünde altında ~60-70 milyon yıllık bir salınım da yapar — bazı bilim insanları bu salınımın Oort Bulutu'nu sarsarak çarpma oranını artırdığını düşünüyor.",
      "Diskin dışında küresel bir hale uzanır: içinde ~150 küresel yıldız kümesi — her biri bir milyona yakın yıldızın birbirine dolandığı, evrenin en eski yapılarından (12-13 milyar yaş) olan topluluklar. Hale, galaksinin bebekliğinden kalma yaşlı yıldız arşividir. Ama asıl ağırlık onun bile ötesindedir: galaksi kütlesinin ~%85-90'ı karanlık maddedir. Bu görünmez hale, dış bölgelerin beklenmedik dönüş hızını açıklar; onsuz Samanyolu çoktan dağılmış olurdu.",
      "Samanyolu yalnız değildir: 'Yerel Grup' denen ~50 galaksili bir mahallede yaşar. En büyük komşusu Andromeda (M31), 2,5 milyon ışık yılı ötede ve saatte ~400.000 km hızla bize doğru gelir. ~4,5 milyar yıl sonra iki galaksi çarpışıp 'Milkomeda' adında dev bir eliptik galakside birleşecek — yıldızlar neredeyse hiç çarpmayacak (uzay o kadar boştur), ama gece gökyüzü sonsuza kadar değişecektir.",
      "Bu tablo, çıplak gözle başlayan bir keşif zincirinin ürünüdür: Galileo 1610'da teleskopuyla şeridi yıldızlara böldü; Herschel 1780'lerde ilk galaksi haritalarını çizdi; Shapley 20. yüzyılın başında merkezin Yay takımyıldızında olduğunu gösterdi. Bugün ESA'nın Gaia sondası iki milyardan fazla yıldızın konumunu, uzaklığını ve hareketini ölçtü: Samanyolu artık durağan bir fotoğraf değil, yıldız akıntıları ve eski çarpma kalıntılarıyla dolu yaşayan bir film.",
    ],
    facts: [
      "Merkeze bakan yön (Yay takımyıldızı) en yoğun yıldız ve toz manzarasını sunar; merkezdeki toz, görünür ışığı milyarlarca kat söndürür.",
      "Güneş'in galaktik yörünge hızı ~220-230 km/sn'dir: ışık hızının yaklaşık %0,07'si — yine de bir tur 230 milyon yıl alır.",
      "~150 küresel kümenin en parlakları çıplak gözle bile görünür: Omega Centauri, belki küçük bir galaksinin yutulmuş çekirdeğidir.",
      "Samanyolu her yıl birkaç yeni yıldız üretir; Andromeda birleşmesi bu oranı dramatik biçimde artıracak bir 'yıldız patlaması' dönemi başlatacak.",
      "Karanlık madde halesi, görünür diskin kat kat ötesine uzanır; onu 'görmek' için tek yol, yıldızların dönüş hızını ölçmektir.",
      "Orion Spuru'ndaki en yakın komşular: Alpha Centauri sistemi (4,24 ış yılı) ve Barnard Yıldızı (5,96 ış yılı) — ve bu mahalle, galaksi ölçeğinde olağanüstü boştur.",
      "2022 EHT fotoğrafındaki turuncu halka, karadeliğin çevresinde dönen sıcak gazdır: görüntü, dünyanın dört bir yanındaki 8 radyoteleskobun verisinin birleşimidir.",
      "Sagittarius cüce galaksisi şu an Samanyolu tarafından yutulmaktadır: galaksiler büyümek için birbirini yutar ve kayıtları halede hâlâ okunabilir.",
    ],
  },
  {
    id: "gunesin-dogusu",
    title: "Güneş Sistemi Nasıl Doğdu?",
    subtitle: "Bir moleküler bulutun çöküşünden 4,6 milyar yıllık bir aileye",
    category: "Güneş",
    paragraphs: [
      "Yaklaşık 4,6 milyar yıl önce, Samanyolu'nun Orion Spuru yakınında soğuk ve karanlık bir dev moleküler bulut duruyordu: -260 °C'ye yaklaşan sıcaklıkta hidrojen molekülleri, toz taneleri ve buz. Belki komşu bir süpernovanın şok dalgası, belki iki bulutun çarpışması bu dengeyi bozdu: bulutun bir bölgesi kendi kütleçekimiyle çökmeye başladı. En güçlü kanıt, ilkel meteoritlerdeki alüminyum-26 izotopudur — ömrü çok kısa bu elementi yalnızca süpernova gibi bir patlama 'doldurmuş' olabilir.",
      "Çöken bulut dönmeye başladı: açısal momentum korunumu gereği küçüldükçe hızlandı ve düzleşti. Merkezde proto-Güneş toplandı; çevresinde dönen, ince bir gaz-toz diski kuruldu. Nebular hipotez tam olarak bunu öngörür — fikri 18. yüzyılda Kant ve Laplace düşündü; bugün ALMA radyoteleskobu, genç yıldızların çevresindeki bu diskleri doğrudan fotoğraflıyor.",
      "Diskte toz taneleri çarpışıp yapıştı: önce statik elektrik, sonra kütleçekimi devreye girdi. Milyonlarca yıl içinde metrelerce, sonra kilometrelerce 'planetesimal', ardından 1.000 km'lik protoplanetler doğdu. Donma çizgisinin içinde ısı buzları yok etti; kaya ve metal birikerek karasal gezegenleri kurdu. Dışında buz da katıydı: Jüpiter ve Satürn, büyük buz-kaya çekirdekleri kurup diskten devasa gaz topladı; Uranüs ve Neptün daha az gaz yakalayarak buz devi oldu.",
      "Asteroit kuşağı ve Kuiper kuşağı, bu inşaatın artıklarıdır: Jüpiter'in devasa çekimi, Mars ile onun arasındaki malzemenin hiçbir zaman gezegen toplayamamasını sağladı; uzaktaki soğuk ve seyrek disk ise buzlu gövdeleri olduğu gibi 'donmuş' bıraktı. Vesta, gezegen olmaya başlamış bir protogezegendir; Arrokoth ise dokunulmamış bir planetesimal — 2019'da New Horizons onun iki yumrunun yumuşakça birleşmiş 4,6 milyar yıllık bir fosili olduğunu gösterdi.",
      "Yeni Güneş bir T Tauri yıldızıydı: şiddetli rüzgârlar ve patlamalarla etrafını temizledi. Bu güneş rüzgârı, diskin kalan gazını ~10-100 milyon yıl içinde süpürdü ve gezegenlerin büyümesini kesti. Süpürge olmasaydı tarih bambaşka olurdu: disk gazı, Jüpiter'i Güneş'e doğru sürükleyebilirdi.",
      "Sonra büyük bir göç geldi: Nice modeline göre dev gezegenler doğdukları yerden kaydı. Jüpiter önce içeri yürüdü, Satürn'le 2:1 rezonansına girince geri çekildi ('Grand Tack' manevrası); Neptün dışarı savrulup Kuiper kuşağını taradı. Bu göçün döküntüsü iç sisteme yağdı: ~4 milyar yıl önceki Büyük Bombardıman, Ay'ın krater haritasını bugünkü yüzüne getirdi.",
      "Ve Ay: Mars büyüklüğünde Theia adlı protoplanet, genç Dünya'ya çarptı (~4,5 milyar yıl önce). Savrulan malzeme yörüngede toplanıp Ay'ı kurdu. Sistem sonra sakinleşti: Dünya soğudu, okyanuslar yağdı ve ilk yaşam ~3,8-4 milyar yıl önce belirdi — Güneş Sistemi'nin bebeklik yaralarından biri, hayatın sahnesine dönüştü.",
    ],
    facts: [
      "En eski katı malzeme, meteoritlerdeki CAI taneleridir: 4,567 milyar yaşındadır ve Güneş Sistemi'nin 'doğum belgesi' sayılır.",
      "Jüpiter'in önce içeri gidip Satürn'le rezonansa girerek geri çekilmesi (Grand Tack), Mars'ın bugünkü küçüklüğünü de açıklar.",
      "Asteroit kuşağının toplam kütlesi Ay'ın yalnızca ~%4'üdür: gezegen olamayan bölge, aslında neredeyse boş bir artıklıktır.",
      "Yeni doğan Güneş bugünkünden sönüktü (~%70 parlaklık): 'genç Güneş paradoksu', Dünya'nın neden donmadığını sorar — cevap büyük olasılıkla sera gazlarında.",
      "Theia çarpması Dünya'yı bir magma okyanusuna çevirdi: bugünkü kıtalar, bu eriyiğin soğuyup katmanlaşmasından doğdu.",
      "Arrokoth'a 2019'daki uçuş, iki yumrunun çarpışmadan birleştiğini gösterdi: 'yumuşak birikme' (soft accretion) ilk kez yakından görüldü.",
      "Plüton'un Sputnik Planitia'sındaki azot buzu hâlâ akar: 4,6 milyar yıl önce doğan buzun, bugün bile jeolojik olarak 'canlı' olabildiğini kanıtlar.",
    ],
  },
  {
    id: "apollo-11",
    title: "Ay'a İlk Adım: Apollo 11",
    subtitle: "1969 yazında 384.000 km ötede, insanlık tarihini değiştiren 21,5 saat",
    category: "Ay",
    paragraphs: [
      "25 Mayıs 1961'de Kennedy, Kongre'de tek cümle kurdu: 'Bu on yıl bitmeden, bir insanı Ay'a indirip güvenle geri getireceğiz.' O gün bu hedef bilim kurgu gibiydi — NASA henüz 15 dakikalık bir yörünge uçuşu bile yapmamıştı. Sekiz yıl, ~400.000 kişilik iş gücü ve devasa bir bütçeyle Saturn V doğdu: bugüne kadar uçan en güçlü roket. 110 metre boyunda, ~3.000 ton ağırlığında ve 34.000 kN itkiyle — üç Boeing 747 motorunun toplamından fazla. 16 Temmuz 1969 sabahı milyonlarca kişi Florida kıyısında bu devin ateşini izledi: Dünya'nın ~384.400 km ötesindeki Ay'a yolculuk başladı.",
      "Uzay aracı üç parçaydı: Columbia (komuta modülü), servis modülü ve Ay modülü Eagle. Michael Collins, Columbia'da Ay yörüngesinde tek başına kaldı — her yörünge turunda ~48 dakika Ay'ın arkasında, tüm insanlıktan ve Dünya'dan habersiz uçtu. Armstrong ve Aldrin ise Eagle ile inişe geçti: bilgisayar iniş sırasında 1202 ve 1201 alarm kodları verdi, Houston birkaç saniyede karar verdi: 'devam et'.",
      "İniş anın kritiğe ulaştığı yerdi: otomatik hedefin kayalarla dolu bir krater kenarı olduğunu gören Armstrong, yarı otomatik modda eliyle yöneterek yatayda ilerleyip düz bir alana doğru manevra yaptı. Yakıt uyarıları çalıyordu — iniş anında Eagle'ın tankında yaklaşık 25 saniyelik yakıt kalmıştı. 20 Temmuz 1969, 20:17 UTC: 'Houston, Tranquility Base here. The Eagle has landed.' — dünyada milyonlarca kişi nefes aldı.",
      "Yaklaşık 6,5 saat sonra, 21 Temmuz 02:56 UTC, Armstrong merdivenden indi ve ay tozuna bastı: 'İnsan için küçük bir adım, insanlık için dev bir sıçrama.' (Bir tartışma hâlâ sürer: Armstrong 'bir insan için' anlamında 'a man' mi dedi, yoksa 'man' mi? Kayıt net değil, kendisi 'a man' dediğini savunur.) Aldrin onu ~19 dakika sonra izledi ve yüzeyi iki kelimeyle tanımladı: 'Magnificent desolation' — muhteşem bir ıssızlık. Aldrin ayrıca kendi inancı gereği Ay yüzeyinde küçük bir komünyon töreni yaptı: Ay'daki ilk dini tören.",
      "Yüzeyde toplam 2 saat 31 dakika yürüdüler: bayrağı diktiler (rüzgâr olmadığı için direğe esnek bir yatay çubuk gerildi), ABD Başkanı Nixon'la konuşuldular ve bilimsel paket EASEP'yi kurdular: pasif sismometre ve lazer yansıtıcı — o yansıtıcı bugün bile Dünya'dan gönderilen lazerle Ay mesafesini milimetre hassasiyetiyle ölçüyor. 21,5 kg ay taşı ve tozu topladılar; uzay aracının ayağında, 'Buradan her insana barışla gelin' anlamındaki plaketi bıraktılar. Toplamda 21,5 saat yüzeyde kaldılar; sonra Eagle fırlayıp Columbia'ya döndü.",
      "24 Temmuz'da Pasifik'e indiler; mürettebat, ay mikropları korkusuyla 21 gün karantinaya alındı (bugün gereksiz olduğu bilinir). Televizyonda ~600 milyon kişi tarihin o ana kadarki en büyük canlı yayınını izledi. Apollo 11'in ardından 5 görev daha Ay'a indi: toplam 12 insan Ay'da yürüdü (Apollo 11, 12, 14, 15, 16, 17). Apollo 13 ise hiç inemedi: patlayan oksijen tankından sonra mürettebat, Ay modülünü canbot olarak kullanarak Ay'ın çevresinden döndü — NASA'nın 'başarısız başarı'sı, mühendislik tarihinin en parlak kriz yönetimlerinden biri.",
      "Bugün Ay'da insanlığın bıraktığı ilk ayak izleri hâlâ durur: atmosfer ve rüzgâr olmadığından milyonlarca yıl korunacaklardır. Artemis programı insanlığı Ay'a döndürmeyi hedefliyor — bu kez güney kutbundaki su buzu rezervleriyle, kalıcı bir üs için. Apollo'nun asıl mirası belki de budur: 'imkansız' dediğin hedefi, planlı ve sistematik çalışmayla 'mümkün'e çevirmenin kanıtı.",
    ],
    facts: [
      "Saturn V hâlâ uçan en güçlü roketlerden biridir: 34.000 kN itki, ~3.000 ton kalkış ağırlığı.",
      "Michael Collins, Columbia'da yalnızken her yörünge turunda ~48 dakika Ay'ın arkasında telsizsiz kalıyordu.",
      "Ay'da rüzgâr ve su olmadığı için Armstrong'un ayak izleri milyonlarca yıl bozulmadan kalacaktır.",
      "Bırakılan lazer yansıtıcı hâlâ çalışır: Dünya'dan ölçülen mesafe, Ay'ın yılda 3,8 cm uzaklaştığını gösterdi.",
      "Aldrin'in Ay'daki komünyonu, görevin en az bilinen anlarındandır: küçük bir kadeh ve ekmek, Ay yüzeyinde ilk dini tören oldu.",
      "Apollo 13 faciasında mürettebat, Ay modülünün 'canbot'una sığınarak eve döndü: patlayan oksijen tankına rağmen kimse kaybolmadı.",
      "Toplam 12 insan Ay'da yürüdü: hepsi 1969-1972 arasındaki Apollo 11, 12, 14, 15, 16 ve 17 görevlerinde; o zamandan beri kimse dönmedi.",
      "Artemis programı, insanlığı Ay'ın güney kutbuna götürmeyi hedefliyor: kutup kraterlerindeki su buzu, kalıcı üs için kaynak olacaktır.",
    ],
  },
  {
    id: "dunyanin-kabugu",
    title: "Dünya'nın Kabuğu ve Levha Tektoniği",
    subtitle: "İnce bir yüzey filmi: milyarlarca yıldır kayan, çarpışan ve yenilenen levhalar",
    category: "Gezegenler",
    paragraphs: [
      "Dünya'nın yüzeyi, gezegen ölçeğinde bir elma kabuğu kadar incedir ve iki türdür. Okyanus kabuğu 5-10 km kalınlığında, yoğun bazalttan oluşur ve gençtir: en eski parçası 200 milyon yıllıktır, çünkü sırtlarda sürekli yeniden doğar ve dalma-batma zonlarında geri döner. Kıta kabuğu 30-70 km, hafif granit benzeri kayaçtan oluşur ve yaşlıdır: Kanada'daki Acasta gnaysı 4,03 milyar yıllıktır — gezegenin bebekliğinden kalan bir parça.",
      "Kabuk ile mantoyu ayıran sınır, Mohorovičić süreksizliği ('moho') diye bilinir: sismik dalgaların hızı burada aniden artar. Manto, Dünya hacminin ~%84'ünü kaplar: katı ama jeolojik zaman ölçeğinde akışkan silikat kayaçtır. Sıcak kaya yükselir, soğuk kaya batar — bu konveksiyon, üstündeki levhaları yılda birkaç santimetre sürükleyen dev motordur.",
      "Merkezde iki katman vardır: dış çekirdek, sıvı demir-nikel eriyiğidir; içinde dönen bu iletken sıvı, jeodinamo üretir — Dünya'nın manyetik alanı. Bu alan, atmosferi güneş rüzgârından korur; onsuz gezegen Mars gibi kururdu. İç çekirdek ise katıdır: ~5.400 °C'ye ulaşan sıcaklığı Güneş yüzeyinden yüksektir ama devasa basınç demiri katı tutar.",
      "Levha sınırları üç tip davranış gösterir. Ayrılma (divergent): Atlantik sırtında yeni okyanus kabuğu doğar, levhalar yılda 2-5 cm uzaklaşır — Atlantik genişlemeye devam ediyor. Yaklaşma (convergent): bir levha diğerinin altına dalar; Pasifik'in 'ateş çemberi'ndeki volkanlar ve en derin çukurlar buradan doğar. Kayma (transform): iki levha birbirine sürtünür — San Andreas fayı; gerilim, depremle aniden boşalır.",
      "Levhaların oyunu kıtaları da gezdirir: ~300 milyon yıl önce tüm kıtalar tek süperkıtaydı — Pangaea. Kıtalar birleşir ve ayrılır (süperkıta döngüsü): her ~400-600 milyon yılda bir yeni bir süperkıta kurulur. Bu döngü, iklimi, okyanus sirkülasyonunu ve evrimin seyrini yönlendirir.",
      "Tektoniğin bedeli de vardır: depremler, levha geriliminin aniden boşalmasıdır; okyanus tabanındaki büyük kaymalar tsunami doğurur. Volkanlar iki yüzlüdür: patlayıcı stratovolkanlar (Vezüv), sakin kalkan volkanlar (Mauna Loa) ve kıta ölçeğinde kalderalar (Krakatoa, Yellowstone). Derinlerde, 150-200 km derinlikte, yüksek basınç ve ısı karbonu kristalize eder: elmas — yüzeye 'kimberlit boruları'yla hızla taşınır.",
      "Peki neden Dünya canlı? Venüs'te tektonik öldü: ısı kabukta hapsoldu, sera kaçtı (+464 °C). Mars'ta çekirdek soğudu: manyetik alan gitti, atmosfer süpürüldü. Dünya'da üçlü çalışır: sıvı su + aktif levha tektoniği + manyetosfer. Bu üçlü karbon-silikat döngüsünü işletir: volkanlar CO₂ basar, yağmur taşır, okyanus tabanında kireç taşına gömülür; tektonik karbonu geri döndürür. Bu gezegen ölçeğindeki termostat, iklimi milyarlarca yıldır yaşanabilir tutar.",
    ],
    facts: [
      "Bugünkü okyanus tabanının tamamı ~200 milyon yıldan gençtir: dinozorlar döneminin okyanus kabuğu artık yok, hep geri dönüştürüldü.",
      "İç çekirdek ~5.400 °C ile Güneş yüzeyinden sıcaktır; ama ~3,6 milyon atmosferlik basınç demiri katı tutar.",
      "Acasta gnaysı (Kanada) 4,03 milyar yaşındadır; 4,4 milyar yıllık zirkon kristalleri, belki de okyanusların o kadar erken var olduğunu gösterir.",
      "Atlantik yılda 2-5 cm genişler: tırnak uzama hızı — ama 200 milyon yılda bir okyanus açar.",
      "Everest hâlâ yükseliyor: Hindistan levhası Asya'ya dalıyor, Himalaya yılda ~4-5 mm kazanıyor.",
      "Elmaslar 150-200 km derinlikte, ~1.000 °C üzerinde ve 45.000+ atmosferde doğar; yüzeye 'kimberlit boruları'yla taşınır.",
      "Levha tektoniği Güneş Sistemi'nde bilinen tek örnektir: Venüs 'durgun kapak' modundadır, Mars'ın tektoniği ölmüştür — karbon termostatının çalışması için hareket şarttır.",
    ],
  },
  {
    id: "asteroit-turleri",
    title: "Asteroit Türleri: Uzayın Kimya Kitabı",
    subtitle: "C, S, M, V, X: her spektroskopi sınıfı, Güneş Sistemi'nin farklı bir bölgesinin ve zamanının imzası",
    category: "Asteroitler",
    paragraphs: [
      "Asteroitler, gezegen olamamış malzemenin arşividir: her sınıf, Güneş Sistemi'nin farklı bir bölgesinde ve farklı bir 'sıcaklıkta' doğdu. Yansıyan ışığın spektrumu bize kimyasal reçetelerini söyler — bu yüzden kuşağa uzayın kimya kitabı denir. Ana sınıflar C, S ve M'dir; alt sınıflar eklenince sayı 20'yi aşar.",
      "C-tipleri (karbonlu): tüm asteroitlerin ~%75'i. Koyu, karbonca zengin gövdelerdir; albedoları 0,03-0,09 arasındadır — kömürden koyu. İçeriği 4,6 milyar yıldır neredeyse hiç değişmemiş ilkel malzemedir: kil mineralleri, organik bileşikler, su izleri. Örnekler: Hygiea, Bennu, Ryugu. C ailesi geniştir: B (Bennu), Cb (Ryugu), Ch, Cg gibi alt sınıflar, kimyadaki ince nüansları taşır.",
      "S-tipleri (silisli, kayalık): ~%17. Olivin-piroksen bakımından zengin, demir-nikel içeren, parlak (albedo ~0,2) gövdelerdir; örnekler: Juno, 433 Eros. İç sistemin 'ısınmış' bölgesinden geldiler; bazıları farklılaşmış gövdelerin kabuk-manto parçalarıdır. M-tipleri (metalik): ~%8. Demir-nikel ağırlıklıdır; en ünlüsü 16 Psyche — büyük olasılıkla patlamış bir protoplanetin çıplak çekirdeği; yüzeyindeki demirin değeri 10^19 dolar mertebesinde tahmin edilir (bazı M-tipleri ise metal-silikat karışımı olabilir). V-tipleri Vesta'nın ailesidir: Dünya'ya düşen HED meteoritlerinin kaynağı. X-tipleri ise spektrumu gizemli gövdelerdir: radar ve albedo olmadan metal mi, karbon mu ayırt edilemez.",
      "Rubble pile (çakıl yığını): bazı asteroitler katı kaya değil, zayıf yerçekimiyle bir arada tutulan çakıl yığınlardır. Bennu ve Ryugu bunun canlı kanıtlarıdır: dönüşleri hızlanırsa (YORP etkisiyle yavaş yavaş hızlanabilirler) merkezkaç kuvveti onları parçalar. Hayabusa2'nin yapay çarpması Ryugu'nun yüzeyinin gevşek bir örtü olduğunu gösterdi; OSIRIS-REx Bennu'ya dokunduğunda sonda yüzeye ~50 cm 'batdı' — gövde bir yığın.",
      "Yörüngeler de bir hikâye anlatır: Kirkwood boşlukları. Ana kuşakta, Jüpiter'le rezonansa giren mesafelerde asteroit neredeyse yoktur: 3:1, 5:2, 7:3, 2:1 rezonanslarında gezegenin düzenli çekimi gövdeleri yörüngeden 'atar'. Bu boşluklar kuşağın yara izleridir ve aynı zamanda Dünya'ya yakın asteroitlerin (NEO) ana kapılarıdır. NEO'lar üç sınıftır: Aten (Dünya'nın yılından kısa yıllı, çoğunlukla Dünya'nın içinde gezen), Apollo (yörüngesi Dünya'nınkini kesen, Bennu gibi) ve Amor (Dünya'nın dışından geçen). 140 m'den büyük ve 7,5 milyon km'den fazla yaklaşanlar 'Potentially Hazardous' (PHA) listesine girer.",
      "Çarpmalar tarihi değiştirdi: Chicxulub (~66 milyon yıl önce, ~10 km çaplı) Yucatán'da 180 km'lik krater açtı; küresel yangın, tsunamiler ve çarpma kışı, türlerin ~%75'ini — dinozorlar dahil — sildi (memeliler için fırsat penceresi açıldı). Tunguska (1908): ~50-60 m'lik bir gövde Sibirya üzerinde patladı ve 2.000 km²'lik ormanı yelpaze gibi düzleştirdi. Chelyabinsk (2013): ~20 m'lik kaya, 30 km yükseklikte patladı; şok dalgası camları kırıp ~1.500 kişi yaraladı — Rusya'nın dashcam'leri tarihin en iyi kaydedilmiş meteor olayını üretti.",
      "Gelecek iki yönlüdür: madencilik ve savunma. Metalik asteroitler 'sonsuz maden' gibi görünür — ama bugünkü ekonomiyle getirme maliyeti değeri sıfırlar. Savunma ise artık teori değil: NASA'nın DART sondası 26 Eylül 2022'de Dimorphos'a (65803 Didymos'un uydusu) çarptı ve 11 saat 55 dakikalık yörünge süresini ~32 dakika kısalttı — insanlık ilk kez bir gövdenin yörüngesini bilinçli olarak değiştirdi ve ölçtü.",
    ],
    facts: [
      "C-tiplerinin albedosu 0,03-0,09'dur: karbonlu asteroit, betondan on kat koyudur — bu yüzden 'görülmeleri' için büyük olmaları gerekir.",
      "Psyche'deki demir-nikelin piyasa değeri ~10^19 dolar tahmin edilir; ama taşıma maliyeti bu değeri imkânsızlaştırır.",
      "Bennu, Apollo sınıfı bir NEO'dur: 2182'de Dünya'ya çarpma olasılığı ~%0,037 (~1/2.700) — bilinen en yüksek riskli büyük gövdelerden biri.",
      "DART (2022), Dimorphos'un yörünge süresini ~32 dakika kısalttı: beklentinin ~25 katı etki — hedef gövde tahminden daha 'yumuşak' çıktı.",
      "Kirkwood boşlukları, Jüpiter'in 3:1, 5:2, 7:3 ve 2:1 rezonanslarında oluşur: oradaki gövdeler yörüngeleri bozularak iç sisteme gönderilir.",
      "Meteoritlerin ~%86'sı taşlı (kondrit/akondrit), ~%8'i demir, ~%2'si taş-demirdir: pallasitlar, olivin kristalleri demir ağında — 'uzayın en güzel kayası'.",
      "Ryugu'nun ortalama yoğunluğu ~1,2 g/cm³'tür: çakıllar arasında dev boşluklar vardır — içi 'sünger gibi' bir rubble pile.",
      "Chicxulub çarpmasının enerjisi ~100 teraton TNT eşdeğeridir: insanlığın en güçlü nükleer silahının milyarlarca katı.",
    ],
  },
  {
    id: "kuyrukluyildiz-anatomisi",
    title: "Kuyrukluyıldız Anatomisi",
    subtitle: "Kirli kar topundan iki kuyruğa: güneşe yaklaşan bir buz gövdesinin anatomisi",
    category: "Kuyrukluyıldızlar",
    paragraphs: [
      "Kuyruklu yıldızın kalbi çekirdektir: birkaç km'lik, koyu, patates biçimli bir buz-kaya karışımı. Fred Whipple 1950'de 'kirli kar topu' modelini kurdu; bugün 'buzlu kar topu' denebilir, çünkü Halley ve 67P gösterdi ki toz oranı buzdan bile fazla olabilir. Çekirdek o kadar koyudur (albedo ~0,04) ki Giotto'nun 1986 kamerası Halley'in çekirdeğini ancak güneşe bakan kenarında seçebildi.",
      "Güneş'e yaklaşınca (~3-5 AB'den itibaren su; daha uzakta CO ve CO₂) buzlar süblimleşir: gaz ve toz, çekirdekten fırlayıp onu 100.000 km'yi aşan bir atmosferle — koma ile — sarar. Koma, çekirdeğin nefesidir: güneş rüzgârı ve radyasyon basıncı bu nefesi kuyruklara çevirir. Gökyüzünde gördüğün 'yıldız', aslında kilometrelerce küçük bir gövdenin gaz ve toz bulutudur.",
      "İki kuyruk, iki farklı fizik. İyon (plazma) kuyruğu: güneş rüzgârının taşıdığı manyetik alan çizgilerine bağlanır ve HER ZAMAN Güneş'ten uzağa bakar — kuyruklu yıldızın hareket yönüne değil; mavi görünür (CO⁺ iyonları), düz ve dikiş gibidir, güneş patlamalarında kopabilir. Toz kuyruğu: radyasyon basıncıyla itilir, yavaşça eğri bir yay çizer, sarımsı görünür. Üçüncü bir yapı daha vardır: hidrojen halesi — UV'de görülen, milyonlarca km çapında soluk bir kabuk.",
      "Rosetta (ESA) 2014'te 67P/Churyumov-Gerasimenko'nun yörüngesine girdi ve Philae sondası, bir çekirdeğe ilk inişi yaptı. Rosetta'nın on yılı sürprizlerle doluydu: moleküler oksijen (O₂) keşfi; ve suyun döteryum/hidrojen oranının Dünya okyanuslarından ~3 kat fazla çıkması — yani 67P tipi kuyruklu yıldızlar, Dünya'nın suyunun ana kaynağı olamaz: su büyük olasılıkla karbonlu asteroitlerden geldi.",
      "İki aile vardır: Kısa dönemli (< 200 yıl) kuyruklu yıldızlar Kuiper Kuşağı'ndan gelir (Halley 75-76 yıl ile sınırda 'kısa' sayılır). Uzun dönemli olanlar Oort Bulutu'ndan gelir: binlerce, hatta milyonlarca yılda bir güneşe ilk kez uğrarlar (Hale-Bopp gibi). Halley'in retrograd dönüşü, onun belki yakalanmış bir Oort gövdesi olduğunu düşündürür.",
      "Kuyruklu yıldızın toz izi, meteor yağmurlarıdır: Dünya, yörüngesinde bu toz şeritlerini her yıl aynı tarihte keser. Perseidler Swift-Tuttle'dan, Orionidler ve Eta Aquariidler Halley'den gelir. Ve takvimde bir not: Halley 2061 yazında geri dönüyor — bugünkü çocuklar, 1986'yı izleyenlerden çok daha iyi bir manzara görecek.",
    ],
    facts: [
      "İyon kuyruğu her zaman Güneş'ten uzağa bakar: kuyruklu yıldız güneşten uzaklaşırken kuyruk 'öne' düşer — yolcu değil, rüzgâr gülü gibidir.",
      "67P'nin suyunun döteryum oranı Dünya'nınkinin ~3 katıdır: Dünya'nın okyanusları büyük olasılıkla kuyruklu yıldızlardan değil, karbonlu asteroitlerden geldi.",
      "Rosetta, 67P'nin çekirdeğinde moleküler oksijen (O₂) buldu: 'baştan' beri donmuş, kimyasal olarak ilkel malzemenin imzası.",
      "Philae'nin çapaları tutmadı: sonda yüzeyde birkaç kez sıçradı, yarı gölgede kaldı — ama 57 saatlik veri, görevi tarihe yazdırdı.",
      "1986'da 5 uzay aracı 'Halley filosu'nu oluşturdu: ESA'nın Giotto'su çekirdeğe 596 km yaklaşarak ilk yakın fotoğrafları çekti.",
      "Kuyruklu yıldızlar 'ölmez': uçucu buz tükenince yüzey koyu toz kabuğuyla kaplanır ve asteroit gibi sakin bir gövdeye dönüşür.",
      "Devasa görünen koma, çekirdeğin binlerce katıdır: asıl gövde, bulutun içinde neredeyse görünmez bir noktadır.",
    ],
  },
  {
    id: "halka-sistemleri",
    title: "Halka Sistemlerinin Sırrı",
    subtitle: "282.000 km'ye ulaşan bir çap, ama çoğu yerde 10 metre kalınlık: Satürn'ün imkansız tabağı",
    category: "Gezegenler",
    paragraphs: [
      "Satürn'ün halkaları, Güneş Sistemi'nin en ikonik manzarasıdır: içten dışa D, C, B, A, F, G ve E adlı yedi ana halka, sistem çapını ~282.000 km'ye taşır. Ama kalınlıkları şok edicidir: çoğu yerde 10 metre ile 1 km arası. Ölçek gerçek yapılsaydı, halkalar bir futbol sahasında konan bir A4 kağıdından daha ince olurdu.",
      "İçerik %95-99 su buzudur: geri kalanı toz ve kayaç. Parçacıklar mikron boyutundan ev büyüklüğündeki buz bloklarına kadar değişir. Keşif, teleskop tarihinin klasik sahnesidir: Galileo 1610'da 'kulaklar' gördü; Huygens 1655'te bunların bir halka olduğunu anladı; Cassini 1675'te A ile B arasındaki büyük boşluğu (Cassini boşluğu) buldu. Bugün yıldız örtülmesi — halkanın arkasından geçen bir yıldızın ışık kırpışması — halkaların metre ölçeğindeki yapısını çözüyor.",
      "Cassini boşluğu (~4.800 km) bir rezonans mucizesidir: oradaki parçacıklar Mimas'la 2:1 rezonansındadır — her 2 turda 1 kez aynı hizaya gelirler ve dev uydu, düzenli çekimiyle onları o mesafeden kovar. Daha küçük Encke boşluğunun içinde Pan adlı mini bir uydu döner: halkayı 'süpüren' bir kar odacısı.",
      "Halkalar gençtir: Cassini verisi ~100-400 milyon yıl gösterir — Satürn'ün yaşına göre bebek. Bu bir ikilem yaratır: ya halkalar şu an yok olma sürecindedir (Cassini 'halka yağmuru'nu ölçtü: her saniye tonlarca malzeme gezegene düşer), ya da yakın zamanda parçalanmış bir uydu ya da kuyruklu yıldızın kalıntısıdır. İki senaryo da aynı mesajı verir: sistem sakin bir müze değil, geç çarpışmaların sahnesidir.",
      "Uydular, halkaların mimarıdır: 'çoban uydular' (Pan, Prometheus, Janus) kenarlardaki malzemeyi sınırlar; Daphnis, Keeler boşluğunda geçerken ~42 km yükseklikte buz dalgaları kaldırır. Halkaların içinde yoğunluk dalgaları, bir sarmal galaksinin mini kopyası gibi döner. Jüpiter, Uranüs ve Neptün'ün halkaları da vardır ama koyu, ince ve soluktur: toz ağırlıklı, buz yoksunu.",
      "Neden halkalar gezegene düşmez? Cevap Roche limitidir: bir gövde gezegene çok yaklaşırsa gelgit kuvveti onu parçalar. Satürn'ün Roche limiti ~2,5 gezegen yarıçapıdır; halkalar tam bu sınır içinde, parçalanmanın hüküm sürdüğü bölgede uzanır: orada parçalar birleşip uydu olamaz. Ve bir sürpriz: 2017'de cüce gezegen Haumea'da da bir halka bulundu. Quaoar'ın 2023'te keşfedilen halkası ise Roche limitinin belirgin biçimde DIŞINDA: 'imkansız' bir halka, buzun birleşme kurallarını yeniden yazıyor.",
    ],
    facts: [
      "Halkaların toplam kütlesi, Mimas kadar (yani çok az): devasa görünüm, kütlenin yanıltıcı bir çizimidir.",
      "Cassini boşluğunu Mimas'ın 2:1 rezonansı açar: bir uydu, yüz binlerce km öteden halkayı heykeltıraş gibi yontar.",
      "Daphnis (~8 km), Keeler boşluğunda geçerken ~42 km yükseklikte buz dalgaları kaldırır: Cassini'nin en ünlü fotoğraflarından biri.",
      "Satürn'ün halkaları ~100-400 milyon yıllıktır: dinozorlar halkaları görmemiş olabilir — halkalar sistemin 'yeni' süsüdür.",
      "E halkası, Enceladus'un fıskiyelerinden beslenir: uydu, kendi halkasını savurur.",
      "Haumea'nın halkası (2017), bir cüce gezegende bulunan ilk halkadır: yarıçapı ~2.287 km'dir.",
      "Quaoar'ın halkası (2023), Roche limitinin dışında: teori orada parçaların birleşip uydu olması gerektiğini söylüyordu — 'imkansız' halka, birleşme kurallarını değiştirdi.",
    ],
  },
  {
    id: "yasanabilir-bolge",
    title: "Yaşanabilir Bölge ve Yaşam Arayışı",
    subtitle: "Goldilocks bandı: ne çok sıcak ne çok soğuk — ama su, yalnızca bir başlangıç",
    category: "Yaşam",
    paragraphs: [
      "Yaşanabilir bölge (habitable zone), yıldızın çevresinde sıvı suyun gezegen yüzeyinde kalabileceği sıcaklık bandıdır: Güneş için kabaca 0,95-1,4 AB. 'Goldilocks bölgesi' denir: ne çok sıcak, ne çok soğuk. Ama bölge bir garanti değildir: Venüs, Dünya'nın hemen komşusudur ve kontrolsüz sera etkisiyle +464 °C'ye kaçtı; yüzeyinde sıvı su yoktur. Konum, yalnızca kapıyı aralar.",
      "Mars'ın hikâyesi diğer ucu gösterir: 3,5-4 milyar yıl önce nehirler, göller ve belki bir kuzey okyanusu vardı. Sonra çekirdek soğudu, jeodinamo durdu: manyetosfer gitti. Güneş rüzgârı atmosferi süpürmeye başladı (MAVEN sondası bu kaçışı ölçüyor); basınç düştü, su dondu ya da süblimleşti. Ders: yaşanabilir bölge yeterli değildir; koruma da gerekir — manyetosfer, gezegenin şemsiyesidir.",
      "Ama yaşam yıldız ışığına ihtiyaç duymayabilir: Dünya'nın ~5 km derinliğinde, güneşsiz, kayadan ve kimyadan beslenen bakteriler yaşar (derin biyosfer). Bu, Europa ve Enceladus'un buz altındaki okyanuslarını 'yaşanabilir bölge dışı' adaylara çevirir: gelgit ısınması ve radyoaktif ısı, milyarlarca yıldır sabit bir sıvı ortam sağlayabilir. Hidrotermal ocak teorisi tam buraya bağlanır: yaşam, ilk kez bu ocaklarda kimyasal enerjiyle doğmuş olabilir (abiyogenez) — demir-sülfür yüzeylerde organik moleküller birikmiş olabilir.",
      "Görevler şimdiden yolda: NASA'nın Europa Clipper'ı (2024'te fırladı, 2030'da varacak) Europa'yı ~50 kez geçerek okyanusu radarla, manyetik ve gravite ölçümleriyle tarayacak. Cassini, Enceladus'un fıskiyelerinden su buzu, tuz, silika nanoparçacıkları ve organik moleküller ölçtü: deniz tabanında hidrotermal kimya işliyor. Titan ise bambaşka bir ekseni dener: metan-etan gölleri, yoğun azot atmosferi ve muhtemel 'alternatif biyokimya' — su yerine metan çözücüsü kullanan bir hayat artık saf hayal değil.",
      "Yıldızlararası arayış da hızlandı: TRAPPIST-1 sistemi, 40 ışık yılı ötede 7 Dünya-benzeri gezegenli bir kırmızı cücedir — üçü yaşanabilir bölgede. Kırmızı cüceler trilyonlarca yıl yaşar ama gençken fırtınalıdır: atmosferi korumak zordur. Ekstremofiller, arayışın sınırlarını genişletir: Deinococcus radiodurans radyasyonu 'yer', tardigradlar (su ayıları) uzay boşluğunda hayatta kalabilir — hayatın 'sınır' tanımadığını gösterir.",
      "Ve büyük soru: herkes nerede? Fermi paradoksu, milyarlarca yıldız ve milyarlarca yıl karşısında teknolojik bir uygarlığın izini sorar — cevap yok. Adaylar: nadir Dünya hipotezi (tektonik + büyük Ay + Jüpiter kalkanı), 'büyük filtre', ya da salt mesafe ve zaman: sinyallerin yolculuğu yüzyıllar alır. Levha tektoniği burada kritik rol oynar: karbon-silikat termostatı, Dünya'nın iklimini milyarlarca yıl yaşanabilir tuttu — belki de en nadir koşul, su değil, hareketli kabuktur.",
    ],
    facts: [
      "Dünya'nın derin biyosferi ~5 km'ye iner: kayadan beslenen bazı bakteriler yüzyıllarca hücre bölünmeden 'bekleyebilir'.",
      "Enceladus'un fıskiyelerindeki silika nanoparçacıkları, sıcak hidrotermal ocakların imzasıdır: deniz tabanı ~90 °C olabilir.",
      "Europa'nın okyanusu, Dünya'nın tüm okyanuslarının 2-3 katı su içerir: buz kabuğu 15-25 km, okyanus 60-150 km derinliktedir.",
      "TRAPPIST-1'in 7 gezegeni, bir 'kolye' gibi sıkı döner: en dış gezegenin yörüngesi bile Merkür'ünkünden küçüktür.",
      "Tardigradlar, 2007'de uzay boşluğunda (vakum + UV) hayatta kaldılar: 'ton' durumuna girip metabolizmayı neredeyse durdururlar.",
      "Venüs'ün 50-60 km yüksekliğinde sıcaklık ve basınç Dünya'ya yakındır: bazı bilim insanları orada 'aerosol yaşamı' olasılığını tartışır.",
      "Fermi paradoksu 1950'de bir öğle yemeği sohbetinde doğdu: 'Hepsi nerede?' — bugün hâlâ kesin bir cevabı yok.",
    ],
  },
  {
    id: "meteorlar",
    title: "Meteor, Meteorit ve Çarpma Olayları",
    subtitle: "Göktaşının üç hayatı: meteoroid, meteor, meteorit — ve tarihi değiştiren çarpmalar",
    category: "Gezegenler",
    paragraphs: [
      "Terminoloji basittir ama karıştırılır: meteoroid, uzaydaki gövdedir (kum tanesinden ~1 m'ye); meteor, atmosfere girip ışık saçan çizgidir ('kayan yıldız'); meteorit, yüzeye ulaşan parçadır. Dünya her gün 50-100 ton uzay maddesiyle karşılaşır: çoğu kum tanesi boyutundadır ve 80-100 km yükseklikte buharlaşır. Gözle gecede birkaç meteor görürsün; büyük yağmurlar saatte 100+ 'saat hızı' üretebilir.",
      "Meteor yağmurları, kuyruklu yıldız toz izleridir: Dünya, yörüngesinde bu şeritleri her yıl aynı tarihte keser. Perseidler (Ağustos) Swift-Tuttle'ın, Leonidler (Kasım) Tempel-Tuttle'ın izindendir. Geminidler (Aralık) özeldir: kaynağı bir kuyruklu yıldız değil, 3200 Phaethon'dur — güneşe 0,14 AB'ye yaklaşan, yüzeyi 700 °C'ye ısınıp toz saçan bir 'kaya kuyruklu yıldız'. Parlak meteorlara 'bolid' ya da 'ateş topu' denir: Ay'daki çarpmaları bile amatör teleskoplar kaydeder.",
      "Meteoritler üç ailedir: taşlı (kondrit + akondrit) — çoğunluk; demir — demir-nikel, kesitinde milyon yıllar süren yavaş soğumanın ürettiği Widmanstätten desenini taşır; taş-demir — pallasitlar: olivin kristalleri demir ağında, 'uzayın en güzel kayası'. Sikhote-Alin (1947, Rusya) bir demir yağmuru oldu: atmosferde parçalanıp 100'den fazla krater açtı. Bilinen en büyük meteorit Hoba'dır (Namibya, ~60 ton): yassı girişi nedeniyle krater bile açmadan düştü ve bugün hâlâ yerinde durur.",
      "Çarpmalar tarihi değiştirir: Chicxulub (~66 milyon yıl önce) ~10 km çaplı bir asteroitti — Yucatán'da 180 km'lik krater açtı; küresel yangınlar, tsunamiler ve çarpma kışı, türlerin ~%75'ini sildi: dinozorların sonu, memelilerin şafağı. Tunguska (1908): ~50-60 m'lik gövde, Sibirya üzerinde patladı ve 2.000 km² ormanı düzleştirdi — krater yok, çünkü patlama havada oldu. Chelyabinsk (2013): ~20 m'lik kaya, ~500 kilotonluk havada patlama üretti; şok dalgası camları kırıp ~1.500 kişi yaraladı — dashcam'ler olayı tarihin en iyi kaydedilmiş meteoru yaptı.",
      "Savunma artık bir mühendislik disiplinidir: LINEAR, Pan-STARRS ve NEOWISE gibi tarama programları Dünya'ya yakın gövdeleri kataloglar; 140 m üstü ve 7,5 milyon km'den fazla yaklaşanlar PHA listesine girer. 2022'de DART, Dimorphos'a çarptı ve yörünge süresini ~32 dakika kısalttı: ilk 'gezegen savunma testi' başarılıydı. Zincir bütündür: tespit → yörünge hesabı → planlama → müdahale. Tunguska boyutu bir şehri siler; Chicxulub boyutu bir medeniyeti — aradaki fark yalnızca uyarı süresidir.",
    ],
    facts: [
      "Dünya her gün 50-100 ton uzay maddesiyle karşılaşır: çoğu kum tanesi boyutunda ve 80-100 km'de buharlaşır.",
      "Widmanstätten deseni, demir meteoritlerinde milyonlarca yıllık yavaş soğuma ile oluşur: laboratuvarda taklit edilemez — meteorit kimlik kartıdır.",
      "Hoba (Namibya) ~60 ton ile bilinen en büyük meteorittir: yassı girişi nedeniyle krater açmadı ve yüzeyde kaldı.",
      "Chelyabinsk (2013) ~500 kiloton enerji açığa çıkardı: Hiroşima'nın ~30 katı — ama patlama ~30 km yükseklikte olduğu için ölü olmadı.",
      "Perseidler, Swift-Tuttle kuyruklu yıldızının toz izidir: her yıl 12-13 Ağustos civarı zirveye ulaşır.",
      "3200 Phaethon, 'kaya kuyruklu yıldız'dır: güneşe 0,14 AB'ye yaklaşır, yüzeyi ~700 °C'ye ısınır ve Geminid yağmurunun babasıdır.",
      "Sikhote-Alin (1947) demir yağmuru, 100'den fazla krater açtı: göktaşı avcılarının 'klasik sahasıdır'.",
    ],
  },
  {
    id: "uzayin-olcegi",
    title: "Uzayın Dehşet Verici Ölçeği",
    subtitle: "Rakamların insan beynini kırdığı yer: bir milyon kilometre 'boş' sayılır",
    category: "Ölçek",
    paragraphs: [
      "Ölçek, uzayın en sert gerçeğidir: 1 AB (astronomik birim) 149,6 milyon km'dir — ışık bunu 8 dakika 20 saniyede alır. Güneş'ten Neptün'e 4,5 milyar km vardır: ışık ~4 saat 10 dakikada ulaşır. Ama Voyager 1, 17 km/sn hızıyla 47 yılda 'yalnızca' ~25 milyar km gidebildi: ışığın 23 saatlik yolculuğu. İç Güneş Sistemi insan ölçeğinde bir mahalle; dış sistem, başka bir ülkedir.",
      "1 ışık yılı = 9,46 trilyon km. En yakın yıldız Proxima Centauri: 4,24 ışık yılı uzakta. Voyager 1 bu mesafeyi, doğru yöne gidiyor olsaydı bile ~75.000 yılda alırdı. Ve bu 'komşu'dur: Samanyolu 100.000 ışık yılı çapındadır — ışık, diskin bir ucundan öbürüne 100.000 yılda gider. Ötesinde Andromeda 2,5 milyon ışık yılı, görülebilir evren ise ~93 milyar ışık yılı çapındadır (evrenin genişlemesi, ışıktan 'hızlı' uzay büyümesine izin verir).",
      "Model kurarsak: Güneş bir portakal olsaydı (~10 cm), Dünya bir kum tanesi olurdu ve ~11 metre ötede dururdu; Neptün ~330 metre ötede olurdu; en yakın yıldız Proxima ise başka bir portakal olarak ~3.000 km ötede — bir kıta uzağında: New York'tan İstanbul'a bir uçuş mesafesi. Ve arada 'hiçbir şey' yoktur: yalnızca boşluk. Andromeda, bu ölçekte bir kıta ötesinde görünmez bir zarf bile olmazdı.",
      "Boşluk, kuşakların da gerçeğidir: asteroit kuşağında 1 km üstü iki gövde arasındaki ortalama mesafe ~1 milyon km'dir — Dünya-Ay mesafesinin 2,5 katı. Filmlerin 'kaya duvarı' tamamen sanattır: bir sonda, kuşağı fark etmeden bile geçebilir. Kuiper kuşağı daha da boştur: New Horizons, Plüton'a 9 yıllık uçuşunda kaçınacak bir şey bile bulamadı.",
      "Bu yüzden simülasyonlar gerçek ölçek değil, sembolik ölçek kullanır: gezegen boyutları büyütülür, mesafeler kısaltılır ve zaman hıza ayarlanır. Bu projede de böyle yapılır — gerçek oranda Dünya, ekranın tek bir pikseli bile olamazdı: Ölçek 'gerçek' yapılırsa uzay, hiçbir şeyi göstermeyen bir karanlıktır. Gökyüzü haritaları hep yalan söyler — ama doğru yalan söyler.",
      "Ama ölçek, bir armağandır: ışık gecikmesi, 'geçmişe bakış' demektir. Güneş'e baktığında 8 dakika önceki güneşi görürsün; Andromeda'ya baktığında 2,5 milyon yıl önceki bir galaksiyi — belki bugün artık bambaşka bir halde. JWST'nin en derin alanları evrenin bebeklik fotoğraflarıdır: 13 milyar yıl önceki galaksiler. Uzayda uzaklık, geçmişin başka bir adıdır: her teleskop bir zaman makinesidir.",
    ],
    facts: [
      "Güneş'ten Dünya'ya ışık 8 dk 20 sn; Ay'a 1,3 sn; Neptün'e ~4 sa 10 dk; Proxima'ya 4 yıl 3 ay gider.",
      "Voyager 1'in hızıyla (17 km/sn) Proxima'ya varmak ~75.000 yıl sürer — üstelik yörüngesi oraya bakmaz.",
      "1 ışık yılı = 9,46 trilyon km: Dünya'nın ekvatorundan ~236 milyon tur.",
      "Asteroit kuşağında 1 km üstü gövdeler arası ortalama ~1 milyon km boşluk vardır: kuşağın 'dolu' görünmesi sinema sanatıdır.",
      "Görülebilir evren ~93 milyar ış yılı çapındadır — ama evren 13,8 milyar yaşındadır: genişleme, ışıktan 'hızlı' uzay büyütür.",
      "Andromeda'ya baktığında 2,5 milyon yıl önceki halini görürsün: o ışık yola çıktığında Homo sapiens henüz yoktu.",
      "Güneş portakal olsaydı, Dünya ~11 m ötede kum tanesi olurdu; Proxima başka bir portakal olarak ~3.000 km ötede olurdu — bir kıta mesafesi.",
    ],
  },
  {
    id: "cuce-gezegenler",
    title: "Cüce Gezegenler: Gezegen Tanımının Dramı",
    subtitle: "2006'da bir tanım değişti: Plüton'un düşüşü ve beş onaylı cücenin hikayesi",
    category: "Gezegenler",
    paragraphs: [
      "2006'da IAU (Uluslararası Astronomi Birliği) 'gezegen' tanımını netleştirdi: üç kural. 1) Güneş'in yörüngesinde dönmeli. 2) Kütleçekimi onu hidrostatik dengeye — yani küresel forma — sokmalı. 3) Yörünge çevresini 'temizlemiş' olmalı: komşuluğundaki malzemeye hükmetmeli. Plüton ilk ikisini geçer ama üçüncüde başarısızdır: Kuiper kuşağında binlerce komşusuyla paylaşır. Sonuç: 'cüce gezegen' sınıfı doğdu, Plüton düştü.",
      "Krizin tetikleyicisi Eris'ti: 2005'te keşfedilen bu gövde, Plüton'dan daha kütleliydi. Ya Eris de gezegendi, ya Plüton gezegen olmayı bırakacaktı — tanım değişti. Halk tepkisi şaşırtıcıydı: New Mexico ve Illinois eyaletleri 'Plüton bizde hâlâ gezegendir' kararları çıkardı. Sonra 2015'te New Horizons, Plüton'u yakın plana aldı ve herkesin karşısına şaşırtıcı bir dünya çıktı: azot buzulları, su buzu dağlar, genç yüzeyler — 'ölü' sanılan gövde, canlı bir jeoloji gösterdi.",
      "Bugün 5 onaylı cüce gezegen vardır: Ceres (astroid kuşağının en büyüğü, 940 km), Plüton (2.377 km), Haumea (elipsoit: 3,9 saatlik gün ve halka), Makemake (kırmızımsı metan buzu, MK 2 uydusu) ve Eris (küçük ama kütleli: Plüton'dan ~%27 fazla kütle). Her biri farklı bir bölgenin konservidir: Ceres iç kuşağın, diğerleri Kuiper'in ve ötesinin.",
      "Aday listesi uzundur: Sedna (yörüngesi ~11.000 yıl süren, güneşe en uzak 'yakın' gövde), Quaoar (2023'te 'imkansız' halkasıyla ünlendi), Orcus (Plüton'la aynı rezonansı paylaşan 'anti-Plüton'), Gonggong (büyük ve kızıl) ve Hygiea (asteroid kuşağında küresel C-tipi). İyi gözlemlerle sayı 10-20'ye çıkabilir: cüce gezegen sınıfı, Güneş Sistemi'nin en büyüyen kategorisidir.",
      "Dinamik sınıflar, sistemin geçmiş fotoğrafıdır: Plütinolar (Plüton gibi 2:3 rezonansta Neptün'le kilitli), klasik Kuiper gövdeleri (dairesel, düşük eğimli), dağınık disk (Eris: Neptün'ün savurduğu dış merkezlikli yörüngeler) ve ayrık gövdeler (Sedna: Neptün bile dokunamaz). Bu sınıflar, dev gezegenlerin göçünün kayıt defteridir.",
      "Ve en büyük soru: Planet Nine. Bazı ayrık gövdelerin yörüngeleri şaşırtıcı biçimde hizalıdır: bu, belki Dünya'dan 5-10 kat kütleli, güneşten 400-800 AB uzakta dolaşan gizli bir gezegenin eseridir. Arama sürüyor (Subaru, LSST/Vera Rubin): bulunursa Güneş Sistemi'nin dokuzuncu gezegeni olur; bulunmazsa da dağınık diskin 'kendiliğinden' hizalanmasını öğrenmiş oluruz.",
    ],
    facts: [
      "Plüton'un düşüşü astroloji takvimlerini bile sarstı — ama astronomi tanımlarla çalışır: bilim, duyguyla değil kriterlerle ilerler.",
      "Eris, Plüton'dan daha küçük görünsün de daha kütleli ve daha yoğundur: kaya bakımından zengindir.",
      "Haumea, Rugby topu biçimlidir: 3,9 saatlik dönüş gövdeyi iki eksende uzatır; 2017'de halkası keşfedildi.",
      "Sedna'nın yılı ~11.000 yıldır: perihel 76 AB — Neptün'ün yörüngesinin bile iki katı uzaklıkta güneşe yaklaşır.",
      "Quaoar'ın halkası, Roche limitinin dışındadır: teori orada parçaların birleşip uydu olması gerektiğini söylüyordu — kurallar yeniden yazılıyor.",
      "Ceres'in parlak noktaları sodyum karbonattır (tuz): içeriden sızan tuzlu suyun kriyovolkanik kalıntısıdır.",
      "Planet Nine hipotezi, 2016'da Batygin ve Brown'ın yörünge analizinden doğdu: varsa, güneşten ~600 AB uzakta ve sönüklüğü nedeniyle zor bulunur.",
    ],
  },
  {
    id: "gunesin-olumu",
    title: "Güneş'in Ölümü ve Sistemin Kaderi",
    subtitle: "Kırmızı dev, gezegenimsi nebula, beyaz cüce: evimizin milyarlarca yıllık kader haritası",
    category: "Güneş",
    paragraphs: [
      "Güneş şu an kütlesinin ~%73'ünü hidrojen olarak taşır ve her saniye ~4 milyon ton kütlesini ışığa çevirir (E=mc²). Ama denge sonsuz değildir: çekirdekte füzyonla biriken helyum, çekirdeği sıkıştırır ve ısısını artırır; parlaklık ~1,1 milyar yılda ~%10 artar. 1-1,5 milyar yıl sonra Dünya için kritik eşik gelir: artan ısı, karbonat-silikat termostatını bozar ve okyanuslar buharlaşmaya başlar ('nemli sera' dönemi). Yaşam, o tarihten önce derin yeraltına ya da kutuplara sığınmak zorunda kalacaktır.",
      "~5 milyar yıl sonra çekirdekteki hidrojen tükenir: Güneş, evriminin dramatik ayağına girer. Füzyon kabuğa taşınır; dış katmanlar şişer ve soğur — kırmızı dev. Yarıçapı ~0,85 AB'ye ulaşır: Merkür ve Venüs kesin olarak yutulur. Dünya? Sınırda: gelgit sürüklenmesi onu içeri çekerken, Güneş'in kütle kaybı yörüngeyi dışarı iter — hesap 'belki kaçar, belki yutulur' der. Kaçsa bile yüzey erimiş kayadır: bugünkü Venüs'ün bile ötesinde bir cehennem.",
      "Kırmızı devin içinde helyum, ~100 milyon K'ye kadar sıkışır ve aniden tutuşur: 'helyum flaşı' — dakikalar süren, bugünkü Güneş parlaklığının milyarlarca katına çıkan bir füzyon patlaması (ama ısı dışarı sızmaz). Sonra karbon-oksijen çekirdeği kurulur; Güneş dış katmanlarını zarif bir 'gezegenimsi nebula' olarak uzaya savurur: içindeki karbon, azot, oksijen — yaşamın hammaddesi — yıldızlararası buluta karışır. Kalan çekirdek beyaz cücedir: Dünya boyutunda ama Güneş'in yarısı kütlede; yoğunluğu ~1 t/cm³ — bir çay kaşığı, bir filin ağırlığındadır.",
      "Beyaz cüce soğur: milyarlarca yılda soluklaşır ve ~10^15 yıl sonra teorik 'siyah cüce' olur — ama evren 13,8 milyar yaşındadır: henüz hiçbir beyaz cüce o noktaya ulaşmadı; hepsi hâlâ sıcaktır. Gezegenlerin kaderi ise katmanlıdır: iç gezegenler yutulur ya da buharlaşır; dış gezegenler (Jüpiter ve ötesi) Güneş'in kütle kaybıyla genişleyen yörüngelere kayar. Neptün'ün ötesindeki buz dünyaları soğuk arşiv olarak kalır: belki trilyonlarca yıl sonra, birileri onları 'kozmik fosil' olarak bulur.",
      "Evrenin sonu senaryoları daha da uzundur: yıldız doğumu ~10^14 yıl içinde biter; karadelikler Hawking radyasyonuyla ~10^100 yılda buharlaşır; sonunda maksimum entropi — 'ısı ölümü': hiçbir yapısal değişimin olmadığı, yalnızca denge. Ama rahatlatıcı kısım şudur: Güneş ömrünün yalnızca ~%50'sini tamamladı. 5 milyar yıl, dinozorların tüm tarihinin ~30 katıdır: insanlığın 'acil' sorunu, Güneş'in ölümü değil; o 5 milyar yılı nasıl kullanacağıdır.",
    ],
    facts: [
      "Güneş her saniye ~4 milyon ton kütlesini enerjiye çevirir: Dünya bu enerjinin yalnızca yarım milyarda birini alır.",
      "Parlaklık artışı ölçülebilir ve kaçınılmazdır: 1-1,5 milyar yıl sonra 'nemli sera' başlar ve okyanuslar buharlaşmaya başlar.",
      "Kırmızı dev Güneş, Dünya'nın gökyüzünde dev bir kızıl disk olur: görünür çapı bugünkünün ~200 katına çıkar.",
      "Helyum flaşı, dakikalar içinde parlaklığı bugünkü Güneş'in milyarlarca katına çıkarabilir — ama ısı çekirdekte kalır, dış katmanlar bunu 'hissetmez'.",
      "Beyaz cücenin yoğunluğu ~1 ton/cm³: bir çay kaşığı malzeme, bir filin ağırlığındadır.",
      "Beyaz cücelerin 'siyah cüce' olması ~10^15 yıl sürer: evren 13,8 milyar yaşında olduğundan henüz hiç siyah cüce yoktur.",
      "Güneş'in ömrü hâlâ ~%50'dir: 5 milyar yıl, insanlık tarihinin (300.000 yıl) ~16.000 katıdır — 'acil' bir sorun değildir.",
    ],
  },
  {
    id: "samanyolu-kollari",
    title: "Samanyolu'nun Kolları",
    subtitle: "Persey, Yay, Kalkan–Centaurus, Norma ve Orion Spuru: galaksimizin kanatlarının adları",
    category: "Galaksi",
    paragraphs: [
      "Samanyolu bir gül gibi düşünülebilir: merkezden açılan kollar onun yapraklarıdır. Ama kollar sabit madde yığınmaları değildir; yoğunluk dalgalarıdır. Galaksi diskinde ilerleyen bu dalga, önüne çıkan gaz bulutlarını sıkıştırır; sıkışan gaz yıldız doğumunu ateşler. Bu yüzden kollar pembe HII bölgeleriyle ve genç mavi yıldız kümeleriyle parlar — kollar, galaksinin yıldız fabrikalarıdır.",
      "Dört büyük kol sayılır: Kalkan–Centaurus (Scutum-Centaurus) ve Persey (Perseus) kolları, merkezi çubuğun iki ucundan doğan iki BÜYÜK koldur. Yay (Sagittarius) ve Norma (Norma) kolları ise daha zayıf, ikincil yapılardır. Bunların dışında sayısız küçük kol parçası (spur) ve sırım (spicule) vardır; bu kılcal yapılar diske damar damar işlenmiştir.",
      "İşte kritik nokta: Güneş hiçbir büyük kola ait değildir. Orion Spuru (Orion Spur) denen, Yay ve Persey kolları arasında sıkışmış yaklaşık 3.500 ış yılı uzunluğunda küçük bir kol parçasında doğdu ve hâlâ orada yaşıyoruz. Gökyüzünde kışın gördüğümüz Orion Takımyıldızı, bu spurun içindeki yıldız oluşum bölgesinin adını verir: Orion Bulutsusu, kendi kolumuzun en yakın yıldız doğum hastanesidir.",
      "Kolların adları nereden gelir? Astronomlar, gökyüzünde kolun arkasında kalan takımyıldızlara göre adlandırır: Persey kolu Persey takımyıldızı yönünde en yoğundur; Yay kolu, galaktik merkezin de bulunduğu Yay takımyıldızı yönünde uzanır. Radyo astronomisi (1950'ler, Oort, Kerr, Westerhout) kolların 21 cm hidrojen haritalarını çıkarınca bu adlar standartlaştı.",
      "Kollar, Güneş'in hareketini de belirler: Güneş saatte ~828.000 km hızla ilerlerken, yaklaşık her 100-150 milyon yılda bir bir sarmal kolun içinden geçer. Bazı bilim insanları, kol geçişlerinin Oort Bulutu'nu sarsıp Dünya'ya kometsel bombardıman başlattığını ve kitlesel yok oluşlarla korelasyonlu olabileceğini öne sürer. Bir sonraki büyük kol geçişi: Persey kolu ile — kozmik takvimde yakındır.",
    ],
    facts: [
      "Kollar fiziksel nesne değil, trafik sıkışıklığıdır: yıldızlar kollardan akıp geçer, kol deseni yerinde kalır.",
      "Kalkan–Centaurus kolu, galaksinin en eski ve en kalın koludur: merkezi çubuğun doğrudan uzantısı sayılır.",
      "Orion Spuru'na 'Yerel Kol' (Local Arm) da denir: çünkü bizim tüm uzay haritalarımız bu koldan yapılmıştır.",
      "Kolun içinden geçerken gökyüzü değişir: yıldız doğum bölgeleri, geceyi pembe-nebula ışığıyla aydınlatırdı.",
      "Radyo haritaları kolları karbon monoksit (CO) ve hidrojen çizgileriyle bulur: gaz, yıldızlardan daha iyi kol imzası verir.",
      "Bazı galaksilerde kollar tutulmaz (flocculent türü): Samanyolu ise 'grand design'a yakın, belirgin kollu bir disktir.",
      "Yay kolu yönü, gece göğünün en zengin yıldız alanıdır: o yönde bakınca galaksinin merkezine bakarsınız.",
    ],
  },
  {
    id: "buyuk-carpma",
    title: "Büyük Çarpma Hipotezi",
    subtitle: "Theia, Dünya'ya nasıl çarptı ve Ay bu kaostan nasıl doğdu?",
    category: "Ay",
    paragraphs: [
      "Ay'ın nereden geldiği, astronomi tarihinin en zorlu bulmacalarından biridir. Üç klasik teori vardı: Ay, Dünya'dan 'koptu' (fission), Dünya tarafından 'yakalandı' (capture) ya da Dünya ile aynı buluttan 'aynı anda oluştu' (co-accretion). Her biri bir şeye uyuyor, üçüne birden uymuyordu: Ay'ın demir çekirdeği Dünya'ya göre orantısız küçük; ama izotop kimyası Dünya'nınkiyle neredeyse birebir aynıydı.",
      "1975'te Hartmann ve Davis bir devrim önerdi: Mars büyüklüğünde bir protoplanet — Theia adı verildi — genç Dünya'ya eğik açıyla çarptı (~4,51 milyar yıl önce). Çarpma öyle şiddetliydi ki iki gövdenin dış katmanları eriyip karıştı; Theia'nın demir çekirdeği Dünya'nın içine gömülüp kaynaştı (iç içe geçiş), savrulan kızgın enkaz ise Dünya çevresinde bir moloz halkası kurdu. Bu halka, binlerce-10.000 yıl gibi kısa bir sürede toplanarak Ay'ı kurdu.",
      "Teoriyi Apollo taşları kurtardı: Ay örneklerindeki oksijen izotop oranları (¹⁶O/¹⁷O/¹⁸O) Dünya'yla tıpatıp aynıydı — 'yakalama' teorisi bunu açıklayamıyordu. Büyük çarpma, Dünya ve enkaz diskinin aynı sıcak, karışmış malzemeden kurulduğunu öngörüyordu. 2019'da Durham Üniversitesi'nin süperbilgisayar simülasyonları, çarpmanın yaklaşık 1 saat sürdüğünü ve Ay'ın tek parça halinde bile oluşabileceğini gösterdi.",
      "Çarpmanın izleri bugün hâlâ üzerindeimizde: çarpma öncesi Dünya günü ~6 saatti. Ay'ın gelgit sürtünmesi, milyarlarca yılda günü 24 saate uzattı ve hâlâ yılda ~3,8 cm uzaklaşıyor. Ay'ın Dünya'nın eksen eğikliğini (~23,4°) dengede tutması da bu çarpmanın dolaylı hediyesidir: Aysız bir Dünya'da iklim kutuplardan ekvatora milyonlarca yıllık dalgalar halinde savrulurdu.",
      "Theia hipotezi hâlâ gelişiyor: 'izotop ikizi' sorununu çözmek için Theia'nın Dünya ile benzer kimyasallı olması ya da çarpmanın çok daha enerjik olup iki gezegenin tamamen karışması (sinestia modeli, 2018) öneriliyor. Kesin olan şu: Ay, iki dünyanın çarpışmasından doğan bir phoenix'tir — ve her gece gökyüzünde bu eski kazanın kanıtına bakarız.",
    ],
    facts: [
      "Theia çarpması Dünya yüzeyini saniyeler içinde magma okyanusuna çevirdi: bugünkü kıtalar bu eriyiğin soğumasından doğdu.",
      "Ay'ın demir çekirdeği küçüktür: çünkü Ay, iki gezegenin demirce fakir DIŞ katmanlarından kuruldu.",
      "Apollo 11'in getirdiği 21,5 kg taş, üç klasik Ay teorisini çökertip büyük çarpmayı tahta çıkardı.",
      "Çarpma anındaki sıcaklık ~10.000 °C'yi aşmış olabilir: kaya, buhar halinde uzaya fışkırıyordu.",
      "Ay ilk doğduğunda gökyüzünde bugünkünden ~15 kat büyük görünüyordu: Dünya'ya ~25.000 km idi (bugün 384.400 km).",
      "Gün uzadıkça ay uzadı: Devon döneminde (~400 milyon yıl önce) gün 22 saatti; mercan halkaları bunu kayıtlı tutar.",
      "Theia adı, Yunan mitolojisinde Ay tanrıçası Selene'in annesinden gelir: bilimsel adlandırma şiirle buluştu.",
    ],
  },
  {
    id: "oort-bulutu",
    title: "Oort Bulutu: Güneş Sistemi'nin Gerçek Sınırı",
    subtitle: "2.000 AU'dan 100.000 AU'ya: ışığın yarım yılda geçtiği buz diyarı",
    category: "Bölge",
    paragraphs: [
      "Güneş Sistemi nerede biter? En uç gezegen Neptün'ün yörüngesi 30 AU'dur (1 AU = Güneş-Dünya uzaklığı). Kuiper kuşağı 50 AU'ya uzanır. Voyager 1, 165 AU'da yıldızlararası uzaya girdi bile. Ama Güneş'in kütleçekimi çok daha uzağa hükmeder: yaklaşık 100.000-200.000 AU'ya kadar. O devasa küresel bölge, Oort Bulutu'dur — sistemin gerçek, görünmez sınırı.",
      "1950'de Jan Oort, uzun dönemli kuyruklu yıldızların yörüngelerini inceledi: bunlar binlerce-yirmi binlerce yıllık periyotlarla her yönden geliyordu — düzlemsel bir kuşaktan değil, küresel bir kabuktan. Oort, Güneş'i bir buz kabuğuyla sarılı olarak öngördü: iç sınırı ~2.000 AU ('Hills bulutu'), dış sınırı ~100.000 AU. Oradaki ışık yılı şaşırtıcıdır: dış sınır, 1,5 ış yılı uzaktadır; güneş ışığı oraya 1 yıldan uzun sürede ulaşır.",
      "Oort, ölçek olarak zihni zorlar: Neptün'ün yörüngesi içine binlerce kez sığacak kadar geniştir. İçinde ~1 trilyon buz gövdesi olduğu tahmin edilir (toplam kütle yalnızca ~5 Dünya kütlesi). Sıcaklık -270 °C'ye yakındır; bu gövdeler 4,6 milyar yıldır Güneş'in doğduğu bulutun donmuş arşivleri gibi korunur. Hiçbir nesnesi doğrudan görülmedi — varlığı, kuyruklu yıldız istatistiklerinden çıkarılır.",
      "Oort'tan gelen bir gövde, yıldızlararası uzaydan geçen bir cisim kadar 'yabancı'dır değildir ama yolu kozmiktir: Hale-Bopp gibi uzun dönemli kuyruklu yıldızlar buradan düşer. Dış bölgedeki cisimler, komşu yıldızların geçişiyle ve galaktik gelgitlerle hafifçe sarsılır; sarsılan biri içeri düşer ve bizim gökyüzümüzde bir yıldız kuyruğu olur. Bazıları (ör. 'Oumuamua olabilir) yakalanmış yıldızlararası gövdelerdir.",
      "İnsanlık, Oort'a ulaşmaktan çok uzaktır: Voyager 1'in Oort'un iç sınırına varması ~300 yıl, bulutu geçip çıkması ~30.000 yıl sürecek. Oort, şimdilik yalnızca matematikte ve gökyüzümüzü süsleyen uzun kuyruklu misafirlerde yaşar: Güneş Sistemi'nin en uzak odası, en sıcak misafirleri bize oradan gönderir.",
    ],
    facts: [
      "Oort Bulutu'nun dış sınırına güneş ışığı 1 yıldan fazla yolda gider: oradaki 'gün', Dünya'nınkinin milyarda biri parlaklıktadır.",
      "Bulut, küreseldir: kuyruklu yıldızlar her yönden gelir — bu, düzlemsel Kuiper'den en büyük farkıdır.",
      "Sedna'nın 11.000 yıllık yörüngesi, Oort'un iç bölgesinden gelen ilk 'canlı mesaj' sayılır.",
      "Galaktik gelgitler: Samanyolu'nun genel çekimi, Oort'un dışını her zaman hafifçe 'karıştırır' — kuyruklu yıldız yağmurunun motoru.",
      "Güneş, galaktik düzlemin üstünden altına salınırken (~60-70 milyon yıllık periyot) Oort'u daha çok sarsabilir: yok oluş döngüsü tartışması buradan doğar.",
      "'Oumuamua (2017) ve Borisov (2019): ilk doğrulanmış yıldızlararası ziyaretçiler — belki başka yıldızların 'Oort'larından kaçan gövdeler.",
      "Oort'un toplam kütlesi ~5 Dünya kütlesidir: trilyonlarca gövde, toz kadar kozmik öneme sahiptir.",
    ],
  },
];
