import type { TheoryDef } from "../theories";
import { N, C } from "./helpers";

/**
 * Kozmoloji teorileri (1-8): Büyük Patlama'dan Simülasyon'a.
 * Her teori uzun, aşamalı ve ses efektli anlatım içerir.
 */
export const COSMOS_THEORIES: TheoryDef[] = [
  {
    id: "buyuk-patlama",
    cat: "kosmoloji",
    title: "Büyük Patlama Teorisi",
    subtitle:
      "Te Killik noktadan ilk ışığa, karanlık çağdan galaksilere — evrenin 13,8 milyar yıllık doğum filmi",
    duration: 125,
    color: "#ff5c39",
    stages: [
      { until: 0.1, title: "Tekillik", text: "Evrenin tüm maddesi ve enerjisi, sonsuz sıcaklık ve yoğunlukta tek bir noktada. Uzay ve zaman bu noktayla birlikte doğar — 'önce' diye bir an yoktur.", era: "0 saniye" },
      { until: 0.24, title: "Patlama ve Enflasyon", text: "10⁻³⁶ saniyede evren çığ gibi büyür; sıcaklık 10²⁷ °C'yi aşar. İlk saniyelerde yalnızca kuarklar, elektronlar ve ışık fotonları var.", era: "0 → 1 saniye" },
      { until: 0.38, title: "İlk Çekirdekler", text: "İlk üç dakikada protonlar ve nötronlar birleşir: hidrojen ve helyum çekirdekleri pişer. Evrenin yıldız hammaddesinin %98'i bu üç dakikada üretilir.", era: "3 dakika" },
      { until: 0.52, title: "İlk Işık Serbest", text: "380.000 yıl: evren 3.000 °C'ye soğur ve şeffaflaşır. Işık serbest kalır — bugün Kozmik Mikrodalga Arka Plan (CMB) olarak 2,7 Kelvin'de ölçülür.", era: "380.000 yıl" },
      { until: 0.68, title: "Karanlık Çağ ve İlk Yıldızlar", text: "Yüz milyonlarca yıl yıldız yoktur: karanlık çağ. Sonra soğuk hidrojen bulutları çöker ve ilk yıldızlar parlar — evren ikinci kez ışığa kavuşur.", era: "~200 milyon yıl" },
      { until: 0.84, title: "Galaksiler Kuruluyor", text: "Yerçekimi maddiyi toplayıp ilk galaksileri ve kümeleri kurar. Samanyolu ~13,6 milyar yaşındadır; evrenin en yaşlı üyelerindendir.", era: "~1 milyar yıl" },
      { until: 1, title: "Bugün ve Yarın", text: "13,8 milyar yıl sonra: gözlenebilir evrende ~2 trilyon galaksi. Genişleme son bulmak bir yana hızlanıyor — karanlık enerji kumandayı ele geçirdi.", era: "bugün" },
    ],
    notes: [
      N(0.03, 0.1, "sıcaklık: 10³² K", 0.5, 0.32),
      N(0.26, 0.34, "10⁻³⁶ sn: enflasyon", 0.24, 0.3),
      N(0.4, 0.48, "H %75 · He %25", 0.66, 0.24),
      N(0.54, 0.62, "CMB: 2,7 K", 0.5, 0.62),
      N(0.7, 0.78, "ilk yıldızlar devti", 0.28, 0.36),
      N(0.88, 0.96, "13,8 milyar yıl", 0.7, 0.7),
    ],
    cues: [
      C(0.001, "rumble", 0.7),
      C(0.1, "explosion", 1.4),
      C(0.24, "whoosh", 1),
      C(0.38, "shimmer", 0.8),
      C(0.52, "bell", 0.9),
      C(0.68, "starform", 1),
      C(0.84, "wind", 0.8),
      C(0.95, "chime", 0.7),
    ],
    ticker: [
      "Georges Lemaître 1927'de 'ilkel atom' fikrini öne sürdü; Einstein bile önce karşı çıktı.",
      "Edwin Hubble 1929'da galaksilerin bizden uzaklaştığını gösterdi: evren genişliyor.",
      "CMB, 1965'te Penzias ve Wilson tarafından tesadüfen keşfedildi; 1978 Nobel ödülünü getirdi.",
      "Büyük Patlama bir 'patlama' değildir: uzayın kendisinin her yerde aynı anda büyümesidir.",
      "Baryon asimetrisi: her 1 milyar antimaddeye 1 milyar 1 madde denk geldi — biz o artığız.",
      "Planck uydusu 2013'te CMB haritasını milyonda derece hassasiyetle çıkardı.",
      "Evrenin %95'i görünmez: %27 karanlık madde, %68 karanlık enerji.",
      "İlk yıldızlar Güneş'ten yüzlerce kat büyük ve kısa ömürlüydü.",
      "Gözlenebilir evrenin yarıçapı 46,5 milyar ışık yılı — ışıktan hızlı değil, uzay büyüdü.",
    ],
  },
  {
    id: "kozmik-enflasyon",
    cat: "kosmoloji",
    title: "Kozmik Enflasyon Teorisi",
    subtitle:
      "Alan Guth'un 1981 fikri: bir saniyenin milyarda milyarda birinde evren 10²⁶ kat şişti",
    duration: 110,
    color: "#ffd166",
    stages: [
      { until: 0.16, title: "Kuantum Köpüğü", text: "Doğmamış evren, kuantum dalgalanmalarının kaynadığı minik bir köpük. Belirsizlik ilkesi, boşlukta bile enerji titreşimleri yaratır.", era: "10⁻³⁶ saniye" },
      { until: 0.34, title: "Şişme Başlar", text: "Enflasyon alanı kararsız hale gelir: uzay katlanarak büyür. Bir turunçgil çekirdeği büyüklüğündeki bölge, gözlenebilir evren boyutuna şişer.", era: "10⁻³⁵ saniye" },
      { until: 0.5, title: "Kuantum Tohumları", text: "Şişme sırasında kuantum dalgalanmaları makroskopa ölçeklenir: küçücük yoğunluk farkları büyüyerek galaksi tohumlarına dönüşür.", era: "şişme sırasında" },
      { until: 0.64, title: "Düzleşen Evren", text: "Şişme, uzayı bir balon gibi düzleştirir: kritik yoğunluğa çok yakın geometri. Bugün ölçtüğümüz 'düz evren', bu sürecin imzasıdır.", era: "sonra" },
      { until: 0.8, title: "Yeniden Isınma", text: "Enflasyon alanı bozunur: depoladığı enerji parçacıklara akar — evren sıcak bir parçacık çorbasına dönüşür. Büyük Patlama'nın asıl ateşleme anı budur.", era: "reheating" },
      { until: 1, title: "Öngörüler ve Kanıtlar", text: "Enflasyon, CMB'deki dalgalanma desenini, düzlüğü ve manyetik tek kutup yokluğunu birden açıklar. 1992 COBE, 2013 Planck verileri modeli güçlendirdi.", era: "bugün" },
    ],
    notes: [
      N(0.06, 0.14, "kuantum köpüğü", 0.5, 0.3),
      N(0.36, 0.44, "10²⁶ kat büyüme", 0.3, 0.26),
      N(0.54, 0.62, "galaksi tohumları", 0.68, 0.32),
      N(0.68, 0.76, "düz geometri", 0.5, 0.66),
      N(0.84, 0.92, "Guth, 1981", 0.28, 0.3),
    ],
    cues: [
      C(0.001, "hiss", 0.6),
      C(0.16, "whoosh", 1.1),
      C(0.34, "shimmer", 0.9),
      C(0.5, "wind", 0.7),
      C(0.64, "bell", 0.7),
      C(0.8, "explosion", 0.8),
      C(0.94, "chime", 0.7),
    ],
    ticker: [
      "Alan Guth 1981'de enflasyonu önerdi: 'nihai bedava öğle yemeği' dedi.",
      "Andrei Linde'nin kaotik enflasyon modeli (1983) bugün en kabul gören sürümlerden.",
      "Şişme, evrenin yaşını 10⁻³⁵ saniyede 10²⁶ kat büyüttü — ışıktan hızlı değil, uzay kendisi genişledi.",
      "Enflasyon, görülemeyecek kadar küçük kuantum dalgacıklarını galaksi tohumuna çevirir.",
      "CMB'nin sıcaklık haritası, enflasyon öngörüsüyle birebir uyumlu bir ölçek dağılımı gösterir.",
      "BICEP2'nin 2014 iddiası toz kirliliği çıktı: birincil kütleçekim dalgaları hâlâ aranıyor.",
      "Düz evren ölçümü (Ω=1,0007±0,0019) enflasyonun en güçlü kanıtlarından.",
      "Manyetik tek kutupların yokluğu da enflasyonla açıklanır: seyreltilip gittiler.",
    ],
  },
  {
    id: "lambda-cdm",
    cat: "kosmoloji",
    title: "Standart Kozmolojik Model (Λ-CDM)",
    subtitle:
      "%5 atom, %27 karanlık madde, %68 karanlık enerji — evrenin resmi kimlik kartı",
    duration: 115,
    color: "#c084fc",
    stages: [
      { until: 0.15, title: "Karanlık Madde İskeleti", text: "Evrenin görünmez omurgası: karanlık madde, yerçekimiyle kozmik ağ kurar. Filamentler galaksilerin doğacağı düğümleri önceden işaretler.", era: "ilk milyarlar" },
      { until: 0.3, title: "Gaz Filamentlere Akar", text: "Sıradan madde, karanlık madde kuyularına akar: gaz filamentler boyunca kayarak düğümlerde yoğunlaşır ve ısınır.", era: "~1 milyar yıl" },
      { until: 0.46, title: "Düğümlerde Galaksiler", text: "Filament düğümlerinde gaz çöker, yıldızlar tutuşur: galaksiler kozmik ağın boncukları gibi dizilir. Millennium simülasyonu bu ağı modelledi.", era: "~2 milyar yıl" },
      { until: 0.62, title: "1998: Hızlanan Genişleme", text: "Uzak süpernovalar beklenenden sönük: genişleme YAVAŞLAMAMIŞ, hızlanmış. Saul Perlmutter, Brian Schmidt ve Adam Riess bu keşifle 2011 Nobel aldı.", era: "1998" },
      { until: 0.78, title: "Λ: Karanlık Enerji", text: "Einstein'ın 'en büyük hatası' dediği kozmolojik sabit geri döndü: Λ, uzayın kendi gerilim enerjisi olarak genişlemeyi hızlandırır.", era: "bugün" },
      { until: 1, title: "Modelin Dengesi", text: "Λ-CDM altı parametreyle binlerce gözlemi aynı anda açıklar. Ama karanlık maddenin doğası ve karanlık enerjinin kaynağı hâlâ sır.", era: "açık sorular" },
    ],
    notes: [
      N(0.05, 0.13, "karanlık madde: %27", 0.28, 0.28),
      N(0.32, 0.4, "gaz akışı", 0.62, 0.3),
      N(0.5, 0.58, "hızlanan genişleme", 0.5, 0.64),
      N(0.66, 0.74, "Λ: Einstein'ın sabiti", 0.24, 0.34),
      N(0.84, 0.92, "biz: %5'teyiz", 0.68, 0.66),
    ],
    cues: [
      C(0.001, "wind", 0.6),
      C(0.15, "whoosh", 0.8),
      C(0.3, "shimmer", 0.7),
      C(0.46, "starform", 0.9),
      C(0.62, "warp", 1),
      C(0.78, "rumble", 0.7),
      C(0.92, "bell", 0.7),
    ],
    ticker: [
      "Λ-CDM'de Λ kozmolojik sabiti, CDM ise 'soğuk karanlık madde' demektir.",
      "Karanlık madde ışıkla etkileşmez; yalnızca kütleçekimiyle kendini ele verir.",
      "1933'te Fritz Zwicky Coma kümesinde 'kayıp kütle' fark etti: ilk ipucu.",
      "Vera Rubin 1970'lerde galaksi dönme eğrilerini ölçtü: kenarlar çok hızlı dönüyordu.",
      "1998 süpernova keşfi 'Yüzyılın Bilim Buluşu' seçildi; Nobel 2011'de verildi.",
      "Millennium simülasyonu 10 milyar parçacıkla kozmik ağı ekrana taşıdı.",
      "Planck 2018 verileri: H₀ = 67,4 km/sn/Mpc — ama yerel ölçüm ~73: 'Hubble gerilimi'.",
      "Karanlık enerji, her metreküpte ~10⁻⁹ jüllük homojen bir enerji gibi davranıyor.",
    ],
  },
  {
    id: "coklu-evren",
    cat: "kosmoloji",
    title: "Çoklu Evren Teorisi",
    subtitle:
      "Kabarcıklar denizinde bizim evren: sonsuz şişmenin doğal sonucu mu, test edilemez fantezi mi?",
    duration: 120,
    color: "#f472b6",
    stages: [
      { until: 0.15, title: "Sonsuz Şişme Köpüğü", text: "Enflasyon hiç durmayabilir: alan çoğu yerde şişmeyi sürdürür. Şişmenin durduğu baloncuklar 'evrenler' olur — sürekli doğan bir köpük.", era: "sonsuz şişme" },
      { until: 0.32, title: "Kabarcık Doğumu", text: "Bir bölge salınımının düşmesiyle şişmeyi bırakır: yeni bir evren kabarcığı doğar. Kabarcık, dıştaki ışıktan hızlı büyür — içerisi bizden kesilir.", era: "anlık doğum" },
      { until: 0.48, title: "Her Kabarcık Kendi Yasasıyla", text: "Sicim teorisinin 10⁵⁰⁰ olası vakumu: her kabarcıkta farklı fizik sabitleri. Kiminde atom yok, kiminde yalnızca karanlık enerji.", era: "manzara" },
      { until: 0.64, title: "Bizim Kabarcık", text: "Bizim kabarcığımızda sabitler tam izin verir: yıldızlar, kimya, gezegenler. 'İnce ayar' tartışmasının çoklu evren cevabı budur: şanslı kabarcığız.", era: "bizim adres" },
      { until: 0.8, title: "Çarpışma İzleri Aranıyor", text: "Komşu bir kabarcık değdiyse, CMB'de soğuk bir daire iz bırakır. Araştırmalar sürüyor: şimdiye kadar istatistiksel olarak anlamlı bir iz yok.", era: "test edilebilir mi?" },
      { until: 1, title: "Bilim mi, Felsefe mi?", text: "Eleştirmenler 'gözlemlenemez' diyor; savunucular 'dolaylı öngörüleri var' cevabını veriyor. Çoklu evren, modern kozmolojinin en ateşli sınır tartışması.", era: "tartışma" },
    ],
    notes: [
      N(0.05, 0.13, "sonsuz şişme", 0.5, 0.28),
      N(0.34, 0.42, "yeni kabarcık!", 0.26, 0.32),
      N(0.52, 0.6, "10⁵⁰⁰ olası vakum", 0.66, 0.3),
      N(0.68, 0.76, "CMB'de iz arama", 0.3, 0.66),
      N(0.86, 0.94, "test edilebilirlik", 0.62, 0.68),
    ],
    cues: [
      C(0.001, "hiss", 0.6),
      C(0.15, "whoosh", 0.8),
      C(0.32, "pop", 0.9),
      C(0.48, "shimmer", 0.8),
      C(0.64, "bell", 0.8),
      C(0.8, "wind", 0.7),
      C(0.94, "glitch", 0.5),
    ],
    ticker: [
      "Sonsuz şişme fikri Alexander Vilenkin ve Andrei Linde tarafından geliştirildi.",
      "Sicim manzarası (landscape): 10⁵⁰⁰ farklı vakum çözümü, 10⁵⁰⁰ farklı evren olasılığı.",
      "Kabarcık evrenler birbirine asla ulaşamaz: aradaki şişen uzay ışıktan hızlı açılır.",
      "İnce ayar: güçlü nükleer kuvvet %1 değişse karbon doğmaz — antropik tartışmanın özü.",
      "2010'da CMB'de 'kabarcık çarpışma izi' iddiası ortaya çıktı; analiz 4-5 sigma bulamadı.",
      "Max Tegmark'a göre 4 düzeyli çoklu evren sınıflaması var: bölgesel, kabarcık, kuantum, matematik.",
      "Eleştiri başkanı Paul Steinhardt: enflasyon bile 'hile' — çoklu evren onun doğal sonucu.",
      "Gözlem seçim etkisi (anthropik): soruyu soran varlık, ancak uygun evrende sorabilir.",
    ],
  },
  {
    id: "dongusel-evren",
    cat: "kosmoloji",
    title: "Döngüsel (Salınımlı) Evren Teorisi",
    subtitle:
      "Patlama, genişleme, çöküş, yeniden doğuş — başlangıcı olmayan sonsuz bir solunum",
    duration: 125,
    color: "#fb923c",
    stages: [
      { until: 0.14, title: "Big Bang: Nefes Alış", text: "Döngü, bir patlamayla açılır: sıcak, yoğun, genç bir evren. Önceki döngünün kalıntıları üzerinde yeniden kurulur.", era: "döngü başlangıcı" },
      { until: 0.3, title: "Genişleme", text: "Maddeler uzaklaşır, yıldızlar doğar ve söner: evren genişlerken soğur. Karanlık enerji yavaşça sahneyi devralır.", era: "genişleme evresi" },
      { until: 0.46, title: "Boşalan Evren", text: "Trilyon yıllar sonra: yıldızlar sönmüş, karadelikler buharlaşmış, neredeyse boş ve soğuk bir uzay kalır.", era: "trilyon yıllar" },
      { until: 0.62, title: "Büzülme: Nefes Veriş", text: "Bazı modellerde genişleme tersine döner: madde merkeze akar, ısı yükselir, mavi kayma her yeri morarır.", era: "kontraksiyon" },
      { until: 0.76, title: "Büyük Çöküş", text: "Her şey tek noktada sıkışır — ama kuantum etkiler tekilliği engelleyebilir: yay gibi sıkışan uzay, geri tepmeye hazırlanır.", era: "Big Crunch" },
      { until: 0.9, title: "Big Bounce: Yeni Patlama", text: "Sıkışma sınırda tersine döner: 'sıçrama' yeni bir patlamayı ateşler. Penrose'un CCC modeli bunu uyarlanabilir geometriyle açıklar.", era: "Big Bounce" },
      { until: 1, title: "Sorunlar ve İpuçları", text: "Entropi döngüden döngüye birikir (Tolman sorunu). Penrose, CMB'de önceki döngünün 'Hawking noktalarını' arıyor.", era: "açık sorular" },
    ],
    notes: [
      N(0.05, 0.12, "döngü no: sonsuz", 0.3, 0.28),
      N(0.32, 0.4, "yıldızlar doğuyor", 0.66, 0.28),
      N(0.5, 0.58, "trilyon yıl sonra", 0.3, 0.62),
      N(0.64, 0.72, "mavi kayma", 0.66, 0.6),
      N(0.8, 0.88, "Bounce!", 0.5, 0.3),
      N(0.92, 0.99, "Penrose: CCC", 0.5, 0.7),
    ],
    cues: [
      C(0.001, "explosion", 1.2),
      C(0.14, "whoosh", 0.8),
      C(0.3, "starform", 0.9),
      C(0.46, "wind", 0.8),
      C(0.62, "warp", 0.9),
      C(0.76, "rumble", 1),
      C(0.9, "explosion", 1.2),
      C(0.97, "chime", 0.7),
    ],
    ticker: [
      "Richard Tolman 1930'larda döngüsel modellerin entropi sorununu gösterdi.",
      "Friedmann'ın 1922 çözümleri kapalı evrenin çöküşünü de öngörürdü.",
      "Steinhardt-Turok ekpirotik modeli döngüyü brana çarpışmasıyla bağlar.",
      "Roger Penrose'un CCC'si (2010): sonsuz genişleme yeni bir Big Bang'a eşdeğerdir.",
      "Penrose, CMB halkalarında önceki döngünün karadelik buharlaşma izlerini aradı.",
      "Big Bounce modellerinde tekillik oluşmaz: kuantum baskı çöküşü iter.",
      "LQC (Döngüsel Kuantum Kütleçekimi) bu sıçramayı matematiğiyle destekler.",
      "Karanlık enerji keşfi basit döngüleri zorlaştırdı: genişleme hızlanıyor çünkü.",
      "Buddhist ve Hindu kozmolojileri de döngüsel evren tasvir eder — binlerce yıllık fikir.",
    ],
  },
  {
    id: "steady-state",
    cat: "kosmoloji",
    title: "Sabit Durum Teorisi",
    subtitle:
      "Hoyle'un meydan okuması: genişleyen evrende yoğunluk hep aynı — çünkü madde sürekli üretiliyor",
    duration: 105,
    color: "#34d399",
    stages: [
      { until: 0.16, title: "1948: Üç İsim", text: "Fred Hoyle, Hermann Bondi ve Thomas Gold sabit durum modelini önerdi: 'Mükemmel Kozmolojik İlke' — evren her yerde ve her zaman aynı görünür.", era: "1948" },
      { until: 0.32, title: "Madde Sürekli Doğar", text: "Genişleme seyrekleşmeyi önlemek için boşlukta yeni madde doğar: saniyede metreküpte ~10⁻⁴⁰ proton. Görünürde hiçbir şey değişmez.", era: "model öngörüsü" },
      { until: 0.48, title: "Genç ve Yaşlı Yan Yana", text: "Her çağda hem genç hem yaşlı galaksiler var: hiçbir 'ilkbahar' dönemi yoktur. Radyo galaksi sayımları bunu sorgulamaya başladı.", era: "öngörü" },
      { until: 0.64, title: "Karanlığa Karşı", text: "1965: CMB keşfi — her yöne eş dağılımlı 2,7 K ışıma. Sabit durum modeli bu 'evrenin bebek fotoğrafını' açıklayamadı: büyük darbe.", era: "1965" },
      { until: 0.8, title: "Hoyle'un Direnişi", text: "Hoyle sonuna kadar savundu; 'Büyük Patlama' adını bile BBC radyosunda alaycı biçimde o uydurdu. Ama veriler aleyhine döndü.", era: "1960'lar" },
      { until: 1, title: "Mirası", text: "Kaybeden model bile kozmolojiye kazandırdı: nükleosentez terimini Hoyle yazdı, karbonun üçlü-alfa sürecini o hesapladı.", era: "miras" },
    ],
    notes: [
      N(0.05, 0.13, "Mükemmel İlke", 0.3, 0.28),
      N(0.34, 0.42, "10⁻⁴⁰ proton/m³·sn", 0.66, 0.3),
      N(0.52, 0.6, "genç+yaşlı karışık", 0.28, 0.62),
      N(0.66, 0.74, "CMB: 2,7 K", 0.62, 0.6),
      N(0.86, 0.94, "'Big Bang' adı: Hoyle", 0.5, 0.3),
    ],
    cues: [
      C(0.001, "wind", 0.6),
      C(0.16, "shimmer", 0.7),
      C(0.32, "grow", 0.7),
      C(0.48, "whoosh", 0.7),
      C(0.64, "bell", 0.9),
      C(0.8, "rumble", 0.6),
      C(0.94, "chime", 0.7),
    ],
    ticker: [
      "Sabit durum, 1948'de BBC radyo programında Bondi'nin filmini izleyen üç fizikçinin sohbetinden doğdu.",
      "Fred Hoyle 'Büyük Patlama' ifadesini 1949 yayınında alaycı biçimde kullandı; ad yapıştı.",
      "Sabit durumda yeni madde sürekli doğar ama yoğunluk sabittir: 'yaratım alanı' hipotezi.",
      "Quasar sayımları 1960'larda geçmişin farklı olduğunu gösterdi: Mükemmel İlke çürüdü.",
      "CMB keşfi Nobel'i Penzias-Wilson'a getirdi; sabit durumun en büyük ölüm sebebi sayılır.",
      "Hoyle, karbonun yıldızlarda nasıl üretildiğini (üçlü-alfa) çözdü: 10⁷ enerji düzeyi tahmini.",
      "'Nükleosentez' kelimesini de Hoyle tüttürdü; bilim dili ona borçlu.",
      "Alternatif 'quasi-steady state' 1993'te denendi ama veriler Lambda-CDM'i destekledi.",
    ],
  },
  {
    id: "ekpirotik",
    cat: "kosmoloji",
    title: "Ekpirotik Evren Teorisi",
    subtitle:
      "İki boyutlar-arası düzlemin çarpışması: ateşten doğan evren — Big Bang'a alternatif bir açılış",
    duration: 115,
    color: "#f87171",
    stages: [
      { until: 0.15, title: "İki Brana", text: "M-teorisinin 11 boyutlu sahnesinde evrenimiz, uzay-zamanın bir 'brana' (membran) yüzeyi. Yakında, paralel bir brana daha durur.", era: "kurulum" },
      { until: 0.3, title: "Yaklaşma", text: "İki düzlem boyutlar-arası mesafede yavaşça yaklaşır: milyarlarca yıllık bir kapanış. Aradaki uzay gergin, titreşen bir gerilim alanı.", era: "yaklaşma evresi" },
      { until: 0.46, title: "Çarpışma", text: "Brana'lar çarpışır: temas hattında muazzam enerji serbest kalır. Bu 'ateş' (ekpirosis Yunancada yangın demektir) yeni bir sıcak evren doğurur.", era: "anlık çarpışma" },
      { until: 0.62, title: "Sıcak Doğum", text: "Çarpışma enerjisi parçacıklara dönüşür: sıcak, yoğun, genişleyen bir evren başlar. İçimizdeki her atom bu çarpmış enerjinin kalıntısı.", era: "yeni evren" },
      { until: 0.78, title: "Bizim Brana Soğur", text: "Düzlem, genişleyip soğur; galaksiler ve yıldızlar kurulur. Trilyon yıllar sonra düzlemler yeniden yaklaşacak: döngü sürer.", era: "bugün" },
      { until: 1, title: "Ayırt Edici Öngörü", text: "Ekpirotik modelde ilksel kütleçekim dalgaları zayıftır: CMB'de B-mode sinyali neredeyse yoktur. Bu, onu enflasyondan ayıran testtir.", era: "test" },
    ],
    notes: [
      N(0.05, 0.13, "M-teorisi: 11 boyut", 0.3, 0.3),
      N(0.34, 0.42, "boyutlar-arası mesafe", 0.66, 0.28),
      N(0.5, 0.58, "ekpirosis = yangın", 0.28, 0.62),
      N(0.66, 0.74, "biz: enerji kalıntısı", 0.62, 0.64),
      N(0.84, 0.92, "B-mode: zayıf öngörü", 0.5, 0.3),
    ],
    cues: [
      C(0.001, "hiss", 0.6),
      C(0.15, "whoosh", 0.8),
      C(0.3, "rumble", 0.9),
      C(0.46, "crash", 1.4),
      C(0.5, "explosion", 1.1),
      C(0.62, "starform", 0.9),
      C(0.78, "wind", 0.7),
      C(0.94, "warp", 0.7),
    ],
    ticker: [
      "Ekpirotik model 2001'de Paul Steinhardt ve Neil Turok tarafından önerildi.",
      "Adı Herakleitos'un ateş kozmolojisinden gelir: 'ekpirosis' yangın demektir.",
      "Model, M-teorisinin brana (membran) kavramına dayanır: evrenimiz 4D bir yüzeydir.",
      "Big Bang bir başlangıç değil, iki düzlemin en yakın yaklaşımıdır.",
      "Hawking bile brana çarpışmalarını resmi bir makaleyle inceledi (Turok ile 2004 tartışması).",
      "Ekpirotik evren, CMB'de düşük B-mode polarizasyonu öngörür — JWST sonrası deneyler kritik.",
      "Steinhardt daha sonra enflasyonu eleştirdi: kendi ekpirotik döngüsünü savundu.",
      "WMAP ve Planck verileri henüz iki modeli ayırt edebilecek hassasiyette değil.",
    ],
  },
  {
    id: "simulasyon-teorisi",
    cat: "kosmoloji",
    title: "Simülasyon Teorisi (Matrix Hipotezi)",
    subtitle:
      "Nick Bostrom'un 2003 üçlemesi: gerçeklik bir bilgisayar simülasyonu olabilir mi?",
    duration: 130,
    color: "#4ade80",
    stages: [
      { until: 0.13, title: "Fiziksel Gerçeklik", text: "Başlangıçta her şey tanıdık: yıldızlar, galaksiler, maddeler. Fizik yasaları pürüzsüz ve evrensel görünür.", era: "varsayılan dünya" },
      { until: 0.28, title: "Piksel Sınırı", text: "Ama Planck ölçeğine inince uzay pürüzsüz değil: 10⁻³⁵ metrelik karecıklar. 'Ekran çözünürlüğü' gibi bir alt sınır var mı?", era: "10⁻³⁵ m" },
      { until: 0.44, title: "Kod Yağmuru", text: "Fizik yasaları matematiksel olarak 'yazılmış': sabitler rastgele değil, kodlanmış değerler. Evren, hesaplama ile ayırt edilemez bir düzen gösterir.", era: "yazılım varsayımı" },
      { until: 0.6, title: "Bostrom'un Üçlemesi", text: "Felsefeci Nick Bostrom (2003): aşağıdakilerden BİRİ doğrudur — (1) uygarlıklar yok olur, (2) ileri uygarlıklar simülasyon yapmaz, (3) biz simülasyon içindeyiz.", era: "2003" },
      { until: 0.76, title: "Gözlemci Sorunu", text: "Kuantum mekanikte gözlem, sonuçları etkiler: 'render edilmemiş' bölgeler gerçekten işlenmiyor olabilir. Bilgi sınırları, hesaplama bütçesini düşündürür.", era: "delil tartışması" },
      { until: 0.9, title: "Glitch Avı", text: "Kozmik ışınların en yüksek enerjilerinde bir 'sınır' öngörüsü var: Greisen-Zatsepin-Kuzmin kesimi. Bazıları bunu 'grid hatası' gibi yorumladı — kanıt değil.", era: "sözde kanıtlar" },
      { until: 1, title: "Test Edilebilir mi?", text: "Bilimsel duruş: simülasyon hipotezi bugün doğrulanabilir/yanlışlanabilir değil — bir felsefe problemi. Ama teknoloji sınırı her gün ilerliyor.", era: "sonuç" },
    ],
    notes: [
      N(0.05, 0.12, "gerçek mi, kod mu?", 0.5, 0.28),
      N(0.3, 0.38, "Planck karecıkları", 0.26, 0.32),
      N(0.46, 0.54, "Bostrom, 2003", 0.66, 0.3),
      N(0.64, 0.72, "gözlemci etkisi", 0.3, 0.64),
      N(0.8, 0.88, "GZK sınırı", 0.62, 0.66),
      N(0.93, 0.99, "test edilemez (şimdilik)", 0.5, 0.3),
    ],
    cues: [
      C(0.001, "wind", 0.6),
      C(0.13, "glitch", 0.6),
      C(0.28, "glitch", 0.8),
      C(0.44, "zap", 0.7),
      C(0.6, "shimmer", 0.7),
      C(0.76, "glitch", 0.9),
      C(0.9, "bell", 0.7),
      C(0.97, "whoosh", 0.6),
    ],
    ticker: [
      "Nick Bostrom'un makalesi 'Are You Living in a Computer Simulation?' 2003'te yayımlandı.",
      "Elon Musk'ın 'gerçeklik olasılığı milyonda bir' sözü bu üçlemeye dayanır.",
      "Planck uzunluğu 1,6×10⁻³⁵ metre: 'piksel' benzeri doğal alt sınır.",
      "Konway'ın Hayat Oyunu, birkaç kuraldan karmaşık 'evrenler' doğruduğunu gösterir.",
      "GZK kesimi (5×10¹⁹ eV üstü) kozmik ışınlarda gözlenen bir enerji tavanıdır.",
      "Kuantum sanallaştırma fikri: gözlemcilik, simülasyonun 'render' tetikleyicisi olabilir.",
      "Fizik kurallarının matematiksel olması Wigner'i şaşırttı: 'matematiğin acımasız etkililiği'.",
      "Eleştiri: simülasyon hipotezi yanlışlanamaz — bu yüzden bilim değil metafiziktir.",
      "Matrix (1999) filmi bu düşünce deneyini popüler kültüre taşıdı.",
    ],
  },
];
