import type { TheoryDef } from "../theories";
import { C, N } from "./helpers";

/**
 * Kategori teorileri: earth — yıldız fiziği + jeoloji paketi (8 teori).
 *
 * 1. yildiz-nukleosentezi   — dev yıldız içinde soğan katmanlı füzyon ve süpernova
 * 2. r-sureci               — nötron yıldızı birleşmesi ve hızlı nötron yakalama
 * 3. diferansiyasyon        — eriyik gezegende çekirdek/manto/kabuk ayrışması
 * 4. agir-bombardiman       — dev gezegen göçü ve 4,1-3,8 milyar yıl önceki saldırı
 * 5. hidrotermal-damar      — sıcak çözeltilerin çatlaklara altın damarı yazması
 * 6. magmatik-ayrisma       — Bowen serisi, granit ve pegmatit kristalleri
 * 7. sedimantasyon          — dağdan deltaya tortu, fosil ve taşlaşma
 * 8. biyojenik-cevherlesme  — siyanobakteri oksijeni ve şeritli demir oluşumu
 *
 * Not: metinlerdeki tüm sayılar gerçek bilimsel değerlerdir (udurma yok).
 */
export const EARTH_THEORIES: TheoryDef[] = [
  /* 1 ------------------------------------------------------------------ */
  {
    id: "yildiz-nukleosentezi",
    title: "Yıldız Nükleosentezi Teorisi",
    subtitle: "Dev yıldızların çekirdeklerinde ağır elementlerin nasıl üretildiğinin hikâyesi",
    duration: 120,
    color: "#fb7185",
    cat: "gokyuzu",
    stages: [
      {
        until: 0.13,
        title: "Dev Ana Kol Yıldızı",
        text: "8-10 Güneş kütleli O/B sınıfı yıldızlar, hidrojeni çekirdeklerinde füzyonla yakar. Çekirdek 30-40 milyon °C'de çalışır ve ömürleri Güneş'in binde biri kadardır: 10-20 milyon yıl. Bu yıldızlar, evrenin ilk ağır element fabrikalarıdır.",
        era: "Evren: ilk milyar yıllar",
      },
      {
        until: 0.26,
        title: "Soğan Katmanları",
        text: "Çekirdekte füzyon aşamaları birbiri ardına başlar: hidrojen, helyum, karbon, oksijen, silisyum. Her katman bir öncekinin küllerini yakıt olarak kullanır. Yıldız, içi içe geçmiş füzyon kabuklarından bir soğana benzer.",
        era: "Yıldızın son milyon yılı",
      },
      {
        until: 0.39,
        title: "Füzyon Zinciri",
        text: "Helyum yakan kabuk 100 milyon °C'de, karbon yakan 600 milyon °C'nin üzerindedir. Silisyum füzyonu yalnızca bir hafta sürer ve ürünü demirdir. Demir-56, nucleon başına en kararlı çekirdektir: artık yakıt yoktur.",
        era: "Son yüzyıllar",
      },
      {
        until: 0.52,
        title: "Demir Aşıldı",
        text: "Demir füzyonu enerji üretmez, tersine enerji yutar. Çekirdek basıncı düşer, ışınım kaybı hızlanır ve dengesizlik saniyeler içinde büyür. Yıldızın kalbi ilk kez nefesini tutar.",
        era: "Son saatler",
      },
      {
        until: 0.65,
        title: "İçe Çöküş",
        text: "Dünya büyüklüğündeki çekirdek, saniyenin onda biri gibi bir anda 50 km çapa kadar çöker. Madde çekirdeğe ses hızını aşarak düşer ve geri tepen şok dalgası doğar. Çekirdek, nükleer yoğunluğa ulaşır.",
        era: "Son milisaniyeler",
      },
      {
        until: 0.84,
        title: "Süpernova",
        text: "Şok dalgası ve nötrino fırtınası yıldızı saniyede 10.000 km hızla dışa savurur. Parlaklık birkaç hafta boyunca tüm bir galaksiyi geçebilir. Saçılan materyal: karbon, silikon, altın ve uranyum.",
        era: "Anlık patlama",
      },
      {
        until: 1,
        title: "Elementler Uzaya",
        text: "Saçılan ağır elementler moleküler bulutlara karışarak yeni yıldız ve gezegenleri besler. Güneş Sistemi de öyle doğdu: Dünya'daki her demir atomu eski bir süpernovanın mirasıdır. Yıldız ölür, elementler kalır.",
        era: "Sonraki yıldız nesilleri",
      },
    ],
    notes: [
      N(0.02, 0.11, "8-10 M☉: kısa ömürlü dev", 0.5, 0.12),
      N(0.14, 0.25, "katmanlar: H→He→C→O→Si→Fe", 0.68, 0.2),
      N(0.28, 0.37, "demir füzyonda enerji üretmez", 0.3, 0.3),
      N(0.42, 0.51, "çekirdek: ~3 milyar °C", 0.7, 0.35),
      N(0.55, 0.63, "çöküş: 0,1 saniyeden kısa", 0.35, 0.62),
      N(0.68, 0.82, "şok hızı: 10.000 km/sn", 0.7, 0.25),
      N(0.87, 0.98, "her demir atomu bir yıldız mirası", 0.5, 0.85),
    ],
    cues: [
      C(0.005, "starform", 0.7),
      C(0.05, "rumble", 0.4),
      C(0.14, "shimmer", 0.5),
      C(0.28, "shimmer", 0.6),
      C(0.4, "whoosh", 0.5),
      C(0.53, "rumble", 0.8),
      C(0.59, "rumble", 0.9),
      C(0.65, "crack", 0.8),
      C(0.7, "supernova", 1),
      C(0.75, "boom", 0.9),
      C(0.86, "shimmer", 0.7),
      C(0.93, "shimmer", 0.6),
      C(0.98, "starform", 0.6),
    ],
    ticker: [
      "Bir O devi, Güneş'in on bin katı ışık üretir ama ömrü yalnızca 10-20 milyon yıldır.",
      "Soğanın katmanları: H, He, C, Ne, O, Si ve sonunda demir; her katman bir füzyon fazıdır.",
      "Demir-56, nucleon başına en düşük enerjiye sahip çekirdektir: füzyonun bitiş çizgisi.",
      "Çekirdek çöküşü 0,1 saniyeden kısa sürer; salınan nötrino enerjisi yıldızın toplamından büyüktür.",
      "Supernova 1987A, 168.000 ışık yılı uzaktan patladı; nötrinoları Dünya'daki tuz suyu tanklarını salladı.",
      "Altın, gümüş ve iyot gibi elementlerin ana kaynağı yıldız ölümüdür; Dünya'nın çekirdeği demirini oradan aldı.",
      "Kalsiyum ve titan gibi bazı elementler yalnızca süpernova şok dalgalarında sentezlenebilir.",
      "Güneş Sistemi, bir süpernovanın saçtığı ağır elementlerle zenginleşmiş moleküler buluttan doğdu.",
      "Bugün gökte gördüğün her kızıl süperdev, gelecekte bir element kaynağıdır.",
      "SN 1987A'dan beklenen nötron yıldızı aranıyor: merkezde tozun ardında gizli olabilir.",
    ],
  },

  /* 2 ------------------------------------------------------------------ */
  {
    id: "r-sureci",
    title: "r-Süreci (Hızlı Nötron Yakalama) Teorisi",
    subtitle: "İki nötron yıldızının çarpışmasında altının ve platinin doğuşu",
    duration: 105,
    color: "#fcd34d",
    cat: "gokyuzu",
    stages: [
      {
        until: 0.14,
        title: "İki Nötron Yıldızı",
        text: "Her biri 1,4 Güneş kütlesini 20 kilometrelik bir küreye sıkıştırır: bir çay kaşığı maddesi milyar ton ağırlığındadır. İkili sistem, kütleçekim dalgaları yayarak enerji kaybeder. Yörüngeler yüzyıllar boyunca milimetre milimetre daralır.",
        era: "Birleşmeden milyonlarca yıl önce",
      },
      {
        until: 0.27,
        title: "Son Turlar",
        text: "Son dakikalarda yörünge periyodu saniyelerden milisaniyelere düşer. Uzay-zaman dokusu, suya atılan taş gibi halka halka titreşir. 17 Ağustos 2017'de LIGO ve Virgo bu titremeyi ilk kez algıladı: GW170817.",
        era: "Son dakikalar",
      },
      {
        until: 0.4,
        title: "Birleşme",
        text: "İki yıldız saniyenin kesirlerinde kaynaşır; madde ışık hızının dörtte biri kadar hızla dışa fırlar. Ortaya saniyeler süren kısa bir gama ışını patlaması çıkar. Uzayda altın üretmek için gereken fırın budur.",
        era: "Birleşme anı",
      },
      {
        until: 0.55,
        title: "r-Süreci",
        text: "Serbest nötronlar, ağır çekirdeklere saniyede milyonlarca kez çarparak yapışır: hızlı nötron yakalama. Ard gelen beta bozunumları bu aşırı nötronlu çekirdekleri kararlı elementlere çevirir. Süreç birkaç saniyede biter.",
        era: "Birleşme sonrası saniyeler",
      },
      {
        until: 0.67,
        title: "Altın Doğar",
        text: "Atom numarası 79: altın, platin ve uranyum gibi çekirdekler bu kaosta doğar. Evrendeki altının yaklaşık tamamı bu yolla üretilmiştir. Süpernovaların payı, toplamın onda birini geçmez.",
        era: "Saniye 3-10",
      },
      {
        until: 0.83,
        title: "Evrene Saçılır",
        text: "Kilonova ışıması günler içinde kızıl-parlak bir sis olarak solur. Saçılan altın ve platin tozu, gökadalar arası boşluğa yayılır. 2017 olayında Dünya kütlelerince değerli metal fırladığı hesaplandı.",
        era: "Günler sonra",
      },
      {
        until: 1,
        title: "Dünya'nın Altını",
        text: "4,5 milyar yıl önce bu tozlar genç Güneş Sistemi'ne karıştı. Gezegenin demir çekirdeğine gömülen altın, son çarpmalarla kabuğa geri getirildi. Yüzüğünüzdeki altın, iki yıldızın ölüm dansının mirasıdır.",
        era: "Bugün",
      },
    ],
    notes: [
      N(0.02, 0.12, "20 km çap · 1,4 M☉ kütle", 0.28, 0.2),
      N(0.14, 0.25, "çay kaşığı: ~1 milyar ton", 0.72, 0.24),
      N(0.27, 0.37, "GW170817: 2017 algılama", 0.3, 0.18),
      N(0.41, 0.52, "nötron yakalama: saniyeler", 0.7, 0.35),
      N(0.55, 0.65, "altın: neredeyse tümü buradan", 0.3, 0.6),
      N(0.68, 0.8, "kilonova: kızıl-parlak sis", 0.7, 0.6),
      N(0.85, 0.97, "yüzükteki altın: yıldız dansı", 0.5, 0.86),
    ],
    cues: [
      C(0.01, "rumble", 0.5),
      C(0.08, "whoosh", 0.5),
      C(0.16, "rumble", 0.6),
      C(0.24, "rumble", 0.85),
      C(0.3, "crash", 1),
      C(0.31, "supernova", 1),
      C(0.42, "zap", 0.7),
      C(0.5, "zap", 0.6),
      C(0.57, "shimmer", 0.8),
      C(0.65, "shimmer", 0.7),
      C(0.72, "chime", 0.6),
      C(0.84, "shimmer", 0.6),
      C(0.95, "chime", 0.7),
    ],
    ticker: [
      "Nötron yıldızı 20 km çapındadır ama kütlesi Güneş'ten ağır: bir şeker kutusu maddesi milyar ton.",
      "Hulse-Taylor ikilisi, kütleçekim dalgalarıyla yörünge kaybını ölçüp Nobel kazandırdı.",
      "GW170817, 130 milyon ışık yılı uzakta algılandı: çok mesajlı gök biliminin ilk büyük olayı.",
      "Kilonova ışıması günler içinde kızıla döner: r-sürecinin renk imzası budur.",
      "r-süreci saniyeler içinde uranyuma kadar uzanan çekirdekler üretir.",
      "Bilinen en ağır nötron yıldızı 2,35 Güneş kütlesi: karadelik eşiğine yakındır.",
      "2017 birleşmesinde saçılan maddenin Dünya kütlelerince altın içerdiği hesaplandı.",
      "Dünya kabuğundaki platin grubu metallerin çoğu aynı kaynaktan gelir: nötron yıldızı çarpışması.",
      "Birleşme öncesi son yörünge turu 1,5 saniyeydi; dalga frekansı binlerce hertz'e ulaştı.",
      "Ay'daki ve Dünya'daki eski altın damarları, evrenin ilk değerli metal fabrikalarının mahsulüdür.",
    ],
  },

  /* 3 ------------------------------------------------------------------ */
  {
    id: "diferansiyasyon",
    title: "Gezegenlerin Diferansiyasyonu Teorisi",
    subtitle: "Eriyik genç gezegende yoğunluk farkıyla çekirdek, manto ve kabuğun doğuşu",
    duration: 115,
    color: "#f97316",
    cat: "jeoloji",
    stages: [
      {
        until: 0.14,
        title: "Eriyik Gezegen",
        text: "Çarpma ısısı, radyoaktif çürüme ve sıkışma, genç Dünya'yı 1.500 °C'ye kadar eritti. Gezegen bir magma okyanusu topu gibiydi. Karışık haldeki madde, yoğunluğuna göre ayrışmaya mahkûmdur.",
        era: "Hadeen: 4,5 milyar yıl önce",
      },
      {
        until: 0.28,
        title: "Demir Damlaları",
        text: "Erimiş demir-nikel damlaları, silikat eriyiğinden yaklaşık iki kat daha yoğundur. Gezegen ölçeğinde yerçekimi, damlaları süzülen yağ gibi içe çeker. Bu süzülme birkaç on milyon yılda tamamlanır.",
        era: "İlk 10-50 milyon yıl",
      },
      {
        until: 0.42,
        title: "Çekirdek Birikir",
        text: "Merkezde metalik bir çekirdek büyür: bugünkü çekirdek, gezegen kütlesinin yaklaşık yüzde 32'sini oluşturur. İç çekirdek katı, dış çekirdek sıvı demir-nikeldir. Merkez sıcaklığı 5.000-6.000 K'yi bulur.",
        era: "İlk 100 milyon yıl",
      },
      {
        until: 0.56,
        title: "Silikatlar Yüzüyor",
        text: "Hafif silikat eriyikleri, suyun balmumunda yüzmesi gibi yukarı çıkar. Yoğun bazaltik manto, kabuğu oluşturan açık renkli kayalardan ağırdır. Gezegen, içi içe tabakalara ayrılır.",
        era: "İlk birkaç yüz milyon yıl",
      },
      {
        until: 0.7,
        title: "Kesit Görünümü",
        text: "Kabuk 5-70 km, manto 2.900 km, çekirdek yarıçapı 3.480 km'dir. Yoğunluk kabukta 2,7, mantoda 4-5, çekirdekte 10-13 g/cm³'tür. Sismik dalgalar bu katmanların fotoğrafını çeker.",
        era: "Bugünkü yapı",
      },
      {
        until: 0.86,
        title: "Jeodinamo",
        text: "Dönen sıvı dış çekirdek, dev bir elektrik dinamosu gibi davranır. Konveksiyon ve rotasyon, gezegeni saran manyetik alanı üretir. Bu kalkan olmasa Güneş rüzgârı atmosferi uzaya süpürebilirdi.",
        era: "Manyetosferin doğuşu",
      },
      {
        until: 1,
        title: "Soğuyan Kabuk",
        text: "Isı kayboldukça yüzey katılaştı ve kraterlerle doldu. Volkanizma ve aşınma bu izleri Dünya'da sildi. Ama Ay ve Merkür, diferansiyasyonun ilk sonucunu hâlâ taşır.",
        era: "İlk milyar yıl",
      },
    ],
    notes: [
      N(0.02, 0.12, "4,5 milyar yıl: eriyik gençlik", 0.5, 0.1),
      N(0.15, 0.26, "demir silikattan 2 kat yoğun", 0.7, 0.28),
      N(0.3, 0.4, "çekirdek: kütlenin %32'si", 0.3, 0.34),
      N(0.44, 0.54, "kabuk 2,7 · çekirdek 13 g/cm³", 0.66, 0.6),
      N(0.58, 0.68, "sismik dalga: iç fotoğraf", 0.3, 0.18),
      N(0.72, 0.84, "jeodinamo: manyetik kalkan", 0.66, 0.82),
      N(0.88, 0.98, "Mars kalkanını kaybetti", 0.35, 0.5),
    ],
    cues: [
      C(0.005, "lava", 0.9),
      C(0.07, "rumble", 0.6),
      C(0.16, "lava", 0.6),
      C(0.3, "rumble", 0.7),
      C(0.44, "merge", 0.8),
      C(0.51, "lava", 0.5),
      C(0.58, "pop", 0.5),
      C(0.64, "rumble", 0.5),
      C(0.73, "whoosh", 0.6),
      C(0.87, "zap", 0.5),
      C(0.93, "freeze", 0.7),
      C(0.98, "crack", 0.6),
    ],
    ticker: [
      "Dünya'nın çekirdeği gezegen kütlesinin yüzde 32'sini oluşturur; Ay'ınki yalnızca yüzde 2'dir.",
      "Demir meteorları, diferansiyasyonun uzaydaki küçük örnekleridir: eriyip ayrılmış asteroid çekirdekleri.",
      "İç çekirdek 1.220 km yarıçapta katı, dış çekirdek 2.260 km'de sıvı demir-nikeldir.",
      "Manyetosfer Güneş rüzgârını saptırır; Mars bu kalkanı kaybetti ve atmosferini yitirdi.",
      "Kutup ışıkları, jeodinamonun gökyüzüne imzasıdır: kalkanın en görkemli görüntüsü.",
      "Sismik S dalgaları sıvıyı geçemez: gölge bölgesi, dış çekirdeğin ilk kanıtıydı.",
      "İlk Dünya günü 6 saat sürüyordu; hızlı dönüş, jeodinamoyu güçlendirdi.",
      "Kıta kabuğu 2,7 g/cm³ ile manto üstünde yüzer: kalın kabuk dağ, ince kabuk deniz tabanı olur.",
      "Psyche asteroidi, çıplak kalmış bir protoplanet çekirdeği olabilir: metal bir dünya.",
      "Bugün bile çekirdek ısısı, tabandan yükselen volkan ve fay hatlarını çalıştırmaya devam eder.",
    ],
  },

  /* 4 ------------------------------------------------------------------ */
  {
    id: "agir-bombardiman",
    title: "Geç Ağır Bombardıman Teorisi",
    subtitle: "Dev gezegenlerin göçüyle kuşağın bozulup iç sistemi dövdüğü dönem",
    duration: 110,
    color: "#e879f9",
    cat: "gokyuzu",
    stages: [
      {
        until: 0.13,
        title: "Sakin Başlangıç",
        text: "4,1 milyar yıl önce gezegenler düzenli yörüngelerde dönüyordu. Asteroit kuşağı, Mars ile Jüpiter arasında sessizce bekliyordu. Bu huzur uzun sürmeyecekti.",
        era: "4,1 milyar yıl önce",
      },
      {
        until: 0.27,
        title: "Devler Göçer",
        text: "Nice modeline göre Jüpiter ve Satürn kütleçekim rezonansına girip yörünge değiştirdi. Devlerin göçü kuşağın rezonanslarını karıştırdı: gövdeler birbirine çarptı ve bir kısmı içe fırlatıldı.",
        era: "Saldırının eşiğinde",
      },
      {
        until: 0.45,
        title: "Asteroid Yağmuru",
        text: "Yüz milyon yıldan uzun bir süre boyunca iç Sistemi 10-100 km çapında gövdeler dövdü. Ay, Merkür ve Mars aynı anda yaralar aldı. Çarpma oranı bugününkünün en az 100 katıydı.",
        era: "4,1-3,8 milyar yıl önce",
      },
      {
        until: 0.6,
        title: "Ay'ın Kaderi",
        text: "Ay'daki Imbrium havzası 1.145 km çapındadır: dev bir gövdenin bıraktığı iz. Sonradan bazalt lavaları bu havzaları doldurdu ve koyu denizleri (maria) oluşturdu. Krater sayısı, dönemin yoğunluğunun doğrudan ölçümüdür.",
        era: "Ay yüzeyinde",
      },
      {
        until: 0.74,
        title: "Dünya Şanslı",
        text: "Dünya'nın okyanusları çarpma ısısını yuttu ve kabuk yeniden oluştu. Buzlu gövdelerin getirdiği su, denizleri tazeledi. Yaşın ilk kesin izleri tam bu sakinleşme sonrasında görülür.",
        era: "İlk okyanuslar",
      },
      {
        until: 0.89,
        title: "Bugünün Arşivi",
        text: "Ay, atmosfere ve erozyona sahip olmadığı için çarpma kaydını saklar. Yoğun krater dokusu, 4-3,8 milyar yıl önceki saldırının haritasıdır. Ay yüzeyi, Güneş Sistemi'nin kara kutusudur.",
        era: "Bugün: Ay yüzeyi",
      },
      {
        until: 1,
        title: "Sakinleşme",
        text: "Dev gezegenler yerleşince kuşak temizlendi ve çarpma oranı düştü. Kalan gövdeler bugün asteroit kuşağı ve Trojalar. Sakin bir sistem, karmaşık yaşama zemin hazırladı.",
        era: "Arkean öncesi son",
      },
    ],
    notes: [
      N(0.02, 0.11, "dönem: 4,1-3,8 milyar yıl önce", 0.5, 0.1),
      N(0.15, 0.25, "Nice modeli: dev gezegen göçü", 0.72, 0.22),
      N(0.29, 0.43, "çarpma oranı: bugünün 100 katı", 0.28, 0.3),
      N(0.46, 0.58, "Imbrium havzası: 1.145 km", 0.7, 0.2),
      N(0.61, 0.72, "buzlu gövdeler suyu getirdi", 0.28, 0.6),
      N(0.75, 0.87, "Ay: doğal çarpma arşivi", 0.66, 0.5),
      N(0.9, 0.98, "sakinleşme: yaşam zemini", 0.5, 0.86),
    ],
    cues: [
      C(0.01, "shimmer", 0.5),
      C(0.14, "whoosh", 0.6),
      C(0.21, "rumble", 0.6),
      C(0.3, "whoosh", 0.7),
      C(0.38, "crash", 0.8),
      C(0.45, "crash", 0.9),
      C(0.51, "crash", 1),
      C(0.55, "boom", 0.8),
      C(0.62, "crash", 0.7),
      C(0.72, "splash", 0.6),
      C(0.8, "boom", 0.6),
      C(0.9, "wind", 0.5),
      C(0.96, "chime", 0.5),
    ],
    ticker: [
      "Geç Ağır Bombardıman 4,1-3,8 milyar yıl önce yaşandı ve yüz milyon yıldan fazla sürdü.",
      "Ay'daki Imbrium çarpması 1.145 km'lik havza açtı; çarpma Dünya'dan çıplak gözle izlenebilirdi.",
      "Nice modeli, Satürn'ün Jüpiter'i geçmesiyle kuşak rezonanslarının bozulduğunu öngörür.",
      "Merkür, Ay ve Mars aynı dönemde yoğun kraterleşti: saldırının kaynağı ortaktı.",
      "Buzlu gövdelerin getirdiği su, Dünya'nın okyanuslarını tazelemiş olabilir.",
      "Ay'da bir metre derinlik kazmak, dört milyar yıl öncenin tarihini okumak gibidir.",
      "Mare adı verilen koyu düzlükler, havzaları dolduran genç bazalt lavalarıdır.",
      "Bugün çarpma oranı dönemine göre en az 100 kat azaldı: sistem sakinleşti.",
      "Apollo örneklerindeki erimiş cam boncuklar, çarpma anının sıcaklığını saklar.",
      "Krater yoğunluğu, bir yüzeyin yaşını ölçen en eski ve en güvenilir saatlerden biridir.",
    ],
  },

  /* 5 ------------------------------------------------------------------ */
  {
    id: "hidrotermal-damar",
    title: "Hidrotermal Damar Oluşum Teorisi",
    subtitle: "Kızgın kabukta dolaşan sıcak suların çatlaklara altın damarları yazması",
    duration: 100,
    color: "#facc15",
    cat: "jeoloji",
    stages: [
      {
        until: 0.16,
        title: "Kızgın Kabuk",
        text: "Magma odalarının 1-3 km üzerindeki kabuk, 50-400 °C sıcaklıklarda dev bir ısı makinesidir. Yeraltı suyu çatlaklardan aşağı süzülüp kızgın kayaya değer. Doğal kazan böylece çalışmaya başlar.",
        era: "Derin kabuk",
      },
      {
        until: 0.32,
        title: "Su Süzülür, Isınır",
        text: "Derinlere inen su, yüksek basınç sayesinde kaynama noktasını aşsa da sıvı kalır. Isınan su hafifler ve konveksiyonla yukarı dönmeye başlar. Dolaşım, yıllarca süren bir hücre gibi döner.",
        era: "Sirkülasyon hücresi",
      },
      {
        until: 0.48,
        title: "Mineral Çözünür",
        text: "Sıcak çözelti, kayadan silikon, demir, bakır ve altın iyonlarını koparıp taşır. Altın bu suda milyonda birkaç parça düzeyinde dolaşır. Yıllar içinde damar dolusu metal çözünmüş olur.",
        era: "Çözelti yüklendi",
      },
      {
        until: 0.64,
        title: "Çatlakta Çökelir",
        text: "Yükselen çözelti soğuyunca ve basınç düşünce çözünürlüğü düşer. Mineraller çatlak duvarına katman katman çöker: önce pirit, sonra kuvars, en son altın. Damar böylece doğar.",
        era: "Damarın doğuşu",
      },
      {
        until: 0.82,
        title: "Damar Ağı",
        text: "Ana damar, çatlak ağını izleyerek dallanır: kuvars gövdesi, sulfür şeritleri ve altın saçakları. Binlerce yılda kalınlaşan damarlar kilometre uzunluğa ulaşır. Buna epitermal sistem denir.",
        era: "Binlerce yıl sonra",
      },
      {
        until: 1,
        title: "Bugünün Madeni",
        text: "Günümüzde damarlar galerilerle izlenir ve cevher yüzeye çıkarılır. Altın damarları 1-2 km derinlikten işletilir. En zengin cevher, damarların çatallı ek yerlerinde birikir.",
        era: "Günümüz",
      },
    ],
    notes: [
      N(0.02, 0.14, "çözelti: 50-400 °C", 0.5, 0.12),
      N(0.17, 0.29, "basınçlı su kaynamadan ısınır", 0.7, 0.3),
      N(0.32, 0.43, "altın: ppm düzeyinde taşınır", 0.3, 0.55),
      N(0.46, 0.57, "sıra: pirit → kuvars → altın", 0.68, 0.28),
      N(0.6, 0.72, "epitermal: 1-2 km derinlik", 0.3, 0.24),
      N(0.76, 0.96, "Mponeng madeni: 4 km", 0.68, 0.8),
    ],
    cues: [
      C(0.005, "lava", 0.8),
      C(0.08, "hiss", 0.7),
      C(0.18, "hiss", 0.5),
      C(0.26, "splash", 0.5),
      C(0.34, "shimmer", 0.6),
      C(0.44, "shimmer", 0.6),
      C(0.52, "freeze", 0.7),
      C(0.62, "chime", 0.6),
      C(0.72, "crack", 0.6),
      C(0.82, "shimmer", 0.7),
      C(0.9, "crack", 0.5),
      C(0.97, "chime", 0.7),
    ],
    ticker: [
      "Hidrotermal çözeltiler 50-400 °C aralığında çalışır: yerin altındaki doğal kazanlar.",
      "Altın suda ppm düzeyinde taşınır ve damarda bir gecede çökebilir.",
      "Kaynama anında basınç düşer ve altın çökelir: epitermal damarların altın savakları.",
      "Kuvars damarları, binlerce yıl boyunca çatlak duvarına katman katman büyür.",
      "Dünyanın en derin altın madeni Mponeng'dir: 4 km derinlik ve 60 °C kaya sıcaklığı.",
      "Türkiye'nin altın yataklarının çoğu epitermal damar ve saçılım tipidir.",
      "Siyah tütüncüler, okyanus dibi hidrotermal bacalardır: 350 °C su ve metal sulfürleri püskürtür.",
      "Bakır damarları Antik Çağ'dan beri Kıbrıs ve Sardes gibi merkezlerde işlendi.",
      "Çökelme sırası pirit → kuvars → altın şeklindedir: damarın iç tarihçesi okunabilir.",
      "Çözelti soğudukça çözünürlük düşer; basınç düşüşü de aynı işi yapar.",
    ],
  },

  /* 6 ------------------------------------------------------------------ */
  {
    id: "magmatik-ayrisma",
    title: "Magmatik Ayrışma Teorisi",
    subtitle: "Soğuyan magma odasında kristallerin Bowen serisine göre sırayla ayrılması",
    duration: 120,
    color: "#fb923c",
    cat: "jeoloji",
    stages: [
      {
        until: 0.13,
        title: "Magma Odası",
        text: "Yerin 5-30 km altındaki odada ergiyik 1.000-1.200 °C'de kıpırdanır. Bu eriyik yüzde 45-75 arası silikon dioksit taşır. Odanın kaderi, soğuma hızına bağlıdır.",
        era: "Derin magma odası",
      },
      {
        until: 0.26,
        title: "Soğuma Başlar",
        text: "Odanın kenarları, duvar kayasına temasla önce soğur ve ince bir katı kabuk belirir. Bu kabuk içeriği yalıtır ve soğumayı yavaşlatır. Tam kristallenme milyonlarca yıl sürebilir.",
        era: "Kenar kabuğu",
      },
      {
        until: 0.4,
        title: "Bowen Serisi",
        text: "Norman Bowen 1920'lerde kristalleşme sırasını çözdü: olivin, piroksen, amfibol, biyotit. Kalsiyumca zengin feldspat da erken katılır. Her mineral, ergiyikten kendi kimyasal imzasını alır.",
        era: "Kristalleşme başlar",
      },
      {
        until: 0.54,
        title: "Kristaller Batar",
        text: "Olivin ve piroksen kristalleri ergiyikten çok daha yoğundur. Binlerce yıl içinde tabana çöker ve koyu bir kümülat katmanı oluşturur. Odanın tabanı kristal bir arşive döner.",
        era: "Kümülat katmanı",
      },
      {
        until: 0.68,
        title: "Kalan Sıvı Zenginleşir",
        text: "Erken kristaller demir ve magnezyumu aldıkça, kalan ergiyik silikon ve alüminyumca zenginleşir. Renk açılır: koyu bazaltik tonlardan krem sarısına. Son damla, en hafif bileşimin damlasıdır.",
        era: "Kalıntı ergiyik",
      },
      {
        until: 0.84,
        title: "Granit Kabuk",
        text: "Kalan ergiyik 700-800 °C'de katılaşır: kuvars, feldspat ve mika. Bu karışım granittir ve kıta kabuğunun ana malzemesidir. Koyu mineraller tabanda kaldı, üstte açık granit yattı.",
        era: "Kıtaların kemikleri",
      },
      {
        until: 1,
        title: "Pegmatit",
        text: "Son artıklar su ve uçucu gaz bakımından zengindir. Bu sıvı çatlaklara kaçar ve metre boyutlu feldspat, kuvars ve turmalin kristalleri büyür. Kristal mücevherleri buradan çıkar.",
        era: "Son damlalar",
      },
    ],
    notes: [
      N(0.02, 0.12, "magma: 1.000-1.200 °C", 0.5, 0.1),
      N(0.15, 0.25, "kenar kabuğu önce katılaşır", 0.72, 0.24),
      N(0.28, 0.39, "olivin: ilk kristal", 0.28, 0.3),
      N(0.42, 0.53, "kümülat: taban madeni", 0.68, 0.62),
      N(0.56, 0.68, "granit: %70 silika", 0.3, 0.2),
      N(0.72, 0.96, "pegmatit: metrelik kristaller", 0.66, 0.82),
    ],
    cues: [
      C(0.005, "lava", 0.9),
      C(0.1, "rumble", 0.5),
      C(0.18, "hiss", 0.6),
      C(0.28, "crack", 0.6),
      C(0.4, "crack", 0.7),
      C(0.54, "freeze", 0.6),
      C(0.66, "shimmer", 0.6),
      C(0.8, "freeze", 0.7),
      C(0.92, "chime", 0.8),
      C(0.97, "chime", 0.5),
    ],
    ticker: [
      "Norman Bowen, 1920'lerde laboratuvarda ergiyik soğutarak kristal sırasını çözdü.",
      "Olivin ilk doğan minerallerden biridir: yeşil taneleri koyu taban katmanlarında batar.",
      "Tabandaki kümülat katmanları, dünyanın platin ve krom madenlerinin ana kaynağıdır.",
      "Bazaltik magma 1.200 °C'de, granitik ergiyik 700 °C civarında katılaşır.",
      "Kıta kabuğu granit bileşimlidir; okyanus kabuğu ise koyu ve yoğun bazalttır.",
      "Pegmatitlerde metrelik kristaller bulunur: dünyanın en büyük kuvars ve feldspat blokları.",
      "Su ve bor gibi uçucular, pegmatit kristallerini dev boyuta taşır.",
      "Bowen serisinin iki kolu vardır: demir-magnezyum zinciri ve feldspat zinciri.",
      "Dayke ve sill'ler, magma odasından sızan son damlaların donmuş kanallarıdır.",
      "Yosemite'nin granit duvarları, yükselip soğumuş bir magma odasının açık kesitidir.",
    ],
  },

  /* 7 ------------------------------------------------------------------ */
  {
    id: "sedimantasyon",
    title: "Sedimantasyon ve Alüvyon Teorisi",
    subtitle: "Dağlardan deltaya tortunun taşınıp katman katman kayaya dönmesi",
    duration: 115,
    color: "#d9b98a",
    cat: "jeoloji",
    stages: [
      {
        until: 0.13,
        title: "Dağlar ve Yağmur",
        text: "Yüksek dağlar, atmosferin saldırısına açık dev kayalardır. Yağmur suyu çatlaklara girer, gece donar ve kayayı yırtar. Himalaya'dan her yıl milyarlarca ton tortu süzülür.",
        era: "Yükseklik: aşınmanın sahnesi",
      },
      {
        until: 0.27,
        title: "Aşınma",
        text: "Buz, su ve rüzgâr kaya kenarlarını ufalar: önce bloklar, sonra çakıl, sonra kum. Parçacık küçüldükçe taşınması kolaylaşır. Dağın zirvesi, bir gün bir deltada kum tanesi olur.",
        era: "Fiziksel aşınma",
      },
      {
        until: 0.41,
        title: "Nehir Taşır",
        text: "Nehirler tortuyu boyuta göre ayrımlayarak taşır: çakıl hızlı akıntıda, kil yavaş suda. Ganj-Brahmaputra yılda yaklaşık 1 milyar ton tortuyu Bengal Körfezi'ne boşaltır.",
        era: "Taşınma",
      },
      {
        until: 0.56,
        title: "Çökelme",
        text: "Deltaya ulaşan su yavaşlar: ağır çakıl önce, kil en son çöker. Katman katman yatay bantlar birikir; her bant bir mevsimin ya da yüz bin yılın kaydıdır. Bu katmanlara tabaka denir.",
        era: "Delta",
      },
      {
        until: 0.7,
        title: "Fosil İzi",
        text: "Bir balık oksijensiz çamura gömülür ve kalıbı katmana basılır. Milyonlarca yıl sonra bu iz, katmanın yaşını ve çevresini söyler. Fosil, Dünya'nın parmak izidir.",
        era: "Gömülü yaşam",
      },
      {
        until: 0.85,
        title: "Basınçla Taşlaşır",
        text: "Üst katmanlar kilometreleri bulan ağırlıkla baskı yapar. Gözenekler kapanır, su sıkışır ve mineraller çimentoya dönüşür. Kum kumtaşı, çamur şeyli olur: buna diyajenez denir.",
        era: "Diyajenez",
      },
      {
        until: 1,
        title: "Kayaç ve Vadi",
        text: "Nehir yatağını derinleştirir ve vadi kesiti tüm tabakaları açığa çıkarır. Grand Canyon'da 1,5 km'lik kesitte 2 milyar yıllık tarih sıralıdır. Kayaç, Dünya'nın açılmış günlüğüdür.",
        era: "Bugün: tabaka manzarası",
      },
    ],
    notes: [
      N(0.02, 0.12, "Himalaya: milyarlarca ton/yıl", 0.5, 0.12),
      N(0.16, 0.26, "donma-çözülme kayayı yırtar", 0.7, 0.3),
      N(0.3, 0.4, "Ganj: 1 milyar ton tortu/yıl", 0.28, 0.6),
      N(0.44, 0.56, "her bant bir zaman sayfası", 0.68, 0.3),
      N(0.6, 0.7, "fosil: ani gömülme eseridir", 0.3, 0.24),
      N(0.74, 0.97, "Grand Canyon: 2 milyar yıl", 0.68, 0.82),
    ],
    cues: [
      C(0.005, "rain", 0.8),
      C(0.08, "rain", 0.6),
      C(0.16, "wind", 0.6),
      C(0.27, "wind", 0.7),
      C(0.36, "splash", 0.6),
      C(0.46, "splash", 0.5),
      C(0.58, "chime", 0.6),
      C(0.7, "rumble", 0.6),
      C(0.84, "crack", 0.7),
      C(0.94, "wind", 0.5),
    ],
    ticker: [
      "Ganj-Brahmaputra deltası yılda 1 milyar ton tortu biriktirir: dünyanın en hızlı büyüyen kara parçası.",
      "Amazon nehrinin yıllık tortu yükü 1 milyar tonu aşar: okyanusa kum taşıyan dev konveyör.",
      "Kum çamurdan hızlı çöker; kil tanecikleri ise aylarca suyun içinde asılı kalabilir.",
      "Grand Canyon kesiti, 2 milyar yıllık kayacı 1,5 km derinlikte sergiler.",
      "Diyajenezde gözenek suyu sıkışır, kalsit ve silis çimentosu taşlaşmayı tamamlar.",
      "Balık fosilleri ani gömülmelerin kaydıdır: oksijensiz çamur onları çürütmeden korur.",
      "Çapraz tabakalaşma, eski rüzgâr ve akıntı yönünün kayada saklanmış okuma parçasıdır.",
      "Kalker, deniz canlılarının kabuk ve iskelet birikiminin kimyasal hediyesidir.",
      "Turba, üstüne binen yükün basıncıyla önce lignit sonra antrasit kömüre dönüşür.",
      "Buzul gölleri yıllık halkalar bırakır: varv katmanları takvim gibi okunur.",
    ],
  },

  /* 8 ------------------------------------------------------------------ */
  {
    id: "biyojenik-cevherlesme",
    title: "Biyojenik Cevherleşme (Demir Oluşumu) Teorisi",
    subtitle: "Siyanobakterilerin oksijeninin demiri çöktürüp dev maden damarlarını yazması",
    duration: 125,
    color: "#a3e635",
    cat: "jeoloji",
    stages: [
      {
        until: 0.13,
        title: "İlkel Okyanus",
        text: "3 milyar yıl önce okyanuslar demirce zengindi: Fe2+ iyonları suda erimiş bekliyordu. Atmosferde serbest oksijen yoktu; su gri-yeşil ve bulanıktı. Gezegen, metal bir solüsyonun içindeydi.",
        era: "Arkean: 3 milyar yıl önce",
      },
      {
        until: 0.27,
        title: "Siyanobakteriler",
        text: "Siyanobakteriler güneş ışığıyla suyu parçalar ve atık olarak oksijen üretir. Bu atık, o dönemin yaşamı için bir zehirdi. Milyar yıllarca sessizce denize baloncuk püskürttüler.",
        era: "İlk fotosentez",
      },
      {
        until: 0.42,
        title: "Pas Doğar",
        text: "Oksijen demirle karşılaşır karşılaşmaz çözünmez oksit (Fe3+) oluşur: pas. Turuncu çamurlar suya karışır ve tabana kar fırtınası gibi batar. Deniz, kızıl bir çökelme sahnesine döner.",
        era: "Kimyasal çökelme",
      },
      {
        until: 0.57,
        title: "Şeritli Demir Oluşumu",
        text: "Milyonlarca yıllık döngüde koyu şeyl ve turuncu demir oksit şeritleri dönüşümlü birikir. Buna şeritli demir oluşumu (BIF) denir ve dünyanın ana demir kaynağıdır. Katmanlar 1 km kalınlığa ulaşır.",
        era: "Proterozoyik",
      },
      {
        until: 0.71,
        title: "Oksijen Gökyüzüne",
        text: "Denizdeki demir tükenince oksijen yüzeye taşındı: atmosferdeki oran yüzde bir eşiğini aştı. Gökyüzü kimyası değişti, demirin cürufu denizden silindi. Bu, gezegenin ilk büyük nefesiydi.",
        era: "2,4 milyar yıl önce",
      },
      {
        until: 0.86,
        title: "Büyük Oksijen Felaketi",
        text: "Oksijen, anaerobik canlıların çoğu için öldürücüdür. Dünya tarihinin ilk büyük yok oluşu yaşandı. Hayatta kalanlar, oksijeni enerjiye çevirmeyi öğrenenler oldu.",
        era: "İlk büyük yok oluş",
      },
      {
        until: 1,
        title: "Demir Çağı",
        text: "Bugün dünyada yılda yaklaşık 2,5 milyar ton demir cevheri çıkarılıp çeliğe dönüşür. Kökeni, 2,5 milyar yıl önceki bakterilerin atığıdır. Gökdelendeki her kiriş, eski bir denizin pasıdır.",
        era: "Günümüz: çelik çağı",
      },
    ],
    notes: [
      N(0.02, 0.12, "okyanus: Fe2+ yüklü", 0.5, 0.55),
      N(0.16, 0.26, "O2 ilk başta zehirdi", 0.7, 0.3),
      N(0.3, 0.4, "Fe2+ erir · Fe3+ çöker", 0.3, 0.68),
      N(0.44, 0.55, "BIF: dünyanın demiri", 0.68, 0.24),
      N(0.58, 0.68, "O2: %1 eşiğini aştı", 0.3, 0.16),
      N(0.72, 0.83, "ilk büyük yok oluş", 0.68, 0.6),
      N(0.87, 0.97, "çelik: bakteri mirası", 0.5, 0.86),
    ],
    cues: [
      C(0.005, "cell", 0.7),
      C(0.1, "cell", 0.6),
      C(0.2, "pop", 0.5),
      C(0.3, "splash", 0.5),
      C(0.42, "grow", 0.7),
      C(0.5, "grow", 0.8),
      C(0.58, "shimmer", 0.6),
      C(0.66, "rumble", 0.7),
      C(0.73, "crack", 0.5),
      C(0.88, "engine", 0.8),
      C(0.95, "chime", 0.6),
    ],
    ticker: [
      "Şeritli demir oluşumları, dünyanın demir üretiminin büyük bölümünün kaynağıdır.",
      "Büyük Oksijen Olayı 2,4 milyar yıl önce yaşandı: atmosferin ilk zehirlenmesi.",
      "Siyanobakteriler milyar yıllarca denize oksijen baloncukları püskürttü.",
      "Hamersley havzasındaki BIF katmanları 1 km kalınlığa ulaşır; şeritler metrelik ritim taşır.",
      "Fe2+ suda çözünür, Fe3+ çözünmez: pasın doğuşu çökelmenin anahtarıdır.",
      "Huron buzullaşması, oksijenin metanı yutmasının getirdiği ilk kar topu dünyasıdır.",
      "Bugün yılda yaklaşık 2,5 milyar ton demir cevheri çıkarılır; çoğu BIF'ten gelir.",
      "Oksijen felaketi, mitokondrinin doğuşunu zorladı: enerji devrimi bir zehirden doğdu.",
      "Denizlerdeki demir tükendiğinde oksijen atmosfere kaçtı; gökyüzünün kimyası değişti.",
      "Çelik, bakterilerin 2,5 milyar yıl önceki atık ürününün sanayi hâlidir.",
    ],
  },
];
