import type { TheoryDef } from "../theories";
import { N, C } from "./helpers";

/**
 * Evrim teorileri paketi (6 teori) — Darwinizm'den Lamarckizm'e.
 *
 * Her teori 6-7 aşamalı, gerçek bilim tarihi referanslı (Darwin 1859,
 * Eldredge-Gould 1972, Margulis 1967, Kimura 1968, Weismann 1892),
 * küçük bilgi balonları (notes) ve ses ipuçları (cues) ile tanımlıdır.
 */
export const EVOLUTION_THEORIES: TheoryDef[] = [
  {
    id: "dogal-secilim",
    cat: "yasam",
    title: "Doğal Seçilim Yoluyla Evrim (Darwinizm)",
    subtitle:
      "Varyasyon, seçilim ve kalıtım — popülasyonları kuşaktan kuşağa dönüştüren sabırlı motor",
    duration: 125,
    color: "#84cc16",
    stages: [
      {
        until: 0.12,
        title: "Varyasyon: Böcek Popülasyonu",
        text: "Aynı türün bireyleri birbirinin kopyası değildir: renk, boyut ve dayanıklılıkta sürekli varyasyon vardır. Darwin, HMS Beagle yolculuğunda (1831-1836) bu küçük farkların hayatta kalma şansını değiştirebildiğini fark etti. Varyasyon, seçilimin işleyebilmesi için gereken ham maddedir.",
        era: "1831-1836 · Beagle yolculuğu",
      },
      {
        until: 0.25,
        title: "Çevre Değişiyor: Sanayi Devrimi",
        text: "Endüstriyel duman, ağaç gövdelerini yosunlu açık renkten isli siyaha çevirdi. Kara benekli güve (Biston betularia) için saklanma kuralları kuşaklar içinde tersine döndü. Çevre değişince seçilimin yönü de değişir: aynı popülasyon, yeni bir sınavla karşılaşır.",
        era: "19. yüzyıl · İngiltere",
      },
      {
        until: 0.38,
        title: "Kuş Avcısı: Görünür Olan Yenilir",
        text: "Uçan avcılar görsel seçilim uygular: gövdeye uymayan renk ilk bakışta ele verir. Açık renkli güveler isli gövdelerde kolayca yakalanırken koyular görünmez kalır. Yenilenler döl bırakamaz; seçilim popülasyonun bileşimini tek başına değiştirir.",
        era: "1859 · Türlerin Kökeni",
      },
      {
        until: 0.52,
        title: "Koyular Çoğalıyor: Nesil Sayaç",
        text: "Hayatta kalanlar renklerini kalıtım yoluyla yavrularına aktarır; birkaç nesilde koyu form baskın hale gelir. Kettlewell'in 1950'lerdeki deneyi, kirli bölgelerde koyu güvelerin belirgin avantajlı olduğunu ölçtü. Frekans kayması, seçilimin el yazısıdır.",
        era: "1950'ler · Kettlewell'in deneyi",
      },
      {
        until: 0.67,
        title: "Galapagos İspinozları",
        text: "Darwin 1835'te Galapagos'ta ispinozları topladı; gaga biçimlerinin adadan adaya besine göre değiştiğini not etti. Tohum kırıcı kalın gagalar, böcek avlayan ince gagalar, kaktüs delen sivri gagalar. Grant çifti, Daphne Major'da bu seçilimi 40 yılı aşkın süredir kuş halkalayarak doğrudan ölçüyor.",
        era: "1835 · Galapagos Adaları",
      },
      {
        until: 0.84,
        title: "Seçilim Döngüsü",
        text: "Evrimin motoru üç adımlık bir döngüdür: varyasyon üretir, seçilim eler, kalıtım korur. Döngü her nesilde yeniden çalışır ve sonuç kuşaklar boyunca birikir. Tek bir nesilde fark edilmez; ama milyonlarca nesil, görkemli dönüşümlere yeter.",
        era: "Teorinin çekirdeği",
      },
      {
        until: 1,
        title: "Yeni Tür: Adaptif Işınlama",
        text: "Gagalar farklılaştıkça davranışlar da farklılaşır: farklı şarkı, farklı mevsim, farklı ada. Artık karışmayan gruplar üreme yalıtımıyla iki ayrı tür sayılır. Darwinizm'in iddiası budur: ortak bir ata, seçilimle dallara ayrılır.",
        era: "Türleşme anı",
      },
    ],
    notes: [
      N(0.02, 0.1, "40 böcek: açık ve koyu varyant", 0.22, 0.28),
      N(0.06, 0.11, "varyasyon = evrimin ham maddesi", 0.76, 0.2),
      N(0.16, 0.24, "isli gövdede koyu görünmez", 0.72, 0.42),
      N(0.3, 0.37, "kuş: görsel avcı", 0.24, 0.2),
      N(0.44, 0.51, "nesil 7: koyular baskın", 0.7, 0.34),
      N(0.57, 0.66, "1835: Galapagos ispinozları", 0.26, 0.3),
      N(0.71, 0.79, "varyasyon → seçilim → kalıtım", 0.5, 0.14),
      N(0.88, 0.97, "üreme yalıtımı = yeni tür", 0.72, 0.28),
    ],
    cues: [
      C(0.001, "wind", 0.4),
      C(0.06, "pop", 0.5),
      C(0.12, "grow", 0.7),
      C(0.2, "wind", 0.7),
      C(0.27, "pop", 0.6),
      C(0.38, "grow", 0.8),
      C(0.52, "pop", 0.7),
      C(0.55, "wind", 0.5),
      C(0.67, "chime", 0.6),
      C(0.84, "grow", 0.9),
      C(0.96, "chime", 0.7),
    ],
    ticker: [
      "Darwin, HMS Beagle ile 1831-1836 arasında dünyayı dolaştı; Galapagos'ta beş hafta kaldı.",
      "Türlerin Kökeni 24 Kasım 1859'da yayımlandı; ilk baskı 1.250 kopyaydı ve ilk gün tükendi.",
      "Endüstriyel melanizm: İngiltere'de isli gövdelerde koyu benekli güveler avcılardan saklandı.",
      "Kettlewell (1950'ler), kirli bölgelerde koyu güvelerin açık renklilerden uzun yaşadığını gösterdi.",
      "Galapagos'ta 13 ispinoz türü, farklı gaga biçimleriyle farklı tohum ve böcekleri işler.",
      "Grant çifti, Daphne Major'da 40 yılı aşkın süredir kuş halkalayarak gerçek zamanlı seçilim ölçüyor.",
      "1977 kuraklığından sonra ispinozların ortalama gaga derinliği ölçülebilir biçimde arttı.",
      "Seçilim bireyi değil popülasyonu dönüştürür; bireyler yalnızca hayatta kalır ya da kalmaz.",
      "Darwin, Mendel genetiğinden habersizdi; kalıtımın mekanizması 1900'de yeniden keşfedildi.",
    ],
  },
  {
    id: "modern-sentetik",
    cat: "yasam",
    title: "Modern Sentetik Evrim Teorisi (Neo-Darwinizm)",
    subtitle:
      "DNA, mutasyon, rekombinasyon ve gen frekansları — seçilimin kalıtım bilimiyle buluştuğu çerçeve",
    duration: 120,
    color: "#22d3ee",
    stages: [
      {
        until: 0.13,
        title: "Kalıtımın Moleküler Temeli",
        text: "Kalıtımın maddesi 1953'te çözüldü: Watson ve Crick'in çift sarmalı, Franklin'in X-ışını görüntülerine dayanıyordu. Bilgi, dört bazın diziliminde saklanır. Seçilim, kalıtsal değişkenliğin kaynağını ilk kez biliyordu.",
        era: "1953 · DNA çift sarmalı",
      },
      {
        until: 0.26,
        title: "Mutasyon: Ham Madde Üretimi",
        text: "Mutasyon, baz dizisindeki kopyalanma hatası ya da zarar görmesidir; tek bir nokta değişimi bile proteini değiştirebilir. Mutasyonlar rastgeledir: organizmanın ihtiyacına göre gelmezler. Ama seçilimin işleyeceği yeni varyasyonu tedarik ederler.",
        era: "Moleküler genetik",
      },
      {
        until: 0.39,
        title: "Rekombinasyon: Yeni Kombinasyonlar",
        text: "Mayoz sırasında kromozomlar parça takası yapar: crossing-over. Rekombinasyon, ebeveynlerden gelen alelleri yeni kombinasyonlara karıştırır; her yavru benzersiz bir harmandır. Cinsel çoğalmayı bu kadar pahalıya değdiren şey budur.",
        era: "Sitogenetik",
      },
      {
        until: 0.53,
        title: "Gen Havuzu ve Frekanslar",
        text: "Popülasyon genetiği, seçilimi sayıya çevirir: bir alelin frekansı, gen havuzundaki payıdır. Hardy-Weinberg dengesi (1908) gösterir ki seçilim olmadan frekanslar kuşak boyunca sabit kalır. Seçilim devredeyse denge bozulur ve frekans kayar.",
        era: "1908 · Hardy-Weinberg",
      },
      {
        until: 0.68,
        title: "Mutasyon + Seçilim Birlikte",
        text: "Mutasyon varyasyonu tedarik eder, seçilim yön verir: ikisi birlikte çalışır. Ortalama değer, yeni koşulların istediği tarafa doğru kuşak kuşak sürüklenir. Neo-Darwinizm'in özeti budur: rastgele üretim, yönlü filtre.",
        era: "1930-1950 · sentez",
      },
      {
        until: 0.84,
        title: "İzolasyon: Havuzlar Ayrılıyor",
        text: "Popülasyon ikiye ayrılınca — bir nehir, bir ada, bir dağ sırası — gen akışı kesilir. İki tarafta beliren mutasyonlar artık karışamaz; her havuz kendi yoluyla farklılaşır. Coğrafik izolasyon, türleşmenin en yaygın yoludur: allopatrik türleşme.",
        era: "Türleşme mekanizması",
      },
      {
        until: 1,
        title: "Modern Sentetik Teori",
        text: "1930-1950 arasında Fisher, Haldane ve Wright'ın matematiği, Dobzhansky ve Mayr'ın saha verisiyle birleşti: modern sentetik teori doğdu. Genetik, paleontoloji ve sistematik tek bir çerçevede buluştu. Bugün moleküler veriler bu çerçeveyi her gün yeniden doğruluyor.",
        era: "1937 · Dobzhansky, 1942 · Mayr",
      },
    ],
    notes: [
      N(0.03, 0.11, "A-T ve G-C baz çiftleri", 0.72, 0.22),
      N(0.17, 0.25, "nokta mutasyonu: A → G", 0.28, 0.3),
      N(0.29, 0.37, "mayoz: parça takası", 0.72, 0.36),
      N(0.42, 0.51, "gen frekansı: havuzdaki pay", 0.24, 0.26),
      N(0.56, 0.66, "tepe, yeni dengeye kayıyor", 0.74, 0.4),
      N(0.71, 0.8, "nehir = coğrafik bariyer", 0.5, 0.16),
      N(0.87, 0.96, "gen havuzu artık karışmıyor", 0.26, 0.3),
    ],
    cues: [
      C(0.001, "shimmer", 0.4),
      C(0.13, "chime", 0.6),
      C(0.19, "zap", 0.8),
      C(0.26, "zap", 0.5),
      C(0.29, "shimmer", 0.6),
      C(0.39, "grow", 0.7),
      C(0.53, "shimmer", 0.7),
      C(0.6, "zap", 0.4),
      C(0.68, "chime", 0.5),
      C(0.84, "grow", 0.9),
      C(0.96, "chime", 0.7),
    ],
    ticker: [
      "Modern sentez, 1930-1950 arasında Darwinci seçilimle Mendel genetiğini tek çerçevede birleştirdi.",
      "Fisher, Haldane ve Wright matematiği kurdu; Dobzhansky ve Mayr sahayla buluşturdu.",
      "Watson ve Crick 1953'te çift sarmalı açıkladı; Franklin'in X-ışını fotoğrafları kilit kanıttı.",
      "İnsan genomunda her doğumda yaklaşık 60-100 yeni mutasyon birikir: ham madde hiç bitmez.",
      "Hardy-Weinberg dengesi (1908): seçilim, mutasyon ve göç yoksa frekanslar sabit kalır.",
      "Mutasyonlar rastgeledir, seçilim yönlüdür: karıştırıcı ile filtre birlikte çalışır.",
      "Rekombinasyon, mayozdaki krossing-over ile alelleri yeni kombinasyonlara karıştırır.",
      "Nehir, ada veya dağ sırası gen akışını keser: allopatrik türleşmenin klasik başlangıcıdır.",
    ],
  },
  {
    id: "kesintili-denge",
    cat: "yasam",
    title: "Kesintili Denge (Punctuated Equilibrium) Teorisi",
    subtitle:
      "Milyonluk durgunluklara gömülü ani türleşmeler — fosil kaydının dik basamaklı tarihi",
    duration: 110,
    color: "#fb923c",
    stages: [
      {
        until: 0.14,
        title: "Uzun Durgunluk: Stazis",
        text: "Fosil kaydının büyük bölümünde türler milyonlarca yıl neredeyse hiç değişmez: buna stazis denir. Katman katman sedimanlar, aynı morfolojinin sessiz tanıklarıdır. Durgunluk kaydın kuralı gibi görünür; değişim istisna.",
        era: "Milyonluk zaman ölçeği",
      },
      {
        until: 0.27,
        title: "Eldredge ve Gould, 1972",
        text: "Niles Eldredge ve Stephen Jay Gould, 1972'de 'kesintili dengeler' makalesini yayımladı. İddia nettir: türleşme, uzun durgunluklara gömülü jeolojik açıdan ani olaylardır. Teori, Darwin'in aşamalı yaklaşımına bir alternatif olarak doğdu.",
        era: "1972 · teorinin ilanı",
      },
      {
        until: 0.4,
        title: "Ani Kriz: Göktaşı ve Volkan",
        text: "Kriz, dengeyi kırar: göktaşı çarpması, yoğun volkanizma, iklim çöküşü. 66 milyon yıl önceki Chixculub çarpması, türlerin yaklaşık dörtte üçünü yok edip boşalan ekolojik alanlar açtı. Krizler, evrimin hızlandırıcılarıdır.",
        era: "66 milyon yıl önce · K-Pg",
      },
      {
        until: 0.55,
        title: "Hızlı Türleşme Patlaması",
        text: "Boşalan nişlere küçük ve izole popülasyonlar hızla yayılır: seçilim baskısı altında yeni formlar birkaç yüz bin yılda belirir. Jeolojik ölçekte bu bir 'an'dır; fosil kaydında keskin bir basamak olarak görünür.",
        era: "Yüz binlerce yıl",
      },
      {
        until: 0.7,
        title: "Yeni Denge Yerleşiyor",
        text: "Yeni formlar ortama uyum sağlar ve denge yeniden kurulur: yeni morfolojiler, yeni uzun stazis dönemleri. Basamaklı fosil kaydı, bu ritmin taşa yazılmış imzasıdır. Her düz bölüm, bir türün milyonluk sessizliğidir.",
        era: "Yeni stazis dönemi",
      },
      {
        until: 0.86,
        title: "Fosil Kaydının Boşlukları",
        text: "Peki geçiş fosilleri neden azdır? Çünkü türleşme küçük ve izole popülasyonlarda, hızla ve dar alanlarda olur: fosilleşme şansı çok düşüktür. Kayıttaki boşluklar, eksikliğin değil hızlı geçişin beklenen izidir.",
        era: "Tafonomi · kaydın doğası",
      },
      {
        until: 1,
        title: "Aşamalı mı, Kesikli mi?",
        text: "Kesintili denge, Darwinci evrimi yıkmaz; hızını tartışır. Aşamalı değişim ve kesikli sıçramalar birlikte görülür: desen, türe ve zamana bağlıdır. Paleontoloji, kendi ölçeğinde evrimi okumayı öğrendi.",
        era: "Bugünün sentezi",
      },
    ],
    notes: [
      N(0.03, 0.12, "aynı kabuk, milyonlarca yıl", 0.72, 0.3),
      N(0.17, 0.26, "Eldredge + Gould, 1972", 0.26, 0.22),
      N(0.3, 0.39, "göktaşı + volkan = kriz", 0.5, 0.14),
      N(0.43, 0.53, "küçük izole popülasyonlar", 0.74, 0.4),
      N(0.58, 0.68, "yeni denge: yeni stazis", 0.26, 0.28),
      N(0.72, 0.82, "kesikli çizgi = kayıt boşluğu", 0.5, 0.7),
      N(0.89, 0.98, "iki desen de kayıtta var", 0.72, 0.28),
    ],
    cues: [
      C(0.001, "rumble", 0.4),
      C(0.14, "grow", 0.6),
      C(0.27, "grow", 0.5),
      C(0.34, "rumble", 0.8),
      C(0.4, "crash", 1),
      C(0.42, "explosion", 1),
      C(0.45, "rumble", 0.9),
      C(0.55, "explosion", 0.7),
      C(0.58, "grow", 0.8),
      C(0.7, "grow", 0.5),
      C(0.86, "crash", 0.4),
      C(0.9, "grow", 0.7),
    ],
    ticker: [
      "Eldredge ve Gould, 1972'de fosil kaydındaki ani değişimleri açıklayan modeli sundu.",
      "Teoriye göre türler ömürlerinin büyük bölümünü neredeyse hiç değişmeden geçirir: stazis.",
      "Türleşme genellikle ana popülasyondan kopan küçük ve izole gruplarda hızlanır.",
      "Trilobit ve foraminifer kayıtları uzun durgunluk ile ani türleşmeyi belgeler.",
      "66 milyon yıl önceki Chixculub çarpması, kayıtta dramatik bir 'kesinti' örneğidir.",
      "Fosilleşme son derece seçicidir: yumuşak dokulu canlıların kaydı neredeyse yoktur.",
      "Darwin'in 'mekik deliği' itirazı: geçiş formları nadir bulunur çünkü kayıt eksiktir.",
      "Kesintili denge gradualizmi yıkmaz; iki desen farklı ölçeklerde birlikte çalışır.",
    ],
  },
  {
    id: "endosimbiyoz",
    cat: "yasam",
    title: "Endosimbiyoz Teorisi",
    subtitle:
      "Bakteri yutan hücre, rakibi ortağa dönüştürdü: mitokondri ve kloroplastın ortak hikâyesi",
    duration: 120,
    color: "#fb7185",
    stages: [
      {
        until: 0.13,
        title: "Büyük Ana Hücre",
        text: "Yaklaşık 2 milyar yıl önce okyanusta büyük bir heterotrof hücre yaşıyordu: zar, çekirdek taslağı ve sindirim kabiliyeti. Ama enerjisi kısıtlıydı; oksijeni verimli kullanamıyordu. Çözüm, kendi içinde gizliydi: yutacağı bir misafirde.",
        era: "~2 milyar yıl önce",
      },
      {
        until: 0.26,
        title: "Küçük Bakteri Yaklaşıyor",
        text: "Küçük bir aerobik bakteri, oksijeni enerjiye çevirmede ustaydı. Süzülerek ana hücreye yaklaştı; iki hücrenin bu karşılaşması, karmaşık yaşamın kapısını aralayacaktı.",
        era: "~2 milyar yıl önce",
      },
      {
        until: 0.39,
        title: "Yutma: Zar Kıvrımı",
        text: "Ana hücre, zarını kıvırarak bakteriyi içine aldı: fagositoz. Bu, milyarlarca yıllık bir yeme ritüelinin başlangıcıydı — ama bu kez sonuç farklı oldu. Misafir, öğle yemeği olmaktan kurtulacaktı.",
        era: "Fagositoz anı",
      },
      {
        until: 0.52,
        title: "Sindirilmedi: Ortaklık",
        text: "Bakteri sindirilmedi: hücre ona barınak verdi, o hücreye hazır ATP yaydı. İki taraflı fayda, ortaklığı kalıcı kıldı. Zamanla iki genom birbirine o kadar bağımlı oldu ki ayrılmak artık imkânsızdı.",
        era: "Ortaklaşmanın kuruluşu",
      },
      {
        until: 0.67,
        title: "Bakteriden Mitokondriye",
        text: "Ortak, organele dönüştü: küçüldü, zarları özelleşti, iç zar kıvrımlarla kristaları kurdu: mitokondri. Hücre, oksijenli solunumla enerjisini katladı; karmaşık (ökaryot) yaşamın yolu açıldı.",
        era: "~1,8 milyar yıl önce",
      },
      {
        until: 0.83,
        title: "Bitki Hattı: Kloroplast",
        text: "Aynı senaryo ikinci kez oynandı: bir siyanobakteri yutuldu ama sindirilmedi — kloroplast oldu. Işığı şekerleştirdi; bitkilerin atası, iki endosimbiyozun ürünü olarak doğdu. Fotosentez, gökyüzüne oksijen pompalamaya başladı.",
        era: "~1,5 milyar yıl önce",
      },
      {
        until: 1,
        title: "Bugünün Hücresi",
        text: "Kanıtlar bugün de yaşıyor: mitokondri ve kloroplast kendi dairesel DNA'sını, kendi ribozomunu taşır; kendini bölünerek çoğaltır. Lynn Margulis (1967) bu fikri bilim gündemine taşıdı; önce dirençle karşılandı, bugün ders kitaplarının temelidir.",
        era: "1967 · Margulis",
      },
    ],
    notes: [
      N(0.03, 0.11, "ana hücre: büyük heterotrof", 0.72, 0.26),
      N(0.16, 0.24, "aerobik bakteri süzülüyor", 0.26, 0.34),
      N(0.28, 0.37, "fagositoz: zar kıvrımı", 0.7, 0.2),
      N(0.42, 0.5, "ATP: enerji takası", 0.28, 0.42),
      N(0.56, 0.65, "mitokondri: iç kristalar", 0.72, 0.46),
      N(0.72, 0.81, "kloroplast: ışığı şekerleştirir", 0.26, 0.24),
      N(0.87, 0.96, "kendi DNA'sı: halka kromozom", 0.7, 0.32),
    ],
    cues: [
      C(0.001, "cell", 0.4),
      C(0.13, "cell", 0.6),
      C(0.26, "cell", 0.5),
      C(0.39, "merge", 0.9),
      C(0.42, "grow", 0.6),
      C(0.52, "shimmer", 0.7),
      C(0.67, "merge", 0.8),
      C(0.7, "grow", 0.7),
      C(0.83, "shimmer", 0.8),
      C(0.95, "shimmer", 0.5),
    ],
    ticker: [
      "Lynn Margulis, 1967'de endosimbiyoz makalesini yayımladı; fikir önce alay konusu oldu.",
      "Mitokondri ve kloroplastın dairesel DNA'sı bakteri kromozomuna benzer: akrabalık belgesi.",
      "Her iki organel de kendi ribozomlarıyla bölünerek çoğalır: hücre bölünmesinden bağımsızdır.",
      "Mitokondriyal DNA anneden geçer: insan soyağacı 'mitokondriyal Eva'ya kadar izlenir.",
      "Mitokondri, hücrenin ATP üretiminin büyük bölümünü karşılar: enerji santralidir.",
      "Kloroplast ışığı şekerleştirir: bitkiler, üst üste iki endosimbiyozun ürünüdür.",
      "Organellerin çift zarı vardır: dış zar yutma vaküolünden, iç zar bakteriden kalma.",
      "Rickettsia gibi modern bakteriler, mitokondrinin en yakın yaşayan akrabalarıdır.",
    ],
  },
  {
    id: "notral-evrim",
    cat: "yasam",
    title: "Nötral Evrim Teorisi",
    subtitle:
      "Seçilimin görmediği sessiz mutasyonlar — rastgele sürüklenme ve moleküler saatin zaferi",
    duration: 100,
    color: "#94a3b8",
    stages: [
      {
        until: 0.15,
        title: "Moleküler Saat",
        text: "Proteinler türler arasında düzenli bir hızla farklılaşır: Zuckerkandl ve Pauling (1962-65) buna 'moleküler saat' dedi. Mutasyonlar kabaca sabit bir ritimle birikiyorsa, iki tür arasındaki fark sayısı geçen zamanı ölçer. DNA, kendi kronometresini taşıyordu.",
        era: "1962-65 · saat fikri",
      },
      {
        until: 0.3,
        title: "Nötr Mutasyonlar: Sessiz Çoğunluk",
        text: "Kimura'nın (1968) matematiği şunu gösterdi: mutasyonların büyük bölümü işlevsizdir — nötrdür. Seçilim onları görmez: ne eler, ne ödüllendirir. Onlar, evrimin sessiz arka plan gürültüsüdür.",
        era: "1968 · Kimura",
      },
      {
        until: 0.44,
        title: "Birikim: Kadran Doluyor",
        text: "Nötr mutasyonlar silinmediği için birikir: saat ilerledikçe kadran doluşur. DNA'daki farklar, geçen milyon yılların doğrudan kaydıdır. Kayıt tutmak için fosile gerek yoktur; dizi yeter.",
        era: "Birikim ilkesi",
      },
      {
        until: 0.58,
        title: "İki Soy Ayrılıyor",
        text: "İki soy dallandığında saat her dalda bağımsız işler: her dal kendi mutasyonlarını biriktirir. Dallanma anından bu yana geçen süre, iki dal arasındaki farka yazılır. Soyağacı, DNA içinde okunur.",
        era: "Filogenetik",
      },
      {
        until: 0.72,
        title: "Kaç Mutasyon, O Kadar Zaman",
        text: "İki tür arasındaki fark sayısı kabaca geçen süreyle orantılıdır; ölçek, fosil kaydıyla kalibre edilir. Böylece moleküler biyoloji, paleontolojinin yanına ikinci bir kronometre koyar. İki saat birbirini denetler.",
        era: "Kalibrasyon",
      },
      {
        until: 0.86,
        title: "Genetik Sürüklenme: Kimura",
        text: "Frekanslar, seçilim olmadığında rastgele yürür: genetik sürüklenme. Küçük popülasyonlarda şans, seçilimi bile alt edebilir. Kimura, moleküler çeşitliliğin büyük bölümünü bu sessiz yürüyüşe bağladı: nötr teori.",
        era: "1968 · nötr teori",
      },
      {
        until: 1,
        title: "Modern Genetik Kanıt",
        text: "Kanıtlar günlük işinde: insan ve şempanze genomu yaklaşık %98,8 aynıdır; sitokrom c proteini insan ve mayada bile büyük ölçüde aynıdır. Moleküler saat bugün soyağaçlarını çizen ana araçtır.",
        era: "Bugün · genomik çağ",
      },
    ],
    notes: [
      N(0.03, 0.13, "her tik = bir mutasyon", 0.26, 0.22),
      N(0.17, 0.28, "nötr: seçilim görmez", 0.74, 0.3),
      N(0.31, 0.42, "mutasyonlar birikiyor", 0.26, 0.4),
      N(0.46, 0.56, "dallanma: iki soy", 0.72, 0.24),
      N(0.6, 0.7, "fark sayısı = geçen süre", 0.28, 0.26),
      N(0.74, 0.84, "Kimura 1968: sürüklenme", 0.72, 0.42),
      N(0.89, 0.98, "sitokrom c: evrensel saat", 0.5, 0.18),
    ],
    cues: [
      C(0.001, "shimmer", 0.4),
      C(0.15, "pop", 0.6),
      C(0.3, "shimmer", 0.7),
      C(0.44, "pop", 0.5),
      C(0.58, "chime", 0.6),
      C(0.72, "grow", 0.7),
      C(0.79, "pop", 0.4),
      C(0.86, "shimmer", 0.8),
      C(0.95, "chime", 0.7),
    ],
    ticker: [
      "Zuckerkandl ve Pauling, 1962-65 arasında 'moleküler saat' fikrini ortaya koydu.",
      "Kimura (1968), protein ve DNA varyasyonunun büyük bölümünün seçilimsiz olduğunu savundu.",
      "İnsan ile şempanze genomu yaklaşık %98,8 aynıdır: soy ~6-7 milyon yıl önce ayrıldı.",
      "Sitokrom c proteini insan ve maya arasında bile büyük ölçüde aynıdır: saat yavaş işler.",
      "Nötr teori seçilimi yıkmaz: faydalı değişimler seçilir, çoğu mutasyon ise sessizdir.",
      "Genetik sürüklenme küçük popülasyonlarda güçlüdür: ada türleri hızla sapar.",
      "Mitokondriyal DNA ve Y kromozomu, soyağaçlarını doğrudan saymak için kullanılır.",
      "Saat kusursuz değildir: hızı türe, gene ve zamana göre değişir; fosille kalibre edilir.",
    ],
  },
  {
    id: "lamarckizm",
    cat: "yasam",
    title: "Lamarckizm (Kazanılmış Karakterlerin Aktarımı)",
    subtitle:
      "Kazanılmış özelliklerin kalıtımı — zürafa boyunları, Weismann bariyeri ve epigenetik köprü",
    duration: 115,
    color: "#eab308",
    stages: [
      {
        until: 0.13,
        title: "Zürafa: Kısa Boyun",
        text: "1809'da Jean-Baptiste Lamarck, Philosophie Zoologique'de türlerin değişebildiğini savundu. Zürafa örneği ünlüdür: yapraklara ulaşan birey, ihtiyacı yönünde değişir. Bu, evrimsel düşüncenin ilk büyük bilimsel çerçevesiydi.",
        era: "1809 · Philosophie Zoologique",
      },
      {
        until: 0.26,
        title: "Uzanma: Kullanım Yasası",
        text: "Lamarck'ın yasası: kullanım organı geliştirir, kullanmama köretir. Boyun uzar, çünkü uzatanın ihtiyacı vardır. Kazanılan özellik, bedenin kendi yazdığı bir talimattır — çevre, organları şekillendirir.",
        era: "Kullanım ve kullanmama",
      },
      {
        until: 0.4,
        title: "Kazanım Yavruya: Lamarck'ın İddiası",
        text: "İddia cesurdu: kazanılan özellik döle aktarılır. Her nesil, ebeveyninin kazandığını devralır ve biraz daha ekler. Boyunlar nesilden nesile uzar: Lamarck'a göre evrim, çaba ve mirastır.",
        era: "Kalıtsal kazanım iddiası",
      },
      {
        until: 0.55,
        title: "Weismann Bariyeri",
        text: "August Weismann (1885-92) kalıtımı iki hatta ayırdı: vücudu kuran somatik hücreler ve döl veren germ hattı. Aralarında tek yönlü bir bariyer vardır: somatik hücrelerin kazanımları germ hattına asla geçemez.",
        era: "1885-92 · Weismann",
      },
      {
        until: 0.7,
        title: "Fare Deneyi: Test Ediliyor",
        text: "Weismann testi kendi yaptı: farelerin kuyruklarını kuşaklar boyunca kesti. Yavrular kuşaklarca kuyruklu doğdu: bedenin travması kalıtım yazmamıştır. Bariyer, laboratuvarda doğrulandı; Lamarck'ın mekanizması çöktü.",
        era: "1888-91 · deney",
      },
      {
        until: 0.85,
        title: "Epigenetik: Küçük Köprü",
        text: "Modern düzeltme: DNA'nın çevresindeki metil gibi etiketler, çevreye yanıt olarak açılıp kapanabilir ve bir-iki nesle sızabilir. 1944 Hollanda açlık kışı, kıtlığın torunların gen etiketlenmesinde iz bırakabildiğini gösterdi. Ama etiketler çoğunlukla silinir: istisna var, kural değişmedi.",
        era: "Bugün · epigenetik",
      },
      {
        until: 1,
        title: "Bilim Tarihi Dersi",
        text: "Sonuç dengeli: Lamarck'ın mekanizması yanlıştı, sorusu doğrudu. Darwin bile pangenesis kuramında kazanım geçişine kısmen yer verdi. Bilim, yanlış cevaplarla da ilerler: doğru soru, doğru mekanizmayı davet eder.",
        era: "Bugün · bilim tarihine bakış",
      },
    ],
    notes: [
      N(0.03, 0.11, "Lamarck, 1809", 0.26, 0.2),
      N(0.16, 0.24, "yapraklar yukarıda", 0.74, 0.28),
      N(0.3, 0.38, "her nesil biraz daha uzun", 0.26, 0.34),
      N(0.44, 0.53, "somatik ↔ germ: duvar", 0.72, 0.24),
      N(0.57, 0.66, "yavru yine kuyruklu doğdu", 0.26, 0.3),
      N(0.72, 0.81, "metil etiketleri: geçici", 0.72, 0.3),
      N(0.88, 0.97, "soru doğru, mekanizma yanlış", 0.5, 0.16),
    ],
    cues: [
      C(0.001, "grow", 0.4),
      C(0.13, "pop", 0.5),
      C(0.26, "grow", 0.7),
      C(0.4, "grow", 0.8),
      C(0.55, "glitch", 0.9),
      C(0.7, "pop", 0.5),
      C(0.85, "grow", 0.6),
      C(0.9, "chime", 0.6),
      C(0.97, "chime", 0.7),
    ],
    ticker: [
      "Lamarck, 1809'da türlerin değişmezliğini sorgulayan ilk büyük bilimsel çerçeveyi kurdu.",
      "Kullanım ve kullanmama yasası: kullanılan organ gelişir, kullanılmayan körelir.",
      "Weismann (1885-92), somatik ve germ hattını ayırdı: kazanım döle geçemez.",
      "Weismann, farelerin kuyruklarını 22 kuşak kesti; yavrular hep kuyruklu doğdu.",
      "1944 Hollanda açlık kışı, çevrenin gen etiketlenmesine dokunabildiğini gösterdi.",
      "Epigenetik etiketler çoğunlukla bir-iki nesilde silinir: istisna var, kural değişmedi.",
      "Darwin bile pangenesis kuramında kazanım geçişine kısmen yer verdi.",
      "Bakterilerde yatay gen aktarımı gerçek, sınırlı bir 'neo-Lamarckçı' örnektir.",
      "Bugün evrim, DNA değişimi + seçilimle açıklanır; Lamarck doğru soruyu sormuştu.",
    ],
  },
];
