import type { TheoryDef } from "../theories";
import { N, C } from "./helpers";

/**
 * Fermi paradoksu ve gelecek teorileri — 5 uzun animasyon tanımı.
 *
 * Bu paketteki teoriler "gelecek" kategorisindedir: Büyük Sessizlik,
 * Büyük Filtre, Kardaşev Ölçeği, Nadir Dünya ve Kara Orman. Tüm metinler
 * gerçek bilimsel kaynaklara dayanır (Fermi 1950, Drake 1961, Hart 1975,
 * Kardaşev 1964, Dyson 1960, Ward & Brownlee 2000, Liu Cixin 2008,
 * Arecibo mesajı 1974).
 */
export const FERMI_THEORIES: TheoryDef[] = [
  /* ------------------------- 1) Fermi Paradoksu ------------------------- */
  {
    id: "fermi-paradoksu",
    title: "Fermi Paradoksu ve Çözüm Teorileri",
    subtitle:
      "Yüz milyarlarca yıldıza rağmen neden hiçbir sinyalin duyulmadığına dair büyük gizem",
    duration: 95,
    color: "#67e8f9",
    cat: "gelecek",
    stages: [
      {
        until: 0.12,
        title: "1950: Los Alamos'ta Bir Soru",
        era: "1950 · Manhattan Projesi",
        text: "Enrico Fermi, Los Alamos'taki bir öğle yemeği sohbetinde aniden 'Peki onlar nerede?' diye sordu. Galakside yüz milyarlarca yıldız ve milyarlarca yıl varken uzaylı uygarlıkların izleri her yerde olmalıydı. Bu basit soru, varoluşsal bir çelişkiye dönüştü.",
      },
      {
        until: 0.28,
        title: "Galaksi Neredeyse Bomboş",
        era: "Fermi-Hart argümanı",
        text: "Akıllı yaşam yaygın olsaydı, üssel büyümeyle galaksiyi yalnızca birkaç milyon yılda kolonileştirirdi. Michael Hart 1975'te bu sürenin Evren'in yaşına göre anlık olduğunu gösterdi. Oysa gökyüzünde ne gemiler ne mega yapılar ne de sinyaller vardır.",
      },
      {
        until: 0.44,
        title: "Drake Denklemi: Sayıları Bölmek",
        era: "1961 · Green Bank",
        text: "Frank Drake 1961'de galaksideki iletişim kurabilir uygarlık sayısını yedi çarpana böldü. R*, fp, ne, fl, fi, fc ve L: yıldızlardan sinyal süresine uzanan bir zincir. Denklem bir tahmin makinesi değil, tartışmayı yapılandıran pusuladır.",
      },
      {
        until: 0.6,
        title: "Çözüm Kataları",
        era: "Dört açıklama ailesi",
        text: "Bilim insanları sessizliği dört ailede açıklamaya çalıştı. Ya karmaşık yaşam gerçekten nadirdir, ya mesafeler geçilmezdir, ya uygarlıklar kendi kendini yok eder, ya da herkes bilinçli olarak susar. Her açıklama, evren hakkında farklı bir kehanet taşır.",
      },
      {
        until: 0.76,
        title: "Kulaklar: SETI ve Radyo Dinleme",
        era: "1960 · Ozma Projesi",
        text: "Frank Drake 1960'ta Ozma Projesiyle Tau Ceti ve Epsilon Eridani'yi dinledi. 1977'de Big Ear teleskobu 72 saniyelik şaşırtıcı 'Wow!' sinyalini kaydetti ama sinyal bir daha hiç duyulmadı. Bugün Breakthrough Listen milyonlarca yıldızı tarıyor.",
      },
      {
        until: 0.9,
        title: "Büyük Sessizlik",
        era: "Gözlenen gerçek",
        text: "Aradan geçen onlarca yılda doğrulanmış tek bir dünya dışı sinyal yok. Sessizlik bir veridir: ya uygarlıklar çok kısa yaşıyor, ya çok uzakta, ya da görünmez olmayı seçiyor. Her seçenek insanlık için öğretici bir aynadır.",
      },
      {
        until: 1,
        title: "Soru Hâlâ Açık",
        era: "21. yüzyıl",
        text: "Fermi'nin sorusu 75 yıldır cevapsız duruyor; belki de cevap, sorunun kendisinden daha sarsıcıdır. Ötegezegen devrimi yaşanabilir gezegen sayısını büyüttü ama hiçbirinde yaşam izi bulunamadı. Paradoks canlılığını koruyor ve bizi dinlemeye, düşünmeye çağırıyor.",
      },
    ],
    notes: [
      N(0.02, 0.11, "Fermi: 'Onlar nerede?'", 0.5, 0.18),
      N(0.04, 0.11, "Soru yemek masasında soruldu", 0.24, 0.74),
      N(0.14, 0.26, "Kolonizasyon ~10 milyon yıl", 0.7, 0.22),
      N(0.17, 0.26, "Hart 1975: argüman sağlam", 0.28, 0.3),
      N(0.31, 0.42, "L: uygarlığın yayın süresi", 0.26, 0.68),
      N(0.47, 0.58, "Nadir, mesafe, yıkım, sessizlik", 0.5, 0.18),
      N(0.62, 0.74, "Wow! sinyali: 72 saniye", 0.26, 0.28),
      N(0.65, 0.74, "Listen: 1 milyon yıldız hedefi", 0.72, 0.4),
      N(0.8, 0.88, "Sessizlik de bir veridir", 0.5, 0.82),
      N(0.91, 0.99, "Cevap: henüz yok", 0.5, 0.16),
    ],
    cues: [
      C(0.005, "bell", 0.5),
      C(0.04, "shimmer", 0.4),
      C(0.12, "whoosh", 0.8),
      C(0.16, "shimmer", 0.5),
      C(0.28, "chime", 0.6),
      C(0.31, "shimmer", 0.45),
      C(0.44, "bell", 0.8),
      C(0.5, "shimmer", 0.4),
      C(0.6, "whoosh", 0.6),
      C(0.66, "wind", 0.5),
      C(0.76, "bell", 0.7),
      C(0.9, "wind", 0.8),
      C(0.95, "chime", 0.5),
    ],
    ticker: [
      "Enrico Fermi ünlü sorusunu 1950 yazında, Los Alamos Ulusal Laboratuvarı'nın öğle yemeği sohbetinde sordu.",
      "Fermi paradoksu: galakside yüz milyarlarca yıldız varken hiçbir yabancı uygarlık izine rastlanmaması çelişkisidir.",
      "Michael Hart 1975'te yazdığı makaleyle Fermi sorusunu, kolonizasyon süresi hesabıyla keskin bir argümana dönüştürdü.",
      "Drake denklemi 1961 Green Bank toplantısı için hazırlandı; amaç sayı vermek değil, tartışmayı çarpanlara bölmekti.",
      "Frank Drake'in Ozma Projesi 1960'ta Tau Ceti ve Epsilon Eridani yıldızlarını dinleyerek ilk modern SETI deneyi oldu.",
      "Wow! sinyali 15 Ağustos 1977'de Big Ear radyo teleskobunda kaydedildi; 72 saniye sürdü ve bir daha asla tekrarlanmadı.",
      "Breakthrough Listen programı, en yakın bir milyon yıldızı radyo ve ışık dalgalarında sinyal açısından taramayı hedefliyor.",
      "Hesaplara göre nispeten yavaş gemilerle bile galaksi kolonizasyonu Evren yaşının küçük bir kesrinde tamamlanabilirdi.",
      "Günümüze dek 5000'den fazla ötegezegen doğrulandı; kimi yaşanabilir bölgede ama hiçbirinde yaşam izi saptanamadı.",
      "Olası çözümler dört aileye ayrılır: yaşam nadirdir, mesafeler çok büyüktür, uygarlıklar kısa ömürlüdür veya sessizliği seçer.",
    ],
  },

  /* ------------------------- 2) Büyük Filtre ---------------------------- */
  {
    id: "buyuk-filtre",
    title: "Büyük Filtre (Great Filter) Hipotezi",
    subtitle:
      "Yaşamın yolundaki dev engel: insanlık onu geride bıraktı mı, yoksa önde mi",
    duration: 110,
    color: "#f87171",
    cat: "gelecek",
    stages: [
      {
        until: 0.13,
        title: "Yaşam Merdiveni",
        era: "Kimyadan uygarlığa",
        text: "Cansız kimyadan galaksiyi kolonileştiren bir uygarlığa giden yol, üst üste inanılmaz sıçramalar gerektirir. Kararlı moleküller, ilk hücre, ökaryotlar, çok hücrelilik, zeka ve teknoloji: her basamak ayrı bir mucize. Robin Hanson bu zincirdeki engellere filtre adını verdi.",
      },
      {
        until: 0.27,
        title: "Geride Kalan Barikatlar",
        era: "Dünya'nın geçmişi",
        text: "Dünya'da yaşam bir kez başladı ve her basamağı geçmeyi başardı; abiyogenez görece hızlı oldu. Ama ökaryot hücre iki milyar yıldan fazla bekledi ve yalnızca bir kez ortaya çıktı. Geçmiş filtreler, bugünkü varlığımızı açıklıyor.",
      },
      {
        until: 0.42,
        title: "Büyük Filtre Duvarı",
        era: "Hipotezin kalbi",
        text: "Hanson'a göre zincirde en az bir basamak istatistiksel olarak neredeyse imkânsızdır. Bu engel geride kaldıysa evren, bizim gibi nadir zihinlerle dolu boş bir salondur. Eğer öndeyse, insanlığın önünde bekleyen bir yıkım eşiği vardır.",
      },
      {
        until: 0.56,
        title: "Senaryo A: Biz Nadiriz",
        era: "İyimser okuma",
        text: "Filtre geride kaldıysa, galakside bizden önce teknolojik bir uygarlık doğmadı demektir. Dünya bu durumda milyarlarca gezegen arasındaki nadir bir istisnadır. Fermi'nin sessiz sorusunun yanıtı, bizim varlığımızın kendisidir.",
      },
      {
        until: 0.7,
        title: "Senaryo B: Duvar Öndedir",
        era: "Kötümser okuma",
        text: "Filtre öndeyse hiçbir uygarlık belirli bir eşiği aşamaz; nükleer savaş, biyoteknoloji kazası ya da yapay zekâ aday sayılır. Üstelik diğer uygarlıklar da aynı duvarda tıkanır ve bu, sessizliği açıklar. Kötümser okuma, Fermi paradoksunu da çözer.",
      },
      {
        until: 0.85,
        title: "Hanson'ın Kısa Flaşları",
        era: "1945'ten bu yana",
        text: "Hanson, nükleer silahların 1945'te başlayan kısa ama çarpıcı geçmişini uyarı işareti sayar. İnsanlık, yıkım gücünü uzaya gidecek teknolojiden önce keşfetti. Filtre tartışması, kısa vadede bir hayatta kalma sorununa dönüşür.",
      },
      {
        until: 1,
        title: "Yeşil Geçit: Aşılabilir mi",
        era: "Umut senaryosu",
        text: "Filtre bir doğa kanunu değil, bilinmeyen bir olasılıktır; keşif onun yerini değiştirebilir. Dünya dışı yaşam izi ya da bir sinyal, filtrenin geride mi önde mi olduğunu gösterir. Bilinçli keşif, galaksinin kapısını aralayabilir.",
      },
    ],
    notes: [
      N(0.02, 0.11, "Robin Hanson, 1998", 0.28, 0.2),
      N(0.02, 0.11, "Zincirde en az 8 basamak", 0.72, 0.3),
      N(0.14, 0.25, "Abiyogenez hızlıydı", 0.3, 0.24),
      N(0.16, 0.25, "Ökaryot: 2 milyar yıl bekleme", 0.7, 0.4),
      N(0.29, 0.4, "En az bir adım neredeyse imkânsız", 0.5, 0.16),
      N(0.44, 0.54, "Filtre gerideyse: biz nadiriz", 0.28, 0.22),
      N(0.44, 0.54, "Öndeyse: yıkım eşikte", 0.72, 0.4),
      N(0.58, 0.68, "Nükleer çağ: 1945'ten beri", 0.3, 0.26),
      N(0.6, 0.68, "AI ve biyotek: yeni adaylar", 0.72, 0.42),
      N(0.87, 0.98, "Keşif filtrenin yerini gösterir", 0.5, 0.82),
    ],
    cues: [
      C(0.005, "chime", 0.4),
      C(0.05, "grow", 0.5),
      C(0.13, "whoosh", 0.6),
      C(0.2, "pop", 0.5),
      C(0.27, "crack", 0.7),
      C(0.3, "crack", 0.5),
      C(0.42, "boom", 0.9),
      C(0.5, "shimmer", 0.5),
      C(0.56, "grow", 0.6),
      C(0.63, "zap", 0.5),
      C(0.7, "explosion", 0.8),
      C(0.85, "rumble", 0.6),
      C(0.9, "chime", 0.6),
      C(0.96, "grow", 0.7),
    ],
    ticker: [
      "Büyük Filtre kavramını ekonomist Robin Hanson, 1998 tarihli 'The Great Filter' makalesiyle ortaya koydu.",
      "Filtre, cansız maddeden galaksiyi kolonileştiren uygarlığa giden yoldaki inanılmaz zor bir geçiş adımıdır.",
      "Hanson'ın aday basamakları arasında doğru yıldız, kimya, abiyogenez, ökaryot, cinsiyetli üreme ve teknoloji var.",
      "Ökaryot hücre, Dünya tarihinde yalnızca bir kez doğdu; bu tek seferlik olay güçlü bir filtre sinyalidir.",
      "Filtre geride kaldıysa evren neredeyse boştur ve insanlık galaksinin en değerli örneği konumundadır.",
      "Filtre öndeyse her uygarlık aynı eşiği aşamaz; bu durum Fermi sessizliğini de açıklar.",
      "Nükleer denemeler 1945'te başladı; Hanson bu hızlı yıkım gücünü filtrenin öndeliğine delil sayar.",
      "K-Pg yok oluşu türlerin yaklaşık yüzde 75'ini silmişti; dış felaketler filtre adayı olarak tartışılır.",
      "Geçilen filtrelerin kanıtı: Dünya'da yaşam kısa sürede başladı ama teknolojik zihin milyarlarca yıl sonra geldi.",
      "Bilim insanları Mars ve Europa'da yaşam izi arayışı, filtrenin geçmişte mi önde mi olduğunu test etmeye çalışıyor.",
    ],
  },

  /* ------------------------- 3) Kardaşev Ölçeği ------------------------- */
  {
    id: "kardasev-olcegi",
    title: "Kardaşev Ölçeği Modeli",
    subtitle:
      "Uygarlıkları enerji güçlerine göre sınıflandıran gezegen, yıldız ve galaksi basamakları",
    duration: 115,
    color: "#fbbf24",
    cat: "gelecek",
    stages: [
      {
        until: 0.16,
        title: "Tip I: Gezegen Uygarlığı",
        era: "1964 · Kardaşev'in tanımı",
        text: "Nikolay Kardaşev 1964'te uygarlıkları yönetebildikleri enerjiyle sınıflandırdı. Tip I, kendi gezegeninin tüm kaynaklarını, kabaca 10 üzeri 16 watt'ı kullanır. İnsanlık bu eşikte henüz tip 0,73 civarındadır.",
      },
      {
        until: 0.34,
        title: "Tip II: Dyson İnşaatı",
        era: "Freeman Dyson, 1960",
        text: "Tip II uygarlık yıldızının bütünü toplar: Güneş saniyede yaklaşık 3,8 × 10^26 watt ışır. Freeman Dyson 1960'ta bunun için yörüngedeki milyarlarca toplayıcıdan oluşan bir ağ önerdi. İnşaat, iskele halkalarından başlayıp yıldızı tam saran bir ağa dönüşür.",
      },
      {
        until: 0.52,
        title: "Tip II: Yıldız Enerjisi",
        era: "Yıldız madenciliği",
        text: "Kaplı yıldız artık boşa ışık saçmaz; tüm çıktı sanayiye, hesaplamaya ve yıldız iticiliğine akar. Böyle bir uygarlık, yıldızını taşımaya ve galaksi içinde göç etmeye bile güç yetirebilir. Dışarıdan bakıldığında yıldız kızılötesi olarak görünür.",
      },
      {
        until: 0.7,
        title: "Tip III: Galaktik Uygarlık",
        era: "10^36 watt ölçeği",
        text: "Tip III, galaksinin yüz milyarlarca yıldızının enerjisini toplar; kollar tek tek ışıklarla dolar. Kardaşev'e göre böyle bir uygarlık bizim için tanrısal görünebilir. Ölçek bu üç basamakla sınırlı değildir; evrenin ötesine taşınabilir.",
      },
      {
        until: 0.85,
        title: "Enerji Merdiveni",
        era: "Logaritmik ölçek",
        text: "Basamaklar arasında devasa farklar vardır: Tip I'den Tip II'ye yüz milyar kat, Tip II'den Tip III'e yine yüz milyar kat artış gerekir. Carl Sagan ölçeği sürekli bir formüle bağladı: K, gücün 10 tabanında logaritmasına bağlıdır.",
      },
      {
        until: 1,
        title: "Bizim Yerimiz: Tip 0,73",
        era: "2020'ler",
        text: "İnsanlık bugün yaklaşık 2 × 10^13 watt tüketiyor; Sagan formülü bu değere 0,73 tip notu verir. Ölçeğin dibinde olmamız, yolun ne kadar uzun olduğunu gösterir. Michio Kaku'ya göre Tip I eşiğine birkaç yüzyıl vardır.",
      },
    ],
    notes: [
      N(0.02, 0.1, "Nikolay Kardaşev, 1964", 0.26, 0.2),
      N(0.04, 0.14, "Tip I ≈ 10^16 watt", 0.72, 0.28),
      N(0.18, 0.32, "Güneş: 3,8 × 10^26 watt", 0.26, 0.24),
      N(0.2, 0.32, "Dyson: toplayıcı bulutu", 0.72, 0.4),
      N(0.36, 0.5, "Kızılötesi imza görünür", 0.28, 0.26),
      N(0.38, 0.5, "Yıldız taşıma hayali bile var", 0.72, 0.42),
      N(0.54, 0.68, "Kollar ışıklarla dolar", 0.28, 0.22),
      N(0.56, 0.68, "Fermi'nin sessizliği sorulur", 0.72, 0.4),
      N(0.72, 0.82, "K = log10(P) formülü", 0.5, 0.2),
      N(0.87, 0.98, "İnsanlık: tip 0,73", 0.5, 0.8),
    ],
    cues: [
      C(0.005, "engine", 0.5),
      C(0.06, "grow", 0.6),
      C(0.16, "engine", 0.7),
      C(0.24, "shimmer", 0.5),
      C(0.34, "starform", 0.8),
      C(0.42, "shimmer", 0.55),
      C(0.52, "engine", 0.8),
      C(0.6, "shimmer", 0.5),
      C(0.7, "starform", 0.9),
      C(0.78, "chime", 0.6),
      C(0.85, "grow", 0.6),
      C(0.92, "bell", 0.7),
    ],
    ticker: [
      "Sovyet astronot Nikolay Kardaşev, ölçeğini 1964'te kuasar ve radyo kaynaklarını sınıflamak için önerdi.",
      "Tip I uygarlık, gezegeninin tüm enerji akışını, yaklaşık 10^16 watt gücü yönetebilir.",
      "Tip II uygarlık yıldızının tüm çıktısını toplar; Güneş saniyede yaklaşık 3,8 × 10^26 watt ışır.",
      "Freeman Dyson 1960'taki makalesinde yıldızı saran toplayıcı bulutun kızılötesi izini aramayı önerdi.",
      "Dyson küresi fikri, Olaf Stapledon'un 1937 romanı Yıldız Yaratıcı'dan bilim dünyasına taşındı.",
      "Tip III uygarlık galaksideki yüz milyarlarca yıldızı sömürür; ölçek 10^36 watt seviyesine çıkar.",
      "Carl Sagan ölçeğe sürekli formül ekledi: K = (log10 P - 6) / 10, watt cinsinden güçle çalışır.",
      "İnsanlık 2023 itibarıyla yaklaşık 2 × 10^13 watt tüketiyor; Sagan formülüne göre tip 0,73'tür.",
      "Dyson küresi katı bir kabuk değil, yörüngede dönen milyarlarca toplayıcıdan oluşan bir ağ olmalıdır.",
      "Kızılötesi astronomi, Dyson yapılarının ısı imzasını uzak yıldızlarda aramak için kullanılabilir.",
    ],
  },

  /* ------------------------- 4) Nadir Dünya ----------------------------- */
  {
    id: "nadir-dunya",
    title: "Nadir Dünya (Rare Earth) Hipotezi",
    subtitle:
      "Karmaşık yaşamın var olması için üst üste gelmesi gereken beş kozmik şans",
    duration: 125,
    color: "#4ade80",
    cat: "gelecek",
    stages: [
      {
        until: 0.11,
        title: "Koşul 1: Sakin Bir Yıldız",
        era: "G2V · ana kol",
        text: "Karmaşık yaşam, on milyar yıllık sabit ışınım ister; Güneş bir G tipi yıldız olarak bunu sağlar. Çok sıcak yıldızlar kısa yaşar, çok soğuk olanlar gezegeni kilitler. Sakin bir yıldız, ilk zorunlu koşuldur.",
      },
      {
        until: 0.24,
        title: "Koşul 2: Jüpiter Kalkanı",
        era: "Dış gezegen güvencesi",
        text: "Dev Jüpiter, gelen kuyruklu yıldızları ve asteroitleri çekip yutar; 1994'te Shoemaker-Levy 9 çarpması bunu canlı gösterdi. Kalkan yoksa büyük çarpmalar karmaşık hayatı sürekli sıfırlar. Gaz devleri, iç sistemin nöbetçileridir.",
      },
      {
        until: 0.38,
        title: "Koşul 3: Büyük Ay",
        era: "Dönüş dolabı dengesi",
        text: "Ay, Dünya'nın eksen eğikliğini kaotikleşmeden yumuşak bir aralıkta tutar; eğiklik salınımları iklimi korur. Gelgit çizgileri kıyı kuşaklarını besledi ve erken kimyanın laboratuvarı oldu. Aysız bir Dünya, Mars gibi savrulabilirdi.",
      },
      {
        until: 0.53,
        title: "Koşul 4: Tektonik ve Manyetosfer",
        era: "Gezegenin iç motoru",
        text: "Levha tektoniği karbon-silikat döngüsünü işleterek iklimi milyarlarca yıl dengeler. Sıvı demir çekirdeğin ürettiği manyetosfer, güneş rüzgârını saptırıp atmosferi korur. Venüs bunu çökertti, Mars onu çoktan kaybetti.",
      },
      {
        until: 0.67,
        title: "Koşul 5: Galaktik Yaşanabilir Bölge",
        era: "Yıldızlar arası mahalle",
        text: "Galaksi merkezine yakın süpernova ve radyasyon yoğundur, kenarda ise metal yoksulluğu vardır. Güneş, bu iki uç arasında güvenli bir halkada döner. Yaşanabilirlik, gezegenin kendisi kadar galaktik adrese de bağlıdır.",
      },
      {
        until: 0.78,
        title: "Beş Parça Bir Arada",
        era: "Nadir birleşim",
        text: "Sakin yıldız, dev kalkan, büyük ay, canlı iç motor ve güvenli mahalle: beş koşul aynı anda nadiren buluşur. Her biri başlı başına olasılığı küçültür; çarpımları Dünya'yı istisna yapar. Puzzle'ın parçaları galaksinin büyük bölümünde eksiktir.",
      },
      {
        until: 0.9,
        title: "Ward ve Brownlee",
        era: "2000 · Rare Earth",
        text: "Peter Ward ve Donald Brownlee, Rare Earth kitabında bu birikimi tek teze bağladı: mikroplar yaygın, hayvanlar nadir olabilir. Kitap, Evren'in insanlarla dolu olduğu varsayımını güçlü jeoloji verileriyle sınadı.",
      },
      {
        until: 1,
        title: "Sonuç: Nadir Ama Yalnız Değil",
        era: "Açık tartışma",
        text: "Nadir Dünya hipotezi, Fermi sessizliğine ılımlı bir cevaptır: kimse yok değil, karmaşık hayat azdır. Mikrobiyal yaşam Mars, Europa ve Enceladus'ta aranmaya devam ediyor. Tartışma, yeni teleskopların atmosfer taramalarıyla derinleşecek.",
      },
    ],
    notes: [
      N(0.02, 0.09, "G-tipi: 10 milyar yıl kararlı", 0.3, 0.2),
      N(0.12, 0.22, "Shoemaker-Levy 9: 1994", 0.72, 0.24),
      N(0.26, 0.36, "Ay: eksen salınımını sınırlar", 0.28, 0.22),
      N(0.28, 0.36, "Gelgit: kıyı laboratuvarı", 0.72, 0.4),
      N(0.4, 0.51, "Manyetosfer: rüzgâr kalkanı", 0.28, 0.24),
      N(0.55, 0.65, "Merkez: süpernova riski", 0.26, 0.24),
      N(0.57, 0.65, "Kenar: metal yoksulluğu", 0.74, 0.4),
      N(0.69, 0.76, "Beş koşul: çarpım olasılık", 0.5, 0.16),
      N(0.8, 0.88, "Rare Earth: Ward, Brownlee", 0.5, 0.18),
      N(0.91, 0.99, "Mikroplar yaygın olabilir", 0.5, 0.8),
    ],
    cues: [
      C(0.005, "chime", 0.5),
      C(0.05, "shimmer", 0.5),
      C(0.11, "grow", 0.55),
      C(0.24, "pop", 0.6),
      C(0.3, "boom", 0.4),
      C(0.38, "merge", 0.7),
      C(0.44, "shimmer", 0.4),
      C(0.53, "engine", 0.5),
      C(0.58, "grow", 0.6),
      C(0.67, "starform", 0.8),
      C(0.72, "shimmer", 0.5),
      C(0.78, "merge", 0.7),
      C(0.88, "chime", 0.6),
      C(0.95, "bell", 0.7),
    ],
    ticker: [
      "Peter Ward ve Donald Brownlee, 2000 tarihli Rare Earth kitabıyla karmaşık yaşamın nadirliğini savundu.",
      "Güneş, G2V sınıfı bir yıldızdır; ışınımı on milyar yıllık ölçekte yalnızca yavaşça güçlenir.",
      "1994'te Shoemaker-Levy 9'un parçaları Jüpiter'e çarptı; çarpma izleri aylarca gezegen yüzeyinde kaldı.",
      "Ay'ın çekimi Dünya'nın eksen eğikliğini 22,1 ile 24,5 derece arasında tutarak iklimi kararlı kılar.",
      "Mars'ın eksen eğikliği, uydusu küçük olduğu için yüz binlerce yıllık ölçekte kaotik biçimde salınabilir.",
      "Levha tektoniği, havadaki karbonu kayaçlarla geri dönüştürerek uzun vadeli sera düzenlemesi yapar.",
      "Dünya'nın sıvı demir-nikel dış çekirdeği jeodinamo üretir; bu manyetosfer güneş rüzgârını saptırır.",
      "Galaktik yaşanabilir bölge, merkezden yaklaşık 25-30 bin ışık yılı mesafedeki güvenli halkadır.",
      "Venüs'ün belirgin bir manyetik alanı yoktur; güneş rüzgârı atmosferinin bir bölümünü uzaya taşımıştır.",
      "Hipoteze göre mikrobiyal yaşam galakside yaygın olabilir; nadir olan, hayvan ve zeka basamağıdır.",
    ],
  },

  /* ------------------------- 5) Kara Orman ------------------------------ */
  {
    id: "kara-orman",
    title: "Kara Orman Hipotezi",
    subtitle:
      "Evren karanlık bir ormandır ve her uygarlık silahını doğrultmuş bir avcıdır",
    duration: 105,
    color: "#64748b",
    cat: "gelecek",
    stages: [
      {
        until: 0.12,
        title: "Gece Ormanı Benzetmesi",
        era: "Liu Cixin · 2008",
        text: "Karanlık Orman, Liu Cixin'in Üç Cisim serisinin ikinci kitabının adı ve tezidir. Evren, dolu bir gece ormanı gibi tasvir edilir: gezinen avcılar birbirinin sesini duyar ama göremez. Her uygarlık, fark edilmemek için sustuğu ölçüde hayatta kalır.",
      },
      {
        until: 0.28,
        title: "Galaksi Bir Ormandır",
        era: "Avcı uygarlıklar",
        text: "Her parlak nokta bir uygarlık olsaydı, galaksi bir ormandaki ateşböcekleri gibi görünürdü. Kara Orman tezine göre her uygarlık diğerini potansiyel avcı sayar. Kimse ilk hamleyi cesaretle değil, görülmemek için çaba harcar.",
      },
      {
        until: 0.42,
        title: "Sessizlik Stratejisi",
        era: "Radyo sessizliği",
        text: "Teze göre sinyal göndermek, karanlıkta el feneri yakmaktır; ışığını gösteren önce vurulur. Bu yüzden galaksi, teknolojik açıdan canlı olsa bile radyo açısından ölüdür. Fermi sessizliğinin bu yorumu, aktif mesajlara karşı temkinli bir duruştur.",
      },
      {
        until: 0.56,
        title: "İki Işığın Karşılaşması",
        era: "Zincirleme şüphe",
        text: "İki uygarlık karşılaştığında mesafe yüzünden niyet doğrulanamaz; her yanıt yıllar alır. Bu arada teknoloji patlaması, diğer tarafı ölümcül tehdide dönüştürür. Tez, güven zincirinin kurulamayacağını varsayar ve saldırıyı 'makul' kılar.",
      },
      {
        until: 0.68,
        title: "Kural: Açıklanmak Ölmektir",
        era: "Ormanın yasası",
        text: "Kitabın ünlü kuralı nettir: uygarlık, konumunu gizlediği sürece yaşar. Açıklanmak, ormanda iz bırakan bir hayvanın başına gelen gibidir. Bu kural, hüzünlü ama içtutarlı bir evren imgesi çizer.",
      },
      {
        until: 0.84,
        title: "Bizim Sinyalimiz",
        era: "1974 · Arecibo",
        text: "16 Kasım 1974'te Arecibo teleskopundan 1679 bitlik mesaj, Herkül'deki M13 kümesine gönderildi. Sinyal 25.000 ışık yılı yol alacak; olası yanıt 50.000 yıl sonra gelebilir. Kara Orman okuru bu mesajı, ormana bırakılmış bir iz sayar.",
      },
      {
        until: 1,
        title: "Saklanmak mı, Selamlamak mı",
        era: "Açık karar",
        text: "Karanlık Orman bir kanıt değil, evrensel oyun kuramı deneyidir; kanıtlar tartışmalıdır. İnsanlık sessiz kalmayı da mesaj göndermeyi de denemiş durumda. Belki galaksi gerçekten boştur, belki de herkes nefesini tutmuştur.",
      },
    ],
    notes: [
      N(0.02, 0.11, "Liu Cixin: Üç Cisim 2", 0.28, 0.2),
      N(0.03, 0.11, "Evren: karanlık orman", 0.72, 0.3),
      N(0.15, 0.26, "Her ışık: bir uygarlık", 0.26, 0.24),
      N(0.18, 0.26, "Kimse ilk el fenerini yakmaz", 0.72, 0.4),
      N(0.44, 0.54, "Güven zinciri kurulamaz", 0.28, 0.22),
      N(0.46, 0.54, "Teknoloji patlaması: tehdit", 0.72, 0.4),
      N(0.58, 0.66, "Açıklanmak, ölmektir", 0.5, 0.2),
      N(0.72, 0.82, "Arecibo: 1679 bit", 0.28, 0.24),
      N(0.74, 0.82, "M13: 25.000 ışık yılı", 0.72, 0.42),
      N(0.88, 0.98, "Kanıt yok, teori güçlü", 0.5, 0.82),
    ],
    cues: [
      C(0.005, "wind", 0.5),
      C(0.07, "shimmer", 0.4),
      C(0.12, "wind", 0.6),
      C(0.28, "whoosh", 0.7),
      C(0.34, "shimmer", 0.45),
      C(0.42, "wind", 0.7),
      C(0.5, "zap", 0.55),
      C(0.56, "glitch", 0.7),
      C(0.6, "glitch", 0.45),
      C(0.68, "boom", 0.4),
      C(0.7, "bell", 0.3),
      C(0.84, "engine", 0.5),
      C(0.88, "whoosh", 0.6),
      C(0.96, "wind", 0.75),
    ],
    ticker: [
      "Karanlık Orman, Liu Cixin'in Üç Cisim üçlemesinin ikinci kitabının adı; Çince baskısı 2008 tarihlidir.",
      "Kitabın benzetmesine göre evren, her avcının sessizce dolaştığı karanlık bir gece ormanıdır.",
      "Avcılar gördükleri her uygarlığı, teknoloji patlaması ihtimali nedeniyle öncelikle tehdit sayar.",
      "Mesafe ve gecikme yüzünden iki uygarlık arasında güven zinciri kurulamaz; şüphe kazanır.",
      "16 Kasım 1974'te Arecibo mesajı gönderildi; 1679 bitlik görüntü, 23 × 73 piksel matrisiydi.",
      "Arecibo sinyali Herkül takımyıldızındaki M13 küresel kümesine hedeflendi; mesafe yaklaşık 25.000 ışık yılı.",
      "Mesajın M13'e varması 25 bin yıl sürecek; olası bir yanıt için en az 50 bin yıl beklemek gerekir.",
      "Tez, Fermi paradoksunu 'herkes duyulmamak için saklanıyor' biçiminde yorumlayan bir çözümdür.",
      "SETI araştırmacılarının çoğu, sinyal yaymanın riskini düşük bulur; konu bilimsel çevrelerde tartışmalıdır.",
      "Hiçbir uluslararası yasa gezegenimizden radyo mesajı göndermeyi yasaklamıyor; karar kültürlere kalıyor.",
    ],
  },
];
