import type { TheoryDef } from "../theories";
import { N, C } from "./helpers";

/**
 * Yaşamın kökeni teorileri — 5 uzun animasyon tanımı (26-30).
 *
 * Bu paketteki teoriler "yasam" kategorisindedir: İlkel Çorba (Oparin-Haldane),
 * RNA Dünyası, Hidrotermal Baca (Demir-Sülfür), Panspermia ve Metabolizma İlk.
 * Tüm metinler gerçek bilimsel kaynaklara dayanır (Oparin 1924, Haldane 1929,
 * Miller-Urey 1953, Woese 1967, Gilbert 1986, Wächtershäuser 1988, Russell
 * 1989, Hoyle & Wickramasinghe, Murchison meteoriti 1969).
 */
export const LIFE_THEORIES: TheoryDef[] = [
  /* --------------------- 26) İlkel Çorba Hipotezi ---------------------- */
  {
    id: "ilkel-corba",
    title: "İlkel Çorba (Oparin-Haldane) Hipotezi",
    subtitle:
      "Canlı olmayan kimyasallardan ilk organik moleküllere — genç Dünya'nın kaynayan kimya tenceresi",
    duration: 100,
    color: "#4ade80",
    cat: "yasam",
    stages: [
      {
        until: 0.12,
        title: "Oksijensiz Bir Gezegen",
        era: "4,4 milyar yıl önce",
        text: "İlkin Dünya atmosferinde serbest oksijen yoktu: metan, amonyak, hidrojen, su buharı ve karbondioksit vardı. Bu 'indirgeyici' atmosfer, organik moleküllerin parçalanmadan birikmesine izin veriyordu — canlılığın kurulabileceği bir ham mafe depositsi.",
      },
      {
        until: 0.26,
        title: "Oparin ve Haldane'nin Sezgisi",
        era: "1924 · 1929",
        text: "Alexander Oparin 1924'te, John Haldane 1929'da bağımsız olarak aynı fikri ortaya attı: okyanuslar, güneş ışığı ve şimşeklerle beslenen dev bir kimyasal tepkime kazanıydı. Binlerce yılda basit gazlar, giderek karmaşık organik moleküllere dönüşerek denizde birikirdi — ilkel çorba.",
      },
      {
        until: 0.42,
        title: "Miller-Urey Deneyi: Fikir Kanıtlanıyor",
        era: "1953 · Chicago",
        text: "Stanley Miller, Harold Urey'nin gözetiminde kapalı cam devrede deniz suyu, metan, amonyak ve hidrojen karışımına haftalarca elektrik şimşekleri gönderdi. Sonuç şaşırtıcıydı: karışım içinde glicin, alanin gibi 13 amino asit — proteinlerin yapı taşları — kendiliğinden oluşmuştu.",
      },
      {
        until: 0.58,
        title: "Kimya Tenceresi Kaynıyor",
        era: "İlk okyanuslar",
        text: "Genç Dünya'da her şimşek, her UV ışını, her meteor çarpması çorbanın ateşini harlıyordu. Volkan adaları, ıslanan kuruyan göller, köpüren kıyı çukurları: tekrar tekrar buharlaşma ve yoğunlaşma, molekülleri zenginleştiren doğal bir damıtma hattıydı.",
      },
      {
        until: 0.74,
        title: "Moleküller Tanesi Görüyor",
        era: "Kıyı yüzeyleri",
        text: "Killi yüzeyler ve mineral tanecikleri, organik molekülleri sıralayıp diziyor, kalıplaştırıyordu: yağ molekülleri kendiliğinden küreler (miseller ve lipit zarları) kurar, amino asitler kısa protein zincirlerine eklenirdi. Çorba, kendi kaplarını kendisi yapıyordu.",
      },
      {
        until: 0.88,
        title: "Öncüllerden Öncülüğe",
        era: "Kimyevi evrim",
        text: "Milyonlarca yılda denizler, kendini kopyalayabilen ilk molekülü barındıracak kadar zenginleşti. Bu 'kimyevi evrim' çağında seçilim moleküller arasında çalıştı: kararlı olan birikti, tepkimeci olan çoğaldı. Doğal seçilim, canlılardan milyonlarca yıl önce moleküller arasında başladı.",
      },
      {
        until: 1,
        title: "Bugünün Testi",
        era: "21. yüzyıl",
        text: "Miller-Urey deneyi bugün de çoğaltılıyor; orijinal şişelerden 2008'de modern yöntemlerle 22 amino asit bulundu. Meteoritler de uzayda kurulmuş organikleri getiriyor. İlkel çorba artık tek bir çorba değil: okyanus, göl, buz, mineral ve uzaydan gelen beslemeyle beslenen bir kimya mutfağı ağı.",
      },
    ],
    notes: [
      N(0.02, 0.1, "atmosfer: CH₄ · NH₃ · H₂ · H₂O", 0.5, 0.16),
      N(0.04, 0.1, "serbest O₂ yok!", 0.24, 0.66),
      N(0.15, 0.24, "Oparin 1924 · Haldane 1929", 0.72, 0.28),
      N(0.3, 0.4, "Miller-Urey: 13 amino asit", 0.26, 0.3),
      N(0.33, 0.4, "şimşek = enerji kaynağı", 0.74, 0.6),
      N(0.47, 0.56, "tekrarlı buharlaşma = damıtma", 0.5, 0.18),
      N(0.61, 0.72, "lipit zarları kendiliğinden kurulur", 0.74, 0.34),
      N(0.63, 0.72, "kil yüzeyi: molekül dizici", 0.24, 0.34),
      N(0.78, 0.86, "molekül seçilimi: kararlı olan kalır", 0.5, 0.7),
      N(0.9, 0.98, "2008: orijinal numunede 22 amino asit", 0.26, 0.22),
    ],
    cues: [
      C(0.001, "rumble", 0.4),
      C(0.12, "rain", 0.6),
      C(0.25, "shimmer", 0.6),
      C(0.42, "zap", 1.0),
      C(0.5, "zap", 0.7),
      C(0.56, "splash", 0.8),
      C(0.72, "cell", 0.8),
      C(0.86, "grow", 0.7),
      C(0.96, "chime", 0.6),
    ],
    ticker: [
      "Miller-Urey deneyinde kullanılan şimşekler, genç Dünya'daki yıldırım yoğunluğunun taklididir.",
      "İndirgeyici atmosferin avantajı: oksijen yokluğunda organikler yıkılmadan birikiyordu.",
      "Miller'in 1953 deneyi 8 gün sürdü; bugünkü modellerde on binlerce farklı organik molekül üretiliyor.",
      "Meteoritler uzayın kendi çorbasını getirir: Murchison meteoriti 70+ amino asit taşıdı.",
      "Lipit zarlar, kapsülleme yapmadan kendiliğinden küre kurar: hücre zarının atası bu keşiften gelir.",
      "Kil mineralleri (montmorillonit) organikleri sıralayıp dizerek katalizör görevi görür.",
      "Oksijen canlılığa hayat verir ama canlılığı başlatırken zehirdi: oksitleyici atmosfer organikleri yakar.",
      "Oparin çorbayı bir kazanda değil, tüm okyanuslarda aramamızı öğretti: dünya bir laboratuvardı.",
    ],
  },

  /* ------------------------ 27) RNA Dünyası ---------------------------- */
  {
    id: "rna-dunyasi",
    title: "RNA Dünyası Hipotezi",
    subtitle:
      "Hem tarif hem işçi olan tek molekül — DNA ve protein'den önce RNA hep vardı",
    duration: 105,
    color: "#34d399",
    cat: "yasam",
    stages: [
      {
        until: 0.13,
        title: "Tavuk-Yumurta Paradoksu",
        era: "1960'lar · soru",
        text: "DNA kalıtımı saklar ama onu okuyacak proteinler gerekir; proteinler çalışır ama kendilerini kodlayacak DNA gerekir. İkisi birbirini bekliyor: hangisi önce geldi? 1960'lardan itibaren moleküler biyologlar bu döngüye takıldı.",
      },
      {
        until: 0.28,
        title: "Woese'nin Öncüsü: RNA Her İkisini Yapıyor",
        era: "1967 · Woese, Crick, Orgel",
        text: "Carl Woese (ve paralel olarak Crick ile Orgel) bir çıkış yolu önerdi: RNA hem bilgi depolayabilir (DNA gibi) hem de kimyasal tepkime hızlandırabilir (protein gibi). Önce RNA vardı; DNA ve protein onun ustalaşmış öğrencileridir.",
      },
      {
        until: 0.45,
        title: "Cech ve Altman: Kanıt Ribozim",
        era: "1982 · Nobel 1989",
        text: "Thomas Cech, RNA'nın kendi kendini kesebildiğini (splicing) gösterdi; Sidney Altman, RNaz P'nin RNA'dan yapıldığını ve protein'siz kataliz yaptığını kanıtladı. Katalitik RNA'ya 'ribozim' dendi — Nobel ödülü 1989'da geldi. RNA gerçekten hem tarif hem işçiydi.",
      },
      {
        until: 0.62,
        title: "Kendi Kendini Kopyalayan Molekül",
        era: "Laboratuvar evrimi",
        text: "Laboratuvarda ribozimler seçilimle geliştirildi: bazıları kendi kopyasını uzatabiliyor, bazıları ligaz (zincir birleştirici) olabiliyor. Bilinen en kısa kendi kendini kopyalayan sistemler, RNA'nın kimyasal akrabaları arasında bulunuyor. Gilbert 1986'da bu çağa 'RNA Dünyası' adını verdi.",
      },
      {
        until: 0.78,
        title: "Hücrenin Kalbi Hâlâ RNA",
        era: "Yaşayan kanıt",
        text: "Ribozom — her canlının protein fabrikası — bir ribozimdir: peptit bağını kuran aktif bölge tamamen RNA'dır. ATP, hücrenin enerji parası, bir nükleotiddir. MRNA, TRNA, SNRNA: hücrenin iç dolup taşan RNA trafiği, eski dünyanın canlı fosilleri gibi çalışıyor.",
      },
      {
        until: 0.9,
        title: "DNA ve Protein Devralıyor",
        era: "Geçiş çağı",
        text: "RNA dünyası yavaş yavaş uzmanlaştı: kalıtım, daha kararlı olan DNA'ya taşındı; kataliz, daha esnek olan proteinlere. RNA aracı olmaya devam etti — üçü bir arada çalışan bir 'RNP dünyası' kuruldu. Bugün tüm canlılarda bu üçlü ortaklık vardır: ortak atadan kalma imza.",
      },
      {
        until: 1,
        title: "Bugün: RNA Şifa ve Sırlar",
        era: "21. yüzyıl",
        text: "RNA dünyası hipotezi bugün hâlâ aktif araştırma alanı: mRNA aşıları RNA'nın gücünü endüstriye çevirdi, asteroitlerin ve buz kızılötesi gözlemler RNA öncüllerinin uzayda oluşabildiğini gösteriyor. İlk canlının kalbi muhtemelen bu esnek moleküldü — ve biz onun mirasçılarıyız.",
      },
    ],
    notes: [
      N(0.02, 0.11, "DNA ← bilgi, protein ← iş", 0.5, 0.16),
      N(0.16, 0.26, "Woese 1967: RNA ortak ataya aday", 0.72, 0.24),
      N(0.33, 0.43, "ribozim = katalitik RNA", 0.26, 0.32),
      N(0.35, 0.43, "Cech + Altman → Nobel 1989", 0.74, 0.6),
      N(0.49, 0.6, "kendi kendini kopyalama", 0.5, 0.7),
      N(0.65, 0.76, "ribozom bir ribozimdir!", 0.26, 0.28),
      N(0.66, 0.76, "ATP = nükleotit", 0.74, 0.36),
      N(0.81, 0.89, "DNA saklar, protein yapar, RNA bağlar", 0.5, 0.18),
      N(0.91, 0.98, "mRNA aşıları: miras güncel", 0.72, 0.66),
    ],
    cues: [
      C(0.001, "hiss", 0.5),
      C(0.13, "shimmer", 0.7),
      C(0.28, "cell", 0.9),
      C(0.45, "grow", 0.8),
      C(0.62, "merge", 0.6),
      C(0.78, "chime", 0.8),
      C(0.9, "shimmer", 0.7),
      C(0.97, "chime", 0.5),
    ],
    ticker: [
      "Ribozomdaki peptit transferaz aktivitesi, organik olmayan her şeyden arındırılmış testlerde hâlâ RNA'dır.",
      "ATP, hücrenin enerji birimidir ama aynı zamanda bir RNA nükleotididir: eski dünyadan kalan para.",
      "Bazı virüsler (RNA virüsleri) bugün hâlâ kalıtımını RNA'da saklar: eski usul hâlâ çalışıyor.",
      "In vitro seçilim (SELEX) ile laboratuvarda binlerce yeni ribozim keşfedildi: RNA evrimi hızlandırılabilir.",
      "RNA, DNA'dan 120 kat daha hızlı bozunur: dünyayı devralmak için hızlıydı, kalıcı olmak için zayıf.",
      "Gilbert'in 1986 adlandırması, hipotezi birkaç on yıl öncesinin verileriyle canlandırdı.",
      "Nükleotit öncülleri meteoritlerde bulundu: RNA parçaları uzayda kurulup Dünya'ya teslim edilmiş olabilir.",
      "Ribozom, antibiyotiklerin ana hedefidir: RNA dünyasının kalbi bugün tıbbın savaş alanıdır.",
    ],
  },

  /* -------------------- 28) Hidrotermal Baca Teorisi ------------------- */
  {
    id: "hidrotermal-baca",
    title: "Hidrotermal Baca (Demir-Sülfür) Teorisi",
    subtitle:
      "Okyanus diplerindeki sıcak mineraller — yaşamın ilk laboratuvarı çiçek gibi büyüyor",
    duration: 100,
    color: "#2dd4bf",
    cat: "yasam",
    stages: [
      {
        until: 0.14,
        title: "1977: Galapagos yakınında keşif",
        era: "Alvin denizaltısı",
        text: "Alvin denizaltısı, Galapagos Yarığı yakınında 2.500 m derinlikte kimsenin beklemediği bir vahşi hayat buldu: siyah duman fışkırtan bacalar, sıcak mineral zengini su ve bu bacalara bağımlı tam bir ekosistem. Güneş'siz yaşam mümkündü — ve belki de ilk kez burada başlamıştı.",
      },
      {
        until: 0.3,
        title: "Güneş'siz Enerji",
        era: "Kemosentez",
        text: "Bacalardan çıkan hidrojen sülfür, bakteriler tarafından oksitlenir: kemosentez. Amonyak, karbondioksit ve demir gibi minerallerle yüklü bu sıcak su, yaşamsal kimyanın girdilerini kesintisiz sağlıyordu. Burada gün yoktu, gece yoktu, hava durumu yoktu: sabit enerji, sabit girdi.",
      },
      {
        until: 0.46,
        title: "Wächtershäuser: Demir-Sülfür Dünyası",
        era: "1988 · patentli fikir",
        text: "Günter Wächtershäuser, pirit (demir sülfür) yüzeyinin organik molekülleri katalizlediğini öne sürdü: FeS + H₂S → FeS₂ + H₂ tepkimesi enerji verir ve bu enerji, karbonu birbirine bağlamaya yeter. Canlılığın ilk metabolizması, mineral yüzeyde yürüyen bir tepkime ağı olabilir.",
      },
      {
        until: 0.62,
        title: "Russell'ın Mikro Cep Teorisi",
        era: "1989 · Lost City",
        text: "Michael Russell, alkali hidrotermal bacaların delikli duvarlarını önerdi: mikro boşluklar, kimyasal öncüllerin doğal reaktörüydü. İçerisi alkali (pH 9-11), dışerisi asidik: bu pH farkı, bugünkü tüm hücrelerin kullandığı proton gradyanının atasıydı. Lost City bacaları 2000'de keşfedildi: bu teorinin canlı örneği.",
      },
      {
        until: 0.78,
        title: "Mineral Labirentte Kataliz",
        era: "Deneysel doğrulama",
        text: "Laboratuvar mikroakışkan reaktörlerinde, bu mineral boşluklarda amino asitler, yağlar ve hatta nükleotit öncülleri oluşabildi. Demir-nikel sülfür kümeleri CO₂'yi formata dönüştürüyor, CO molekülü metile bağlanıyor: metabolizmanın ilk turu, mineral yüzeylerde dönüyordu.",
      },
      {
        until: 0.9,
        title: "Zar ve Gen Buradan Çıkıyor",
        era: "Köken hipotezi",
        text: "Mikro boşluklar, zar sorunu olmayan doğal hücreler gibi davrandı: iyon gradyanı hazır, besin girişi hazır, ürün birikimi hazır. RNA öncülleri bu zengin ortamda kopyalanmaya başladığında, ilk prokaryotların atası bacadan koparak okyanusa yayıldı.",
      },
      {
        until: 1,
        title: "Bugün: Baca Hâlâ Yaşıyor",
        era: "21. yüzyıl",
        text: "Bu bacaların etrafındaki mikropların soyları, muhtemelen Dünya'nın en eski canlı soylarıdır: bakteri ağacı köklerinin en derin dalları hep termofiller. Ve benzer bacalar Europa ve Enceladus'un buz altı okyanuslarında da var: yaşam burada başladıysa, orada da başlamış olabilir.",
      },
    ],
    notes: [
      N(0.02, 0.12, "2.500 m derinlik · 350 °C", 0.5, 0.16),
      N(0.04, 0.12, "Alvin 1977 keşfi", 0.24, 0.7),
      N(0.17, 0.28, "kemosentez: H₂S → enerji", 0.72, 0.26),
      N(0.34, 0.44, "FeS + H₂S → FeS₂ + H₂", 0.26, 0.3),
      N(0.36, 0.44, "Wächtershäuser 1988", 0.74, 0.6),
      N(0.5, 0.6, "pH farkı = proton motoru", 0.5, 0.72),
      N(0.52, 0.6, "Lost City 2000", 0.24, 0.28),
      N(0.66, 0.76, "mikro boşluk = doğal hücre", 0.72, 0.34),
      N(0.68, 0.76, "CO₂ → format → şeker", 0.26, 0.6),
      N(0.82, 0.9, "termofiller = en eski soylar", 0.5, 0.18),
      N(0.92, 0.98, "Europa · Enceladus: aynı fırsat", 0.5, 0.68),
    ],
    cues: [
      C(0.001, "hiss", 0.6),
      C(0.13, "lava", 0.8),
      C(0.3, "bubble", 0.7),
      C(0.46, "shimmer", 0.7),
      C(0.62, "cell", 0.8),
      C(0.78, "grow", 0.7),
      C(0.9, "chime", 0.6),
      C(0.97, "chime", 0.5),
    ],
    ticker: [
      "Siyah bacacıklardan çıkan 'duman' su değildir: süper ısınmış mineral zengini sıvının aniden soğumasıdır.",
      "Bacalardaki karides ve Midye'lerin organlarında milyonlarca kemosentetik bakteri yaşar: güneşsiz gıda zinciri.",
      "Pirit'in diğer adı 'delilik altını'dır: katalitik yüzeyi, organik kimyayı ilerleten kristal bir araçtır.",
      "Proton gradyanı bugün ATP sentazı çalıştırır: ilk hücrenin motoru, bacanın pH basamağıydı.",
      "Mikro boşlukların duvarları yağ gibi davranır: organik molekülleri içeride tutup dışarıyı süzer.",
      "Kara duman (siyah baca) 350 °C'dir; beyaz duman (Lost City) 40-90 °C: yaşam için ikincisi daha uygundur.",
      "Bu ortamda hiç UV ve meteor bombardımanı yoktur: yüzeydeki çorbadan daha güvenli bir inkübatördür.",
      "Enceladus'un su fışkırtan çatlaklarında hidrojen bulunmuştur: Cassini, baca kimyasının uzaydaki izini kokladı.",
    ],
  },

  /* ------------------------ 29) Panspermia ----------------------------- */
  {
    id: "panspermia",
    title: "Panspermia Teorisi",
    subtitle:
      "Yaşamın tohumu Dünya'da değil: uzaydan ekildi — meteorit, kuyrukluyıldız ve yıldız tozu taşımacılığı",
    duration: 95,
    color: "#a3e635",
    cat: "yasam",
    stages: [
      {
        until: 0.14,
        title: "Anaxagoras'tan Kelvin'e",
        era: "MÖ 5. yy · 19. yy",
        text: "Anaxagoras MÖ 5. yüzyılda yaşamın gök adamlardan geldiğini söylüyordu; 19. yüzyılda Kelvin ve Richter de benzerini önerdi. Svante Arrhenius 1903'te 'panspermia' terimini verdi: yaşam, evrende yaygın olan bir fenomen ve gökcisimleri arasında taşınıyor.",
      },
      {
        until: 0.3,
        title: "Yaşam Uzaya Dayanabilir mi?",
        era: "Deneysel test",
        text: "Dış uzay: vakum, -270 °C, sert UV ve kozmik ışın. Yine de deneysel testler şaşırtıcı: lişenler ve tardigradlar vakuma aylarca dayanabildi, bakteri sporları ışından koruyucu kabukların içinde yıllarca hayatta kaldı. Kalın kaya içinde seyahat eden mikroplar için şans gerçek var.",
      },
      {
        until: 0.46,
        title: "Murchison: Uzaydan Gelen Kimya",
        era: "1969 · Avustralya",
        text: "Murchison meteoriti Dünya'ya düştüğünde içinde 70'ten fazla amino asit bulundu; bazıları Dünya'da hiç yoktu. Soluk kristalleri sağ-el (D) ve sol-el (L) karışımıydı ama L fazla: canlıların kullanığı sol-el tercihinin uzaydan gelmiş bir imzası olabilir.",
      },
      {
        until: 0.62,
        title: "İki Taşıma Yolu",
        era: "Kaya ve toz",
        text: "Litopanspermia: Mars gibi gezegenlerden çarpmayla kopan kaya parçaları, içinde mikropları koruyarak yıllar sonra başka gezegene iner. Radyopanspermia: mikroskobik sporlar, yıldız ışığının basıncıyla galakside sürüklenir. Her iki yol da fiziksel olarak mümkün: Mars'a giden 34 Apollo ve meteorit kanıtı var.",
      },
      {
        until: 0.78,
        title: "Yıldız Tozu: Organik Fabrikası",
        era: "Hoyle-Wickramasinghe",
        text: "Fred Hoyle ve Chandra Wickramasinghe, kuyrukluyıldız tozunda ve yıldızarası bulutlarda geniş organik kimya bulunduğunu gösterdi: polisiklik aromatik hidrokarbonlar, glikolaldehit, hatta glicin öncülleri. Samanyolu, uzaktan bakıldığında dev bir kimya fabrikası gibi davranıyor.",
      },
      {
        until: 0.9,
        title: "Dünya'da Bir Kez mi Başladı?",
        era: "Avantaj ve eleştiri",
        text: "Panspermia, yaşama başlamanın zorluğunu başka bir yere taşır: uzaydan gelen moleküller ilk çorbayı zenginleştirdi (bu kesin gibi) ama ilk canlı molekülün nerede kurulduğu hâlâ açık. Klasik eleştiri: 'kökeni erteler, çözmez.' Modern cevap: 'çoğaltır ve yayılır.'",
      },
      {
        until: 1,
        title: "Bugünün Arayışı",
        era: "21. yüzyıl",
        text: "Hayabusa2 ve OSIRIS-REx asteroit örnekleri organik zenginliği doğruladı; Enceladus ve Europa misyonları başka okyanuslarda yaşam arayacak. Eğer yaşam Mars'ta bulunduysa ve genetiği bize çok benziyorsa, panspermia ciddi bir aday olarak geri döner: belki hepimiz, uzak bir yıldızın tozunun torunlarıyız.",
      },
    ],
    notes: [
      N(0.02, 0.12, "Anaxagoras: MÖ 5. yy", 0.5, 0.16),
      N(0.04, 0.12, "Arrhenius 1903: 'panspermia'", 0.24, 0.7),
      N(0.17, 0.28, "tardigradlar vakuma dayanır", 0.72, 0.26),
      N(0.34, 0.44, "Murchison: 70+ amino asit", 0.26, 0.3),
      N(0.36, 0.44, "sol-el fazla: uzay imzası", 0.74, 0.6),
      N(0.49, 0.6, "Mars'tan Dünya'ya kaya taşımacılığı", 0.5, 0.72),
      N(0.51, 0.6, "meteorit: ALH84001", 0.24, 0.28),
      N(0.66, 0.76, "yıldıztozu: PAH fabrikası", 0.72, 0.34),
      N(0.68, 0.76, "glicin kuyrukluyıldızda bulundu", 0.26, 0.6),
      N(0.82, 0.9, "erteler mi, çoğaltır mı?", 0.5, 0.18),
      N(0.92, 0.98, "Hayabusa2 · OSIRIS-REx", 0.5, 0.68),
    ],
    cues: [
      C(0.001, "wind", 0.5),
      C(0.14, "whoosh", 0.7),
      C(0.3, "shimmer", 0.6),
      C(0.45, "crash", 0.7),
      C(0.62, "wind", 0.6),
      C(0.78, "shimmer", 0.8),
      C(0.9, "chime", 0.6),
      C(0.97, "bell", 0.5),
    ],
    ticker: [
      "Ay'a çıkan Apollo aynaları hâlâ duruyor: bu aynaların üzerinde Mars'tan gelmiş şüpheli mikro mikro izler aranıyor.",
      "ALH84001: Mars'tan kopan meteorit, 1984'te Antarktika'da bulundu; içindeki mikro yapılar tartışmayı hâlâ sürdürüyor.",
      "Tardigradlar vakumda 10 gün yaşayabildi: bilinen en dirençli Dünya canlısı bu açıdan test edildi.",
      "Kuyrukluyıldız 67P'ye inen Philae, organik molekülleri tespit etti: Rosetta misyonu panspermia'nın ham maddesini gördü.",
      "Sol-el amino asit tercihi (homochirality), canlılığın en sırlı imzasıdır: meteoritlerde hafif L fazlası görüldü.",
      "Dünya'dan Ay'a giden Surveyor 3 kamerası, 2,5 yıl sonra toplanan mikropların bir kısmının hayatta olduğu iddia edildi.",
      "Panspermia tek başına kökeni açıklamaz: taşınan yaşamın ilk defa nerede başladığını yine sormak gerekir.",
      "Enzimsiz bir RNA zinciri 150 nükleotit civarında olmalıdır: bu boyut, buz kızılötesi gözlere göre kuyrukluyıldız çekirdeklerinde kurulabilir.",
    ],
  },

  /* -------------------- 30) Metabolizma İlk --------------------------- */
  {
    id: "metabolizma-once",
    title: "Metabolizma İlk Hipotezi",
    subtitle:
      "Gen'den önce reaksiyon ağları vardı: ilk 'canlı' bir kimya fabrikasıydı, zarfı sonra geldi",
    duration: 90,
    color: "#fb923c",
    cat: "yasam",
    stages: [
      {
        until: 0.14,
        title: "Gen Önce mi, İş Önce mi?",
        era: "Temel çelişki",
        text: "RNA dünyası 'bilgi önce' der; metabolizma ilk hipotezi 'kimya önce' der. Bir canlıyı canlı yapan şey genetik tarif mi, yoksa enerji ve maddeyi dönüştüren tepkime ağı mı? İkinci görüş, ilk canlının kendini kopyalayan bir molekül değil, kendini sürdüren bir tepkime döngüsü olduğunu söylüyor.",
      },
      {
        until: 0.3,
        title: "Oparin'in Koadervatları",
        era: "1938 · ilk model",
        text: "Oparin, protein benzeri moleküllerin suda koadervat damlacıkları kurduğunu gösterdi: zarfı olmayan ama içerisi dışarıdan farklılaşan kimyasal damlalar. Bu damlalar madde alıp veren, büyüyen, bölünen 'protobiont' adaylarıydı: hücrenin mühürsüz öncüleri.",
      },
      {
        until: 0.46,
        title: "Autotrofik Köken: Kauffman Ağları",
        era: "1980'ler · karmaşıklık",
        text: "Stuart Kauffman, yeterince yoğun bir kimyasal ağın kendiliğinden döngüsel tepkime setleri (otokatalitik döngüler) kurduğunu gösterdi: A, B'yi yapar; B, C'yi; C de A'yı — ağ kendi kendini besler. Bu 'autotrofik' modelde metabolizma, gen'den önce mekanik olarak ortaya çıkar.",
      },
      {
        until: 0.62,
        title: "TCA Döngüsünün Tersten Çalışması",
        era: "Evrensel çekirdek",
        text: "Tüm canlıların metabolik kalbindeki Krebs (TCA) döngüsü, oksijenli solunumda tersine çalışır ve CO₂'den organik molekül kurar: pek çok biyokimyacıya göre bu, ilk metabolizmanın izleri. Nükleotit ve amino asit ön maddeleri, bu döngünün yan dallarından çıkar: kimya önce, tarif sonra.",
      },
      {
        until: 0.78,
        title: "Mineral Kataliz: Enzim'in Öncüsü",
        era: "Demir-sülfür köprüsü",
        text: "Wächtershäuser'in pirit yüzeyi ve Russell'ın bacaları, bu hipotezin sahnesidir: mineral katalizörler, enzimlerden önce tepkimeleri hızlandırdı. İlginç detay: bugünkü enzimlerin aktif merkezlerinde hâlâ demir-sülfür kümeleri vardır — eski mineral katalizörlerin canlıya taşınmış kalıntıları.",
      },
      {
        until: 0.9,
        title: "Zar Sonra Gelir",
        era: "Kompartımanlaşma",
        text: "Ağ kurulduktan sonra problem cebe girmek: lipit zarları ve protein gövdeleri, kimyasal ağı dışarıdan ayırarak gerçek hücreyi kurdu. Bu modelde hücre zarı, metabolizmanın 'paketi' — metabolizmanın kendisi paketlemeden önce milyonlarca yıl açık alanda işledi.",
      },
      {
        until: 1,
        title: "Bugün: Ağ Bilimi",
        era: "21. yüzyıl",
        text: "Metabolik ağlar bugün bilgisayarda modelleniyor: otokatalitik döngüler laboratuvarda kuruldu, hatta sentetik biyoloji bunu ilaç ve biyoyakıt üretimine taşıdı. Eğer hipotez doğruysa, 'canlı' kavramı genetikten önce kimyada doğdu: hayat, bir tarif değil, bir akış ve o akış devam ediyor.",
      },
    ],
    notes: [
      N(0.02, 0.12, "gen önce mi, iş önce mi?", 0.5, 0.16),
      N(0.04, 0.12, "Oparin: koadervat damlaları", 0.24, 0.7),
      N(0.17, 0.28, "otokatalitik döngü: A→B→C→A", 0.72, 0.26),
      N(0.34, 0.44, "TCA döngüsü ters çalışır", 0.26, 0.3),
      N(0.36, 0.44, "Kauffman 1980'ler", 0.74, 0.6),
      N(0.5, 0.6, "Fe-S kümeleri: eski kataliz", 0.5, 0.72),
      N(0.52, 0.6, "enzimlerin kalbinde hâlâ Fe-S", 0.24, 0.28),
      N(0.66, 0.76, "zar: sonradan gelen paket", 0.72, 0.34),
      N(0.68, 0.76, "protobiont: mühürsüz hücre", 0.26, 0.6),
      N(0.82, 0.9, "sentetik biyoloji: döngü kuruldu", 0.5, 0.18),
      N(0.92, 0.98, "hayat = akış, tarif değil", 0.5, 0.68),
    ],
    cues: [
      C(0.001, "hiss", 0.5),
      C(0.14, "cell", 0.7),
      C(0.3, "grow", 0.8),
      C(0.46, "shimmer", 0.7),
      C(0.62, "merge", 0.6),
      C(0.78, "cell", 0.8),
      C(0.9, "chime", 0.6),
      C(0.97, "grow", 0.5),
    ],
    ticker: [
      "Koadervat damlaları, sallandığında bölünebilir: hücre bölünmesinin mühürsüz atası.",
      "Otokatalitik döngü matematiksel olarak 'kaotik yakınsama' gösterir: doğru koşulda kendini besleyen ağ kaçınılmazdır.",
      "Bugünkü enzimlerdeki demir-sülfür kümeleri, Wächtershäuser'in mineral katalizörlerinin canlılara taşınmış mirasıdır.",
      "TCA döngüsünün tüm ara maddeleri, amino asit ve nükleotit sentezinin başlangıç noktasıdır: metabolik çekirdek çok eskidir.",
      "Metabolizma ilk modelinde kalıtım yavaş yavaş 'yakalanır': ağ önce var olur, gen ağın kaydını tutmaya başlar.",
      "Sentetik biyologlar 2009'da in vitro otokatalitik döngü kurdular: formilamid ile pirimidin sentezi.",
      "Canlılık tanımının birçoğu 'metabolizma + kalıtım' der: metabolizma ilk hipotezi, bu iki ayaktan hangisinin önce geldiğini tartışır.",
      "Dünya'nın karbon döngüsü, ilk metabolik ağın büyütülmüş bir devamı gibi düşünülebilir: gezegen hâlâ 'nefes alıyor'.",
    ],
  },
];
