import type { TheoryDef } from "../theories";
import { N, C } from "./helpers";

/**
 * Fizik teorileri (9-15): Newton'dan holografik ilkeye.
 */
export const PHYSICS_THEORIES: TheoryDef[] = [
  {
    id: "klasik-mekanik",
    cat: "fizik",
    title: "Klasik Mekanik (Newton Fiziği)",
    subtitle:
      "Elmayı ve Ay'ı aynı kanuna bağlayan devrim: 1687 Principia ve saat gibi işleyen evren",
    duration: 115,
    color: "#cbd5e1",
    stages: [
      { until: 0.14, title: "1665: Veba ve Elma", text: "Londra veba salgınında Cambridge kapanır; genç Isaac Newton çiftliğe döner. Düşen elma, Ay'ı yörüngede tutan kuvvetle aynı mı?", era: "1665-1666" },
      { until: 0.3, title: "Ay da Düşüyor", text: "Newton hesaplar: Ay, Dünya'ya her saniye 1,4 mm düşer. Yörünge, sürekli düşüşle ileri uçuşun dengesidir. Elma ile Ay aynı kanuna tabi.", era: "hesap" },
      { until: 0.46, title: "Newton'un Topu", text: "Dağ tepesinden atılan top gitgide hızlanırsa: düşer, uzaklaşır, Dünya'yı sarar, yörüngeye girer. Yörünge mekanik bir deneydir.", era: "düşünce deneyi" },
      { until: 0.62, title: "Evrensel Kütleçekimi", text: "F = G·m₁m₂/r²: her kütle her kütleyi çeker. Aynı yasa elmayı, Ay'ı, gelgitleri ve gezegenleri tek formülde birleştirir.", era: "1687 Principia" },
      { until: 0.78, title: "Determinist Saat Evreni", text: "Laplace'a göre: bir anın tüm konum ve hızlarını bilen zeka, geleceği hesaplayabilir. Klasik evren, ayarlanmış bir saat mekanizmasıdır.", era: "determinizm" },
      { until: 1, title: "Sınırları", text: "Merkür'ün perihel kayması kusurunu açığa vurur; ışık hızı yakınında kanunlar çürür. Newton, düşük hızlarda hâlâ kusursuz çalışır.", era: "sınırlar" },
    ],
    notes: [
      N(0.05, 0.13, "veba yılları: 1665", 0.3, 0.3),
      N(0.32, 0.4, "Ay: 1,4 mm/sn düşüş", 0.66, 0.28),
      N(0.5, 0.58, "F = G·m₁m₂/r²", 0.5, 0.64),
      N(0.66, 0.74, "Principia, 1687", 0.28, 0.32),
      N(0.84, 0.92, "Laplace'ın şeytanı", 0.62, 0.66),
    ],
    cues: [
      C(0.001, "wind", 0.5),
      C(0.14, "pop", 0.6),
      C(0.3, "whoosh", 0.7),
      C(0.46, "engine", 0.8),
      C(0.62, "bell", 0.9),
      C(0.78, "chime", 0.8),
      C(0.92, "whoosh", 0.6),
    ],
    ticker: [
      "Newton, Principia'yı 1687'de yayımladı: bilim tarihinin en etkili kitabı sayılır.",
      "Ay'ın Dünya'ya düşüş hızı saniyede ~1,4 mm: yörünge bu düşüşün kendisidir.",
      "Halley, Principia'nın baskı masrafını kendi cebinden karşıladı — kuyruklu yıldız onun adını taşır.",
      "Newton'un kütleçekimi Cavendish'in 1798 terazisiyle laboratuvarda ölçüldü.",
      "Laplace'ın 'şeytanı': tüm konum ve hızları bilen zeka geleceği hesaplayabilir.",
      "Neptün, 1846'da Uranüs'ün yörünge sapmalarından HESAPLANARAK bulundu: Newton zaferi.",
      "Merkür'ün perihel kaymasıNewton'la açıklanamaz: 43 ark-saniye/yıl fazlalık — görelilik çözer.",
      "Klasik mekanik bugün roket yörüngelerinin %99'unu hâlâ mükemmel hesaplar.",
    ],
  },
  {
    id: "ozel-gorelilik",
    cat: "fizik",
    title: "Özel Görelilik Teorisi",
    subtitle:
      "1905 mucize yılı: ışık hızı sabittir, zaman genleşir, kütle enerjiye dönüşür",
    duration: 120,
    color: "#67e8f9",
    stages: [
      { until: 0.15, title: "İki Postülat", text: "26 yaşındaki patent memuru Einstein iki ileri sürer: (1) fizik yasaları her sabit hızlı gözlemci için aynıdır, (2) ışık hızı herkes için c'dir.", era: "1905" },
      { until: 0.32, title: "Zaman Genleşmesi", text: "Işık hızına yakın hareket eden saatler YAVAŞ ilerler: hareketli kardeş genç kalır. Muonlar bunu saniyeler içinde kanıtlar.", era: "etki 1" },
      { until: 0.48, title: "Uzunluk Kısalması", text: "Hızlı gemi, yönünde kısılır: 0,87c'de boyun yarısı. Her gözlemci kendi düzleminde normal ölçer — 'aynı anda'lık mutlak değildir.", era: "etki 2" },
      { until: 0.64, title: "Eşzamanlılık Krizi", text: "Platformdaki ve trendeki gözlemci, aynı iki şimşeğin farklı anda çaktığını görür. Uzay ve zaman ayrı değil: tek bir doku — uzay-zaman.", era: "etki 3" },
      { until: 0.8, title: "E = mc²", text: "Kütle donmuş enerjidir: 1 gram madde 9×10¹³ joul — 21 kiloton TNT. Güneş bu denklemle her saniye 4 milyon ton kütle ışığa çevirir.", era: "1905 devamı" },
      { until: 1, title: "Kanıtlar Her Yerde", text: "Parçacık hızlandırıcıları, GPS saatleri, altın levha deneyleri: özel görelilik günlük teknolojide çalışıyor. Hız limiti c: 299.792.458 m/sn.", era: "bugün" },
    ],
    notes: [
      N(0.05, 0.13, "c = 299.792 km/sn", 0.5, 0.28),
      N(0.34, 0.42, "gemi saati yavaş", 0.28, 0.3),
      N(0.5, 0.58, "boyun %50 kısılır", 0.66, 0.3),
      N(0.66, 0.74, "1 g = 21 kt TNT", 0.3, 0.64),
      N(0.84, 0.92, "muon kanıtı", 0.62, 0.66),
    ],
    cues: [
      C(0.001, "whoosh", 0.6),
      C(0.15, "warp", 0.9),
      C(0.32, "shimmer", 0.7),
      C(0.48, "zap", 0.7),
      C(0.64, "bell", 0.8),
      C(0.8, "explosion", 0.8),
      C(0.94, "chime", 0.7),
    ],
    ticker: [
      "1905, Einstein'ın 'mucize yılı' (annus mirabilis): 4 devrimci makale.",
      "Michelson-Morley deneyi (1887) eter aramış, bulamamıştı: özel göreliliğin zeminini hazırladı.",
      "Işık hızına ulaşılamaz: kütle, hıza bağlı olarak sonsuza yaklaşır.",
      "Muonlar, yerden 15 km yukarıda doğar; ömürleri kısa olmasına rağmen yere ulaşır: zaman genleşmesi.",
      "GPS uydularındaki saatler özel görelilik yüzünden günde 7 mikrosaniye HIZLI ilerler.",
      "Hendrik Lorentz dönüşümleri Einstein'dan önce vardı; Einstein onlara anlamını verdi.",
      "E = mc²'nin deneysel ilk kanıtı nükleer reaksiyonlardır; Cockcroft-Walton 1932.",
      "Büyük Hadron Çarpıştırıcısı protonları ışık hızının %99,9999991'ine çıkarır.",
    ],
  },
  {
    id: "genel-gorelilik",
    cat: "fizik",
    title: "Genel Görelilik Teorisi",
    subtitle:
      "Kütleçekimi bir kuvvet değil: kütle uzay-zamanı büküyor — 1915'in en büyük teorisi",
    duration: 125,
    color: "#fbbf24",
    stages: [
      { until: 0.15, title: "En Mutlu Fikir", text: "Einstein 'hayatımdaki en mutlu fikir' der: serbest düşen kişi kendi ağırlığını HİSSETMEZ. Kütleçekimi ve ivme eşdeğerdir — eşdeğerlik ilkesi.", era: "1907" },
      { until: 0.32, title: "Uzay-Zaman Bükülüyor", text: "Kütle, çevresindeki uzay-zaman dokusunu esnetir: küre bir trambolinde ağır bilye gibi. Gezegenler 'düşerek' bu çukurlarda yörünge kurar.", era: "temel resim" },
      { until: 0.48, title: "Işık da Sapıyor", text: "Bükülmüş uzay ışığı da büker: 1919 güneş tutulmasında Eddington yıldız konumlarının sapmasını ölçtü. Einstein bir gecede ünlü oldu.", era: "1919" },
      { until: 0.62, title: "Zaman Kütleyle Yavaşlar", text: "Kütleçekimi derininde saat yavaş ilerler: yerde 79 yıl yaşayan, 400 km yükseklikte 80 yıl yaşayabilir. Dünyanın merkezi Dünya'dan 2,5 yıl genç!", era: "zaman eğrisi" },
      { until: 0.78, title: "Kütleçekim Dalgaları", text: "İki karadelik birleşince uzay-zaman dalgalar halinde titreşir: 1,3 milyar ışık yılından gelen dalga 2015'te LIGO'da protonun binde biri kadar esneklik yarattı.", era: "14 Eylül 2015" },
      { until: 1, title: "Günlük Teknoloji", text: "GPS uyduları günde 38 mikrosaniye düzeltme yapmazsa konum gün içinde 10 km kayar. Genel görelilik artık bir altyapıdır.", era: "bugün" },
    ],
    notes: [
      N(0.05, 0.13, "serbest düşüş = ağırlıksız", 0.5, 0.28),
      N(0.34, 0.42, "trambolin resmi", 0.28, 0.3),
      N(0.5, 0.58, "Eddington, 1919", 0.66, 0.3),
      N(0.64, 0.72, "merkez 2,5 yıl genç", 0.28, 0.64),
      N(0.8, 0.88, "LIGO: GW150914", 0.62, 0.66),
      N(0.94, 0.99, "GPS düzeltmesi: 38 µs", 0.5, 0.3),
    ],
    cues: [
      C(0.001, "whoosh", 0.6),
      C(0.15, "rumble", 0.8),
      C(0.32, "shimmer", 0.7),
      C(0.48, "bell", 0.9),
      C(0.62, "warp", 0.9),
      C(0.78, "crash", 1.1),
      C(0.82, "supernova", 0.9),
      C(0.94, "chime", 0.7),
    ],
    ticker: [
      "Alan denklemleri 10 eşitliktir: Gμν + Λgμν = 8πTμν.",
      "Einstein 1915'te alan denklemlerini yayımladı; 'en mutlu fikir' 1907'den beri olgunlaşıyordu.",
      "1919 güneş tutulması: yıldız ışığı 1,75 ark-saniye sapma — teorinin tahminiyle birebir.",
      "Mercurius perihel kayması: 43 ark-saniye/yıl açıklaması göreliliğin ilk zaferi.",
      "Kütleçekimsel zaman yavaşlaması laboratuvarda optik saatlerle ölçülür (NIST, 2010).",
      "LIGO, 4 km'lik iki koluyla protonun 1/10.000'i kadar esnemeyi ölçer.",
      "GW150914: iki karadelik (36+29 güneş kütlesi) birleşti; 3 güneş kütlesi dalga oldu.",
      "2017'de GW170817 hem dalga hem ışık gözlendi: çok-ajanslı astronomi çağı açıldı.",
      "Kütleçekimsel mercek: uzak galaksiler arka plandaki kuasarları çoğaltıp büker.",
    ],
  },
  {
    id: "kuantum-alan",
    cat: "fizik",
    title: "Kuantum Alan Teorisi (Standart Model)",
    subtitle:
      "Boşluk yoktur: her şey alanlar, parçacıklar alan titreşimleri — 17 parçacıklı periyodik sistem",
    duration: 125,
    color: "#a3e635",
    stages: [
      { until: 0.15, title: "Boşluk Sanıldığımız Boşluk Değil", text: "Kuantum alan teorisinde evren, iç içe geçmiş alanlardan oluşur: elektron alanı, foton alanı, kuark alanları... Parçacık = alanın bir titreşimi.", era: "temel resim" },
      { until: 0.3, title: "Sanal Parçacıklar", text: "Belirsizlik ilkesi boşluğu kaynatır: parçacık-antiparçacık çiftleri aniden doğar ve yok olur. Casimir etkisi bu 'boşluk basıncını' ölçer.", era: "kuantum köpüğü" },
      { until: 0.46, title: "Standart Model Ailesi", text: "17 temel parçacık: 6 kuark, 6 lepton, 4 kuvvet taşıyıcısı + Higgs. Quarklar asla tek başına görünmez — asla.", era: "1960-1970'ler" },
      { until: 0.62, title: "Higgs Alanı", text: "Higgs alanı evreni dolduran bir 'bal şeriti': parçacıklar içinden geçerken sürtünerek kütle kazanır. Higgs bozonu 2012'de LHC'de yakalandı.", era: "2012" },
      { until: 0.78, title: "Çarpıştırıcı Sahneleri", text: "LHC protonları ışık hızının %99,9999991'ine çıkarıp çarpıştırır: enerji maddelere dönüşür (E=mc²) ve yeni parçacıklar doğar.", era: "LHC" },
      { until: 1, title: "Mükemmel ama Eksik", text: "Standart Model, kütleçekimini, karanlık maddeyi ve nötrino kütlelerinin kökenini açıklayamaz. En doğrulanmış teori VE en eksik teori.", era: "açık sorular" },
    ],
    notes: [
      N(0.05, 0.13, "parçacık = titreşim", 0.5, 0.28),
      N(0.34, 0.42, "Casimir etkisi", 0.28, 0.3),
      N(0.5, 0.58, "17 parçacık", 0.66, 0.3),
      N(0.64, 0.72, "Higgs: 4 Temmuz 2012", 0.28, 0.64),
      N(0.84, 0.92, "kütleçekimi yok", 0.62, 0.66),
    ],
    cues: [
      C(0.001, "hiss", 0.6),
      C(0.15, "shimmer", 0.7),
      C(0.3, "pop", 0.8),
      C(0.46, "bell", 0.9),
      C(0.62, "grow", 0.7),
      C(0.78, "explosion", 0.9),
      C(0.82, "zap", 0.9),
      C(0.94, "chime", 0.7),
    ],
    ticker: [
      "Standart Modelin 17 parçacığından 13'ü 2012'ye kadar laboratuvarda tek tek yakalandı.",
      "Higgs bozonunun varlığı 1964'te öngörüldü; 48 yıl sonra LHC'de görüldü.",
      "Peter Higgs ve François Englert bu keşifle 2013 Nobel Fizik ödülünü paylaştı.",
      "Kuarklar asla serbest görünmez: renk hapsi (confinement) — çektiğinizde yeni kuark doğar.",
      "Foton ve gluon kütlesizdir; W ve Z bozonları Higgs mekaniğiyle kütle kazanır.",
      "Casimir etkisi (1997 ölçüm): iki metal levha boşlukta birbirine 'boşluk basıncıyla' yaklaşır.",
      "Standart Modelin 12 hassas parametresi deneyden girer: teori neden bu değerleri söyemez?",
      "Anomalous magnetic moment ölçümleri modelle milonuncu düzeyde uyumlu: insanlık zirvesi.",
      "Neutrino 1998'de kütleli bulundu: Standart Modelin ilk gerçek çatlağı.",
    ],
  },
  {
    id: "sicim-m-teorisi",
    cat: "fizik",
    title: "Sicim Teorisi ve M-Teorisi",
    subtitle:
      "Parçacık yok: her şey titreşen mini teller — ve uzayın sakladığı 11 boyut",
    duration: 120,
    color: "#f0abfc",
    stages: [
      { until: 0.15, title: "Derinlere Inince", text: "Madde → atom → çekirdek → kuark. Kuarkın da altında mı? Sicim teorisine göre en altta nokta değil, 10⁻³⁵ m'lik titreşen sicimler var.", era: "10⁻³⁵ m" },
      { until: 0.32, title: "Titreşim = Parçacık", text: "Aynı tel farklı frekanslarla titreşir: bir mod elektron, bir mod kuark, bir mod foton. Parçacık tablosu, bir yayın harmonik serisidir.", era: "fikir" },
      { until: 0.48, title: "Ekstra Boyutlar", text: "Matematik tutarlı olması için uzayın 10 boyutu (M-teorisinde 11) gerekir: 6 boyut minik Calabi-Yau şekillerinde katlanmış.", era: "geometri" },
      { until: 0.64, title: "Calabi-Yau Manzaraları", text: "Katlama geometrisi, fizik sabitlerini belirler: her farklı Calabi-Yau şekli, farklı bir evren anlamına gelir — 10⁵⁰⁰ olasılık.", era: "manzara" },
      { until: 0.8, title: "M-Teorisi: Beş Teori Bir", text: "1995'te Edward Witten, 5 farklı sicim teorisinin tek bir 11 boyutlu 'M-teorisi'nin görünümleri olduğunu gösterdi. Zarlar (branes) sahneye çıktı.", era: "1995" },
      { until: 1, title: "Test Edilebilirlik Sorunu", text: "Sicim ölçeği erişilemez: 100 km'lik bir parçacık hızlandırıcı galaksi boyutunda olurdu. Teori matematiği zengin, deneysel kanıtı bekliyor.", era: "tartışma" },
    ],
    notes: [
      N(0.05, 0.13, "tel: 10⁻³⁵ m", 0.5, 0.28),
      N(0.34, 0.42, "titreşim = kimlik", 0.28, 0.3),
      N(0.5, 0.58, "10/11 boyut", 0.66, 0.3),
      N(0.66, 0.74, "Witten, 1995", 0.28, 0.64),
      N(0.84, 0.92, "10⁵⁰⁰ manzara", 0.62, 0.66),
    ],
    cues: [
      C(0.001, "hiss", 0.5),
      C(0.15, "shimmer", 0.8),
      C(0.32, "chime", 0.8),
      C(0.48, "warp", 0.8),
      C(0.64, "bell", 0.8),
      C(0.8, "whoosh", 0.7),
      C(0.94, "glitch", 0.5),
    ],
    ticker: [
      "Sicim teorisinin kökeni 1968 Gabriele Veneziano'nun 'beta fonksiyonu' gözlemine dayanır.",
      "İlk sicim modeli hadronları açıklayamadı; 1970'lerde kütleçekimci gravitonla yeniden doğdu.",
      "Graviton, sicimde KAPALI bir halka titreşimidir: kütleçekimi teoriye bedavaya gelir.",
      "İlk sicim teorisi 26 boyut isterdi (bosonik); süpersimetri bunu 10'a indirdi.",
      "Edward Witten 1990 Fields madalyası kazandı: 'fizikçi olarak matematik ödülü' alan ilk isim.",
      "Calabi-Yau şekilleri 10⁵⁰⁰ çözüm sunar: 'sicim manzarası' tartışması buradan doğar.",
      "AdS/CFT karşılıklığı (Maldacena, 1997) teoriyi holografiyle birleştirdi: 20.000+ atıf.",
      "LHC'de süpersimetrik parçacık bulunamadı: teorinin en öngörülebilir modelleri zayıfladı.",
    ],
  },
  {
    id: "dongusel-kuantum",
    cat: "fizik",
    title: "Döngüsel Kuantum Kütleçekimi",
    subtitle:
      "Uzay-zamanın kendisi kuantadır: ağ ve döngülerden dokunan — tekilliği önleyen teori",
    duration: 115,
    color: "#5eead4",
    stages: [
      { until: 0.15, title: "Uzay Atomsuz Değil", text: "LQG'ye göre uzay-zaman sürekli değil: hacmin en küçük birimi Planck hacmi (10⁻¹⁰⁵ m³). Uzay, döngü ağlarından örülmüş bir doku.", era: "Planck ölçeği" },
      { until: 0.32, title: "Spin Ağları", text: "Alan miktarları, düğümler ve bağlantılardan oluşan 'spin ağlarıyla' kodlanır: her düğüm bir hacim paketi, her bağlantı bir yüzey alanı kuantası.", era: "yapı" },
      { until: 0.48, title: "Alan Kuantadır", text: "Elektromanyetik enerji gibi GEOMETRİ de kuantadır: alan 1, 2, 3... birim paketler halinde. Süreklik, sadece makroskopta illüzyondur.", era: "kotalar" },
      { until: 0.64, title: "Çöküşte Tekillik Yok", text: "Ölen yıldızın çekirdeği sonsuza sıkışamaz: Planck ölçeğinde kuantum baskı bir yay gibi geri iter. Einstein denklemi yeniden yazılır: tekillik yok.", era: "sonuç 1" },
      { until: 0.8, title: "Big Bounce", text: "Sıkışma bir sınıra ulaşır ve tersine döner: önceki evrenin çöküşü, yeni bir patlamaya dönüşür. Kara delik içi bir 'evren doğumu' olabilir.", era: "sonuç 2" },
      { until: 1, title: "Kanıt Arayışı", text: "Gamma ışın patlamalarında enerjiye bağlı hız kayması aranıyor: uzay kuantalysa ışık hafifçe 'takılır'. Gözlemler şimdilik sınır koyuyor, bulamıyor.", era: "bugün" },
    ],
    notes: [
      N(0.05, 0.13, "Planck hacmi", 0.3, 0.28),
      N(0.34, 0.42, "spin ağı", 0.66, 0.3),
      N(0.5, 0.58, "geometri kuantadır", 0.28, 0.62),
      N(0.66, 0.74, "tekillik yok!", 0.62, 0.64),
      N(0.84, 0.92, "gamma ışın testleri", 0.5, 0.3),
    ],
    cues: [
      C(0.001, "hiss", 0.5),
      C(0.15, "shimmer", 0.7),
      C(0.32, "pop", 0.7),
      C(0.48, "rumble", 0.9),
      C(0.64, "explosion", 1.1),
      C(0.8, "whoosh", 0.7),
      C(0.94, "chime", 0.7),
    ],
    ticker: [
      "LQG'nin kurucu isimleri: Abhay Ashtekar, Carlo Rovelli ve Lee Smolin (1980'ler).",
      "Planck hacmi 10⁻¹⁰⁵ m³: bir proton bile içinde milyarlarca 'hücre' barındırır.",
      "Rovelli'nin kitabı 'Yedi Kısa Fizik Dersi' LQG'yi dünyaya tanıttı.",
      "Alan hesabı teoride hacim ve alan OPERATÖRDÜR: spektrumları discrete (paketli).",
      "Kuantum geometridinamiği, uzay-zamanı 'yapı taşlarından' bir ağ gibi örerek simüle eder.",
      "Big Bounce LQG'nin en ünlü öngörüsü: Ashtekar-Singh hesabı 2006'da bunu gösterdi.",
      "Fermi teleskopu gamma patlamalarında Planck ölçeği hız kayması aradı: bulunamadı (sınırlar).",
      "Kara delik entropisi LQG'de de doğru hesaplanır: Bekenstein-Hawking formülüyle uyum.",
    ],
  },
  {
    id: "holografik-evren",
    cat: "fizik",
    title: "Holografik Evren İlkesi",
    subtitle:
      "3D dünya, 2D bir yüzeyde kodlu olabilir: karadelik termodinamiğinden doğan radikal fikir",
    duration: 120,
    color: "#d8b4fe",
    stages: [
      { until: 0.15, title: "Karadelik Bilgi Sorunu", text: "Karadeliğe düşen bilgi kaybolur mu? Hawking 'evet' dedi; kuantum mekanik 'asla' der: bilgi korunmalıdır. 40 yıllık kavganın kökeni.", era: "1970'ler" },
      { until: 0.32, title: "Bekenstein'ın Sezgisi", text: "Jacob Bekenstein (1972): karadeliğin entropisi hacmiyle değil YÜZEY ALANIYLA ölçeklenir. İçerik, sınır yüzeyine 'yazılıdır'.", era: "1972" },
      { until: 0.48, title: "Hawking Entropisi", text: "Formül net: S = A/4 (Planck birimlerinde). Her 4 Planck alanına 1 bit bilgi düşer. Hacim değil, yüzey — hologramın ilk ipucu.", era: "formül" },
      { until: 0.64, title: "Holografik İlke", text: "'t Hooft ve Susskind: evrenin tüm 3D içeriği, sınırlayan 2D yüzeyde kodlanabilir. Içteki dünya, sınırdaki bilginin projeksiyonudur.", era: "1990'lar" },
      { until: 0.8, title: "AdS/CFT: Matematiksel Zafer", text: "Juan Maldacena (1997): antide Sitter uzayındaki kütleçekimi, sınırındaki kuantum teorisiyle BİREBİR eşdeğer. 20.000+ atıfla çağın en önemli makalesi.", era: "1997" },
      { until: 1, title: "Biz Evrenimizde", text: "Evrenimiz AdS değil, ama ilke umut veriyor: uzay, zaman ve kütleçekimi, daha temel bir kuantum bilginin 'yansıması' olabilir. Kimlik sorunu yeniden doğar.", era: "bugün" },
    ],
    notes: [
      N(0.05, 0.13, "bilgi kaybolur mu?", 0.5, 0.28),
      N(0.34, 0.42, "S = A/4", 0.28, 0.3),
      N(0.5, 0.58, "3D ← 2D kod", 0.66, 0.3),
      N(0.66, 0.74, "Maldacena, 1997", 0.28, 0.64),
      N(0.84, 0.92, "bilgi = geometri", 0.62, 0.66),
    ],
    cues: [
      C(0.001, "hiss", 0.5),
      C(0.15, "rumble", 0.7),
      C(0.32, "shimmer", 0.8),
      C(0.48, "bell", 0.8),
      C(0.64, "warp", 0.9),
      C(0.8, "chime", 0.8),
      C(0.94, "shimmer", 0.6),
    ],
    ticker: [
      "Bekenstein-Hawking entropisi: S = kA/4l² (A: olay ufku alanı).",
      "Hawking ve Thorne bilgi kaybına 'evet', Susskind ve 't Hooft 'hayır' dedi; bet Stewart'a yenildi.",
      "Hologram: 2D yüzey 3D imgeyi taşır — ilke adını bu optik olaydan alır.",
      "Maldacena 1997 makalesi 'AdS/CFT karşılıklığı': teorik fiziğin en çok atıf alan makalesi.",
      "Karadelik sayfa alanı: her 4 Planck alanına ~1 nat bilgi — sonucu 1973'ten beri sağlam.",
      "Ryu-Takayanagi formülü (2006): yüzey entanglement'ı, hacim geometrisini üretir.",
      "'Uzay-zaman entanglement'tan dokunur' fikri holografinin modern halefi.",
      "Leonard Susskind 'The Black Hole War' kitabında bu 40 yıllık kavgayı anlattı.",
    ],
  },
];
